//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIAlertViewDelegate.h"
#import "WebServiceObjectDelegate.h"

@class NSMutableArray, NSString, WebServiceObject;

@interface   : NSObject <WebServiceObjectDelegate, UIAlertViewDelegate>
{
    WebServiceObject *_wsObject;
    NSMutableArray *_functionNameArray;
    NSMutableArray *_notYetProcessArxanGuardDetectedArray;
}

+ (void);
+ (void);
+ (void);
+ (void);
+ (void);
+ (id)	;
@property(retain, nonatomic) NSMutableArray *notYetProcessArxanGuardDetectedArray; // @synthesize notYetProcessArxanGuardDetectedArray=_notYetProcessArxanGuardDetectedArray;
@property(retain, nonatomic) NSMutableArray *functionNameArray; // @synthesize functionNameArray=_functionNameArray;
@property(retain, nonatomic) WebServiceObject *wsObject; // @synthesize wsObject=_wsObject;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

