//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSOperation.h"

@class NSMutableData, NSTimer, NSURLConnection;

@interface   : NSOperation
{
    double timeoutInterval;
    NSTimer *timerTimeout;
    NSMutableData *mtdaResponse;
    NSURLConnection *urlConnection;
}

@property(retain, nonatomic) NSURLConnection *urlConnection; // @synthesize urlConnection;
@property(retain, nonatomic) NSMutableData *mtdaResponse; // @synthesize mtdaResponse;
@property(retain, nonatomic) NSTimer *timerTimeout; // @synthesize timerTimeout;
@property(nonatomic) double timeoutInterval; // @synthesize timeoutInterval;
- (void);
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (id)connection:(id)arg1 willSendRequest:(id)arg2 redirectResponse:(id)arg3;
- (void)dealloc;

@end

