//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface   : NSObject
{
}

+ (void)unfoldTableViewWithCellFrame:(struct CGRect)arg1 withTableView:(id)arg2 withMMBPickerView:(id)arg3 withTabBarHeight:(float)arg4 withOverTabBar:(_Bool)arg5;
+ (void)unfoldTableViewWithCellFrame:(struct CGRect)arg1 withTableView:(id)arg2 withMMBPickerView:(id)arg3 withTabBarHeight:(float)arg4;
+ (id)sortTraditionalStrokes:(id)arg1 withKeyName:(id)arg2;
+ (void)setNavigationItemTitle:(id)arg1 NavigationItemId:(id)arg2;
+ (id)scanStrWithCharset:(id)arg1 CharacterSet:(id)arg2;
+ (id)transferToNSStringFromNSDate:(id)arg1 withFormat:(id)arg2 withTimeZone:(id)arg3;
+ (id)transferToNSStringFromNSDate:(id)arg1 withFormat:(id)arg2;
+ (id)transferToNSDateFromNSString:(id)arg1 withFormat:(id)arg2 withTimeZone:(id)arg3;
+ (id)transferToNSDateFromNSString:(id)arg1 withFormat:(id)arg2;
+ (void)showRectLog:(id)arg1 withRect:(struct CGRect)arg2;
+ (void)showAlertWithTitle:(id)arg1 withMsg:(id)arg2 withCancelButtonTitle:(id)arg3 withOtherButtonTitle:(id)arg4 withDelegate:(id)arg5 withTag:(long long)arg6;
+ (void)showAlertWithTitle:(id)arg1 withMsg:(id)arg2 withCancelButtonTitle:(id)arg3 withOtherButtonTitle:(id)arg4 withDelegate:(id)arg5;
+ (id)scaleImage:(id)arg1 toScale:(float)arg2;
+ (id)resizeImage:(id)arg1 toSize:(struct CGSize)arg2;
+ (id);
+ (_Bool)isZH_TW;
+ (_Bool)isShowAlertView;
+ (_Bool)isNumber:(id)arg1;
+ (_Bool)isIncludeTWCharacter:(id)arg1;
+ (_Bool)isLocationServicesEnabled:(id)arg1;
+ (_Bool)isHeadingAvailable:(id)arg1;
+ (id);
+ (id)getURLParmeterValueByName:(id)arg1 withName:(id)arg2;
+ (id)getTxSN;
+ (id)getTraditionalStrokes:(id)arg1;
+ (struct CGRect)getScreenRect;
+ (id)getNow:(id)arg1;
+ (id)getNonDuplicateData:(id)arg1;
+ (int)getLocationServiceStatusWithManager:(id)arg1 withDeviceVersion:(float)arg2;
+ (id)getImageWithColor:(id)arg1;
+ (id)getHTTPConnectionErrorMessageWithError:(id)arg1;
+ (float)getHeightForKeyBoard;
+ (double)getDistanceFrom:(id)arg1 to:(id)arg2;
+ (long long)getDayOfWeek:(id)arg1 withMonth:(id)arg2 withDay:(id)arg3;
+ (id)getColorWithPatternImage:(id)arg1;
+ (id);
+ (id)getBundleDisplayName;
+ (struct __SecKey *)generateRSAPublicKeyWithString:(id)arg1;
+ (id)generateNavigationItemTitle:(id)arg1;
+ (id);
+ (void)foldTableViewWithTableView:(id)arg1 withMMBPickerView:(id)arg2;
+ (id);
+ (id)encodeURL:(id)arg1;
+ (id)	;
+ (id)decodeUTF8Str:(id)arg1;
+ (id)datediffWithBaseDate:(id)arg1 withUnit:(id)arg2 withDiff:(long long)arg3 withAutoAdjustDay:(_Bool)arg4;
+ (id)checkNumberWithAmount:(id)arg1 withFieldTitle:(id)arg2 withMin:(long long)arg3 withMax:(long long)arg4;
+ (id)convertToUTC:(id)arg1;
+ (_Bool)checkLocationServiceStatusWithManager:(id)arg1 withDelegate:(id)arg2;
+ (struct CGSize)calcuteLabelSizeWithText:(id)arg1 withWidth:(double)arg2 withFont:(id)arg3 withLineBreakMode:(long long)arg4;
+ (long long)calcuteASCIILength:(id)arg1;
- (void)dealloc;

@end

