//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCWebKitViewController.h"

#import "CLLocationManagerDelegate.h"

@class AVAudioEngine, AVSpeechSynthesizer, CLLocationManager, NSString, SFSpeechAudioBufferRecognitionRequest, SFSpeechRecognitionTask;

@interface AIRobotViewController : HNCWebKitViewController <CLLocationManagerDelegate>
{
    _Bool _isLoginOpenAIRobotEvent;
    _Bool _isRequestGPSLocation;
    _Bool _isAlreadyDetectGPSLocation;
    NSString *_guideWFID;
    NSString *_funcTXID;
    AVSpeechSynthesizer *_speechSynthesizer;
    SFSpeechAudioBufferRecognitionRequest *_speechAudioBufferRecognitionRequest;
    SFSpeechRecognitionTask *_speechRecognitionTask;
    AVAudioEngine *_audioEngine;
    CLLocationManager *_locationManager;
}

@property(nonatomic) _Bool isAlreadyDetectGPSLocation; // @synthesize isAlreadyDetectGPSLocation=_isAlreadyDetectGPSLocation;
@property(nonatomic) _Bool isRequestGPSLocation; // @synthesize isRequestGPSLocation=_isRequestGPSLocation;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) AVAudioEngine *audioEngine; // @synthesize audioEngine=_audioEngine;
@property(retain, nonatomic) SFSpeechRecognitionTask *speechRecognitionTask; // @synthesize speechRecognitionTask=_speechRecognitionTask;
@property(retain, nonatomic) SFSpeechAudioBufferRecognitionRequest *speechAudioBufferRecognitionRequest; // @synthesize speechAudioBufferRecognitionRequest=_speechAudioBufferRecognitionRequest;
@property(retain, nonatomic) AVSpeechSynthesizer *speechSynthesizer; // @synthesize speechSynthesizer=_speechSynthesizer;
@property(nonatomic) _Bool isLoginOpenAIRobotEvent; // @synthesize isLoginOpenAIRobotEvent=_isLoginOpenAIRobotEvent;
@property(retain, nonatomic) NSString *funcTXID; // @synthesize funcTXID=_funcTXID;
@property(retain, nonatomic) NSString *guideWFID; // @synthesize guideWFID=_guideWFID;
- (void)WebServiceObject:(id)arg1 didCompleteCallHNCBAPIWithHeader:(id)arg2 withCallHNCBAPIResponseBody:(id)arg3;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)closeAIRobot;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

