//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSMutableData, NSObject<AsyncImageViewDelegate><NSObject>, NSString, NSURLConnection;

@interface AsyncImageView : UIView
{
    NSObject<AsyncImageViewDelegate><NSObject> *delegateAsync;
    NSURLConnection *urlConnection;
    NSMutableData *mtdaResponse;
    NSString *sImageURL;
    struct CGSize sizeRound;
    struct CGSize sizeShadow;
    struct CGSize sizeOval;
}

@property(nonatomic) struct CGSize sizeOval; // @synthesize sizeOval;
@property(nonatomic) struct CGSize sizeShadow; // @synthesize sizeShadow;
@property(nonatomic) struct CGSize sizeRound; // @synthesize sizeRound;
@property(retain, nonatomic) NSString *sImageURL; // @synthesize sImageURL;
@property(retain, nonatomic) NSMutableData *mtdaResponse; // @synthesize mtdaResponse;
@property(retain, nonatomic) NSURLConnection *urlConnection; // @synthesize urlConnection;
@property(retain, nonatomic) NSObject<AsyncImageViewDelegate><NSObject> *delegateAsync; // @synthesize delegateAsync;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)dealloc;
- (id)image;
- (void)loadImageFromURLString:(id)arg1;
- (void)loadImageFromURL:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

