//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MajorViewController.h"

@class APIDataManager, NSString, UIImageView;

@interface BankInfo : MajorViewController
{
    NSString *_nickname;
    NSString *_cardnumber;
    NSString *_base64ImageString;
    NSString *_creditCardImagePath;
    NSString *_creditCardImageName;
    NSString *_creditCardCardType;
    NSString *_staffString;
    UIImageView *_imageV;
    APIDataManager *_datamanager;
}

@property(retain, nonatomic) APIDataManager *datamanager; // @synthesize datamanager=_datamanager;
@property(retain, nonatomic) UIImageView *imageV; // @synthesize imageV=_imageV;
@property(retain, nonatomic) NSString *staffString; // @synthesize staffString=_staffString;
@property(retain, nonatomic) NSString *creditCardCardType; // @synthesize creditCardCardType=_creditCardCardType;
@property(retain, nonatomic) NSString *creditCardImageName; // @synthesize creditCardImageName=_creditCardImageName;
@property(retain, nonatomic) NSString *creditCardImagePath; // @synthesize creditCardImagePath=_creditCardImagePath;
@property(retain, nonatomic) NSString *base64ImageString; // @synthesize base64ImageString=_base64ImageString;
@property(retain, nonatomic) NSString *cardnumber; // @synthesize cardnumber=_cardnumber;
@property(retain, nonatomic) NSString *nickname; // @synthesize nickname=_nickname;
- (void)didReceiveMemoryWarning;
- (_Bool)SwitchDate:(id)arg1;
- (void)createView;
- (void)viewDidLoad;

@end

