//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCTableViewController.h"

#import "AsyncImageViewDelegate.h"

@class NSLayoutConstraint, NSMutableDictionary, NSString, UIImageView, UITableViewCell;

@interface BenefitDetailViewController : HNCTableViewController <AsyncImageViewDelegate>
{
    NSLayoutConstraint *_benefitDetailListHeightConstraint;
    NSString *_pageOrder;
    NSMutableDictionary *_selectBenefitSummaryDictionary;
    NSMutableDictionary *_benefitDetailDictionary;
    UITableViewCell *_largeImageCell;
    UIImageView *_largeImageView;
}

@property(retain, nonatomic) UIImageView *largeImageView; // @synthesize largeImageView=_largeImageView;
@property(retain, nonatomic) UITableViewCell *largeImageCell; // @synthesize largeImageCell=_largeImageCell;
@property(retain, nonatomic) NSMutableDictionary *benefitDetailDictionary; // @synthesize benefitDetailDictionary=_benefitDetailDictionary;
@property(retain, nonatomic) NSMutableDictionary *selectBenefitSummaryDictionary; // @synthesize selectBenefitSummaryDictionary=_selectBenefitSummaryDictionary;
@property(retain, nonatomic) NSString *pageOrder; // @synthesize pageOrder=_pageOrder;
@property(retain, nonatomic) NSLayoutConstraint *benefitDetailListHeightConstraint; // @synthesize benefitDetailListHeightConstraint=_benefitDetailListHeightConstraint;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)callPhoneButtonClickEvent:(id)arg1;
- (void)linkButtonClickEvent:(id)arg1;
- (void)mapViewButtonClickEvent:(id)arg1;
- (id)generateLinkButtonWithFrame:(struct CGRect)arg1 linkButtonTitle:(id)arg2;
- (void)imageDidFinishLoading:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)WebServiceObject:(id)arg1 didCompleteAT0002WithHeader:(id)arg2 withAT0002ResponseBody:(id)arg3;
- (void)WebServiceObject:(id)arg1 didCompleteAP0006WithHeader:(id)arg2 withAP0006ResponseBody:(id)arg3;
- (void)didReceiveMemoryWarning;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)dealloc;
- (void)updateViewConstraints;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

