//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UILabel;

@interface BonusView : UIView
{
    struct CGSize _initrinsicContentSize;
    UIView *_bonusView;
    UILabel *_orderTotalHeaderLabel;
    UILabel *_orderTotalLabel;
    UILabel *_bonusDiscountTotalHeaderLabel;
    UILabel *_bonusDiscount;
    UILabel *_refundLabel;
    UILabel *_refundHeaderLabel;
    UIView *_lineView;
    UILabel *_paymentTotalHeaderLabel;
    UILabel *_paymentTotalLabel;
    UILabel *_bonusHeaderLabel;
    UILabel *_bonusTotalLabel;
}

- (void).cxx_destruct;
@property(retain, nonatomic) UILabel *bonusTotalLabel; // @synthesize bonusTotalLabel=_bonusTotalLabel;
@property(retain, nonatomic) UILabel *bonusHeaderLabel; // @synthesize bonusHeaderLabel=_bonusHeaderLabel;
@property(retain, nonatomic) UILabel *paymentTotalLabel; // @synthesize paymentTotalLabel=_paymentTotalLabel;
@property(retain, nonatomic) UILabel *paymentTotalHeaderLabel; // @synthesize paymentTotalHeaderLabel=_paymentTotalHeaderLabel;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UILabel *refundHeaderLabel; // @synthesize refundHeaderLabel=_refundHeaderLabel;
@property(retain, nonatomic) UILabel *refundLabel; // @synthesize refundLabel=_refundLabel;
@property(retain, nonatomic) UILabel *bonusDiscount; // @synthesize bonusDiscount=_bonusDiscount;
@property(retain, nonatomic) UILabel *bonusDiscountTotalHeaderLabel; // @synthesize bonusDiscountTotalHeaderLabel=_bonusDiscountTotalHeaderLabel;
@property(retain, nonatomic) UILabel *orderTotalLabel; // @synthesize orderTotalLabel=_orderTotalLabel;
@property(retain, nonatomic) UILabel *orderTotalHeaderLabel; // @synthesize orderTotalHeaderLabel=_orderTotalHeaderLabel;
@property(retain, nonatomic) UIView *bonusView; // @synthesize bonusView=_bonusView;
- (struct CGSize)intrinsicContentSize;
- (void)initTextColor;
- (void)getLabelText:(id)arg1 totals:(id)arg2;
- (void)coustomInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

