//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class APIDataManager, BonusdetailsData, NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, UIButton, UITableView, UIView;

@interface BonusDetailsViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    NSArray *_headers;
    UIButton *_refundButton;
    UITableView *_tableView;
    NSDictionary *_responseObject;
    NSMutableDictionary *_dictDetail;
    NSString *_back;
    UIView *_blankView;
    APIDataManager *_dataManager;
    BonusdetailsData *_bonusdetailsData;
    CDUnknownBlockType _isBackBlock;
    NSMutableArray *_arraykey;
    NSMutableDictionary *_dic;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSMutableDictionary *dic; // @synthesize dic=_dic;
@property(retain, nonatomic) NSMutableArray *arraykey; // @synthesize arraykey=_arraykey;
@property(copy, nonatomic) CDUnknownBlockType isBackBlock; // @synthesize isBackBlock=_isBackBlock;
@property(retain, nonatomic) BonusdetailsData *bonusdetailsData; // @synthesize bonusdetailsData=_bonusdetailsData;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
@property(retain, nonatomic) UIView *blankView; // @synthesize blankView=_blankView;
@property(retain, nonatomic) NSString *back; // @synthesize back=_back;
@property(retain, nonatomic) NSMutableDictionary *dictDetail; // @synthesize dictDetail=_dictDetail;
@property(retain, nonatomic) NSDictionary *responseObject; // @synthesize responseObject=_responseObject;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIButton *refundButton; // @synthesize refundButton=_refundButton;
@property(retain) NSArray *headers; // @synthesize headers=_headers;
- (void)showRefundButton:(id)arg1;
- (void)system_maintenance:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)initData;
- (void)initButton;
- (void)viewWillAppear:(_Bool)arg1;
- (void)backRecord;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

