//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MajorViewController.h"

#import "CommonAlertsDelegate.h"
#import "RevealDescriptionViewDeleaget.h"
#import "UITextFieldDelegate.h"

@class APIDataManager, NSLayoutConstraint, NSString, RevealDescriptionView, UIButton, UILabel, UISwitch, UITextField, UITextView, UIView;

@interface CalculatorViewController : MajorViewController <RevealDescriptionViewDeleaget, UITextFieldDelegate, CommonAlertsDelegate>
{
    _Bool _quickPay;
    UITextField *_amtField;
    UILabel *_typeLabel;
    UILabel *_accLabel;
    UILabel *_toolLabel;
    NSString *_shopName;
    NSString *_originalQrcode;
    APIDataManager *_dataManager;
    NSString *_strPayType;
    NSString *_strPayId;
    NSString *_type;
    NSString *_acc;
    NSString *_tool;
    NSString *_credPan;
    UILabel *_creditTPanLabel;
    UIButton *_btnShowQr;
    UITextView *_shopNameTextView;
    UIView *_creditTPanView;
    UIView *_amtView;
    NSString *_tmId;
    NSLayoutConstraint *_creditTPanViewHeight;
    UISwitch *_bonusSwitch;
    NSString *_pBalance;
    NSString *_errMsg;
    NSString *_pRedeemState;
    UILabel *_pBalanceLabel;
    UILabel *_redeemHeaderLabel;
    UIView *_lineView;
    UILabel *_bonusHeaderLabel;
    UIButton *_iconDescriptionBt;
    UIView *_blockView;
    RevealDescriptionView *_descriptionView;
}

@property(retain, nonatomic) RevealDescriptionView *descriptionView; // @synthesize descriptionView=_descriptionView;
@property(retain, nonatomic) UIView *blockView; // @synthesize blockView=_blockView;
@property(retain, nonatomic) UIButton *iconDescriptionBt; // @synthesize iconDescriptionBt=_iconDescriptionBt;
@property(retain, nonatomic) UILabel *bonusHeaderLabel; // @synthesize bonusHeaderLabel=_bonusHeaderLabel;
@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UILabel *redeemHeaderLabel; // @synthesize redeemHeaderLabel=_redeemHeaderLabel;
@property(retain, nonatomic) UILabel *pBalanceLabel; // @synthesize pBalanceLabel=_pBalanceLabel;
@property(retain, nonatomic) NSString *pRedeemState; // @synthesize pRedeemState=_pRedeemState;
@property(retain, nonatomic) NSString *errMsg; // @synthesize errMsg=_errMsg;
@property(retain, nonatomic) NSString *pBalance; // @synthesize pBalance=_pBalance;
@property(retain, nonatomic) UISwitch *bonusSwitch; // @synthesize bonusSwitch=_bonusSwitch;
@property(retain, nonatomic) NSLayoutConstraint *creditTPanViewHeight; // @synthesize creditTPanViewHeight=_creditTPanViewHeight;
@property(retain, nonatomic) NSString *tmId; // @synthesize tmId=_tmId;
@property(retain, nonatomic) UIView *amtView; // @synthesize amtView=_amtView;
@property(retain, nonatomic) UIView *creditTPanView; // @synthesize creditTPanView=_creditTPanView;
@property(retain, nonatomic) UITextView *shopNameTextView; // @synthesize shopNameTextView=_shopNameTextView;
@property(retain, nonatomic) UIButton *btnShowQr; // @synthesize btnShowQr=_btnShowQr;
@property(retain, nonatomic) UILabel *creditTPanLabel; // @synthesize creditTPanLabel=_creditTPanLabel;
@property(nonatomic) _Bool quickPay; // @synthesize quickPay=_quickPay;
@property(retain, nonatomic) NSString *credPan; // @synthesize credPan=_credPan;
@property(retain, nonatomic) NSString *tool; // @synthesize tool=_tool;
@property(retain, nonatomic) NSString *acc; // @synthesize acc=_acc;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *strPayId; // @synthesize strPayId=_strPayId;
@property(retain, nonatomic) NSString *strPayType; // @synthesize strPayType=_strPayType;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
@property(retain, nonatomic) NSString *originalQrcode; // @synthesize originalQrcode=_originalQrcode;
@property(retain, nonatomic) NSString *shopName; // @synthesize shopName=_shopName;
@property(retain, nonatomic) UILabel *toolLabel; // @synthesize toolLabel=_toolLabel;
@property(retain, nonatomic) UILabel *accLabel; // @synthesize accLabel=_accLabel;
@property(retain, nonatomic) UILabel *typeLabel; // @synthesize typeLabel=_typeLabel;
@property(retain, nonatomic) UITextField *amtField; // @synthesize amtField=_amtField;
- (void)dealloc;
- (void)didIsPointRedeemFailed:(id)arg1;
- (void)didIsPointRedeemSuccess:(id)arg1;
- (void)bonusSwitchisOnDelegate:(_Bool)arg1;
- (void)switchIsChanged:(id)arg1;
- (void)system_maintenance:(id)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)initBonus;
- (void)pressDoneDelegate;
- (void)revealDescription:(id)arg1;
- (void)btnShowQr:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)doneWithNumberPad;
- (void)createContentView;
- (void)viewDidLoad;
- (void)isNotLogin:(id)arg1;
- (void)apiError:(id)arg1;
- (void)CALCULATOR_SCAN_FAILED:(id)arg1;
- (void)CALCULATOR_SCAN_SUCCESS:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

