//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FMDatabaseQueue;

@interface ChatDBService : NSObject
{
    FMDatabaseQueue *_my_FMDatabaseQueue;
}

+ (id)getInstance;
@property(retain, nonatomic) FMDatabaseQueue *my_FMDatabaseQueue; // @synthesize my_FMDatabaseQueue=_my_FMDatabaseQueue;
- (void)clearData;
- (id)queryChat;
- (void)updateReadSuccess:(id)arg1;
- (void)updateIsSendSuccess:(id)arg1;
- (_Bool)saveChat:(id)arg1 contentType:(id)arg2 content:(id)arg3 other:(id)arg4;
- (id)init;

@end

