//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ColorConfig : NSObject
{
}

+ (id)purpleyGrey;
+ (id)paleGrey;
+ (id)beige;
+ (id)whiteTwoColor;
+ (id)whiteColor;
+ (id)toolbarBackgroundColor;
+ (id)greyishColor;
+ (id)lightGrayColor;
+ (id)descriptionOrangeColor;
+ (id)textGrayColor;
+ (id)backgroundColor;
+ (id)redColor;

@end

