//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilMap_Entry.h"

@class NSString;

@interface ComGoogleJ2objcNetIosHttpURLConnection_HeaderEntry : NSObject <JavaUtilMap_Entry>
{
    NSString *key_;
    NSString *value_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)setValueWithId:(id)arg1;
- (id)getValue;
- (id)getKey;
- (id)initWithNSString:(id)arg1 withNSString:(id)arg2;

@end

