//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CommonAlerts : NSObject
{
    id <CommonAlertsDelegate> _commonAlertsDelegate;
}

+ (void)showNotLoginAlert:(id)arg1 message:(id)arg2;
+ (void)showMessageAlert:(id)arg1 message:(id)arg2;
+ (void)showApiErrorAlert:(id)arg1;
- (void).cxx_destruct;
@property(nonatomic) __weak id <CommonAlertsDelegate> commonAlertsDelegate; // @synthesize commonAlertsDelegate=_commonAlertsDelegate;
- (void)showSwitchMessageAlert:(id)arg1 message:(id)arg2 bonusSwitch:(id)arg3;

@end

