//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface CommonMethod : NSObject
{
}

+ (int)convertStringToInt:(id)arg1;
+ (_Bool)verifyTwIdWithId:(id)arg1;
+ (long long)daysBetweenDate:(id)arg1 andDate:(id)arg2;
+ (id)addSeparatorLineBellowView:(id)arg1 margin:(double)arg2 superView:(id)arg3;
+ (void)changeNavigationbarBackgroundColor:(id)arg1;
+ (id)imageWithColor:(id)arg1 size:(struct CGSize)arg2;

@end

