//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MajorViewController.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"
#import "UITextFieldDelegate.h"
#import "WKNavigationDelegate.h"

@class APIDataManager, EWalletUtils, NSArray, NSMutableArray, NSString, UIButton, UIPickerView, UIScrollView, UITextField, UITextView, UIToolbar, WKWebView;

@interface ConnectCreditCardViewController : MajorViewController <UIPickerViewDelegate, UIPickerViewDataSource, UITextFieldDelegate, WKNavigationDelegate>
{
    _Bool _isSetAsDefault;
    _Bool _confirmFile;
    APIDataManager *_dataManager;
    EWalletUtils *_ewallet;
    long long _viewType;
    UIButton *_defaultBtn;
    NSMutableArray *_creditCardListArray;
    NSMutableArray *_creditCardNameArray;
    UITextField *_cardNumberTextField;
    UITextField *_expireDateTextField;
    UITextField *_referralNumberField;
    UITextField *_cvcTextField;
    UITextField *_nickNameTextField;
    UIPickerView *_cardNumberPickerView;
    UIPickerView *_expireDatePickerView;
    UIToolbar *_toolbar;
    NSString *_qrcode;
    UIScrollView *_scrollView;
    UITextView *_agreedClauseTextView;
    UIButton *_btnCheckAgree;
    NSString *_maId;
    WKWebView *_webKitView;
    NSString *_selectedExpireYear;
    NSString *_selectedExpireMonth;
    NSArray *_monthArray;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSArray *monthArray; // @synthesize monthArray=_monthArray;
@property(retain, nonatomic) NSString *selectedExpireMonth; // @synthesize selectedExpireMonth=_selectedExpireMonth;
@property(retain, nonatomic) NSString *selectedExpireYear; // @synthesize selectedExpireYear=_selectedExpireYear;
@property(nonatomic) _Bool confirmFile; // @synthesize confirmFile=_confirmFile;
@property(retain, nonatomic) WKWebView *webKitView; // @synthesize webKitView=_webKitView;
@property(retain, nonatomic) NSString *maId; // @synthesize maId=_maId;
@property(retain, nonatomic) UIButton *btnCheckAgree; // @synthesize btnCheckAgree=_btnCheckAgree;
@property(retain, nonatomic) UITextView *agreedClauseTextView; // @synthesize agreedClauseTextView=_agreedClauseTextView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) NSString *qrcode; // @synthesize qrcode=_qrcode;
@property(retain, nonatomic) UIToolbar *toolbar; // @synthesize toolbar=_toolbar;
@property(retain, nonatomic) UIPickerView *expireDatePickerView; // @synthesize expireDatePickerView=_expireDatePickerView;
@property(retain, nonatomic) UIPickerView *cardNumberPickerView; // @synthesize cardNumberPickerView=_cardNumberPickerView;
@property(retain, nonatomic) UITextField *nickNameTextField; // @synthesize nickNameTextField=_nickNameTextField;
@property(retain, nonatomic) UITextField *cvcTextField; // @synthesize cvcTextField=_cvcTextField;
@property(retain, nonatomic) UITextField *referralNumberField; // @synthesize referralNumberField=_referralNumberField;
@property(retain, nonatomic) UITextField *expireDateTextField; // @synthesize expireDateTextField=_expireDateTextField;
@property(retain, nonatomic) UITextField *cardNumberTextField; // @synthesize cardNumberTextField=_cardNumberTextField;
@property(retain, nonatomic) NSMutableArray *creditCardNameArray; // @synthesize creditCardNameArray=_creditCardNameArray;
@property(retain, nonatomic) NSMutableArray *creditCardListArray; // @synthesize creditCardListArray=_creditCardListArray;
@property(retain, nonatomic) UIButton *defaultBtn; // @synthesize defaultBtn=_defaultBtn;
@property(nonatomic) long long viewType; // @synthesize viewType=_viewType;
@property(nonatomic) _Bool isSetAsDefault; // @synthesize isSetAsDefault=_isSetAsDefault;
@property(retain, nonatomic) EWalletUtils *ewallet; // @synthesize ewallet=_ewallet;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)system_maintenance:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFiledEditChanged:(id)arg1;
- (void)textFieldDidBeginEditing:(id)arg1;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (double)pickerView:(id)arg1 rowHeightForComponent:(long long)arg2;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)btnCheckAgree:(id)arg1;
- (void)getCreditCardListFailed:(id)arg1;
- (void)getCreditCardListSuccess:(id)arg1;
- (void)verifyCreditCardInfoSuccessFailed:(id)arg1;
- (void)verifyCreditCardInfoSuccess:(id)arg1;
- (void)btnRight:(id)arg1;
- (void)pickerDone:(id)arg1;
- (void)onClickDefaultBtn;
- (long long)getCurrentDateWithFormmat:(id)arg1;
- (_Bool)isBlankOrNil:(id)arg1;
- (void)createContentView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

