//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCViewController.h"

#import "UITextFieldDelegate.h"

@class NSArray, NSDictionary, NSString, UIButton, UILabel, UITextField, UIView;

@interface ConnectionSettingViewController : HNCViewController <UITextFieldDelegate>
{
    _Bool _isFromInitAppConnectionSetting;
    UITextField *_protocolField;
    UITextField *_ipAddressField;
    UIButton *_commonButton;
    UIButton *_cancelButton;
    UILabel *_versionInfoLabel;
    NSDictionary *_remoteNotificationInfo;
    UIView *_showPickerViewFromComponent;
    NSArray *_protocolArray;
    NSArray *_ipAddressArray;
}

@property(retain, nonatomic) NSArray *ipAddressArray; // @synthesize ipAddressArray=_ipAddressArray;
@property(retain, nonatomic) NSArray *protocolArray; // @synthesize protocolArray=_protocolArray;
@property(retain, nonatomic) UIView *showPickerViewFromComponent; // @synthesize showPickerViewFromComponent=_showPickerViewFromComponent;
@property(nonatomic) _Bool isFromInitAppConnectionSetting; // @synthesize isFromInitAppConnectionSetting=_isFromInitAppConnectionSetting;
@property(retain, nonatomic) NSDictionary *remoteNotificationInfo; // @synthesize remoteNotificationInfo=_remoteNotificationInfo;
@property(retain, nonatomic) UILabel *versionInfoLabel; // @synthesize versionInfoLabel=_versionInfoLabel;
@property(retain, nonatomic) UIButton *cancelButton; // @synthesize cancelButton=_cancelButton;
@property(retain, nonatomic) UIButton *commonButton; // @synthesize commonButton=_commonButton;
@property(retain, nonatomic) UITextField *ipAddressField; // @synthesize ipAddressField=_ipAddressField;
@property(retain, nonatomic) UITextField *protocolField; // @synthesize protocolField=_protocolField;
- (void)processConnectionSetting;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)buttonClickEvent:(id)arg1;
- (void)mmbPickerViewBtnDoneClickEvent:(id)arg1;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

