//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DalvikSystemCloseGuard_Reporter.h"

@interface DalvikSystemCloseGuard_DefaultReporter : NSObject <DalvikSystemCloseGuard_Reporter>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)init;
- (void)reportWithNSString:(id)arg1 withJavaLangThrowable:(id)arg2;

@end

