//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "DalvikSystemBlockGuard_Policy.h"

@interface DalvikSystemBlockGuard_$1 : NSObject <DalvikSystemBlockGuard_Policy>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)init;
- (int)getPolicyMask;
- (void)onNetwork;
- (void)onReadFromDisk;
- (void)onWriteToDisk;

@end

