//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface EWalletData : NSObject
{
    NSString *_action;
    NSString *_mobile;
    NSString *_custId;
    NSString *_outAcct;
    NSString *_nickName;
    NSString *_keypascoTimeOut;
    NSString *_isLogin;
    NSString *_isOTP;
    NSString *_twqrp;
}

@property(retain, nonatomic) NSString *twqrp; // @synthesize twqrp=_twqrp;
@property(retain, nonatomic) NSString *isOTP; // @synthesize isOTP=_isOTP;
@property(retain, nonatomic) NSString *isLogin; // @synthesize isLogin=_isLogin;
@property(retain, nonatomic) NSString *keypascoTimeOut; // @synthesize keypascoTimeOut=_keypascoTimeOut;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(retain, nonatomic) NSString *outAcct; // @synthesize outAcct=_outAcct;
@property(retain, nonatomic) NSString *custId; // @synthesize custId=_custId;
@property(retain, nonatomic) NSString *mobile; // @synthesize mobile=_mobile;
@property(retain, nonatomic) NSString *action; // @synthesize action=_action;
- (void)dealloc;

@end

