//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;

@protocol EWalletUtilsDelegate

@optional
- (void)completeVerifyQRCodeCallBackWithReturnMsg:(NSString *)arg1 rtnCode:(NSString *)arg2;
- (void)completeCheckQRCodeCallBackWithReturnMsg:(NSString *)arg1;
- (void)completeSignEndCallBackWithStatusCode:(NSString *)arg1 resultCode:(NSString *)arg2;
- (void)completeSignBeginCallBackWithStatusCode:(NSString *)arg1 taskId:(NSString *)arg2;
- (void)completeDetectKeypascoStatusCallBackWithStatusCode:(NSString *)arg1 keypascoStatus:(NSString *)arg2 deviceName:(NSString *)arg3 deviceCount:(NSString *)arg4;
- (void)completeLoginCallBackWithStatusCode:(NSString *)arg1 guideWFID:(NSString *)arg2 qrCodeStr:(NSString *)arg3;
@end

