//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaLangReflectAccessibleObject.h"

@class IOSClass, JavaMethodMetadata, NSMethodSignature;

@interface ExecutableMember : JavaLangReflectAccessibleObject
{
    IOSClass *class_;
    SEL selector_;
    NSMethodSignature *methodSignature_;
    JavaMethodMetadata *metadata_;
}

- (void)dealloc;
@property(readonly) NSMethodSignature *signature;
- (_Bool)isBridge;
- (_Bool)isVarArgs;
- (id)toGenericString;
- (id)getParameterAnnotations;
- (id)getDeclaredAnnotations;
- (id)internalName;
- (id)getExceptionTypes;
- (_Bool)isSynthetic;
- (id)getGenericExceptionTypes;
- (id)getGenericParameterTypes;
- (id)getTypeParameters;
- (id)getDeclaringClass;
- (id)getParameterTypes;
- (int)getModifiers;
- (id)getName;
- (id)initWithMethodSignature:(id)arg1 selector:(SEL)arg2 class:(id)arg3 metadata:(id)arg4;

@end

