//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface GoogleAnaliticsTools : NSObject
{
    NSArray *_categoryArray;
    NSArray *_actionArray;
    NSArray *_scViewNm;
    id <GAITracker> _tracker;
}

@property(retain, nonatomic) id <GAITracker> tracker; // @synthesize tracker=_tracker;
@property(retain, nonatomic) NSArray *scViewNm; // @synthesize scViewNm=_scViewNm;
@property(retain, nonatomic) NSArray *actionArray; // @synthesize actionArray=_actionArray;
@property(retain, nonatomic) NSArray *categoryArray; // @synthesize categoryArray=_categoryArray;
- (void)event:(id)arg1 withAction:(id)arg2 withLabel:(id)arg3;
- (void)scView:(id)arg1;
- (void)dealloc;
- (id)init;

@end

