//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class APIDataManager, NSMutableArray, NSMutableString;

@interface GraphicPasswordView : UIView
{
    int _iphoneSize;
    NSMutableString *gesturePw;
    id <GrapicPasswordDelegate> delegate;
    APIDataManager *_dataManager;
    long long _viewType;
    NSMutableArray *_selectedButtons;
    struct CGPoint _currentPoint;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGPoint currentPoint; // @synthesize currentPoint=_currentPoint;
@property(retain, nonatomic) NSMutableArray *selectedButtons; // @synthesize selectedButtons=_selectedButtons;
@property(nonatomic) long long viewType; // @synthesize viewType=_viewType;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
@property(nonatomic) int iphoneSize; // @synthesize iphoneSize=_iphoneSize;
@property(retain, nonatomic) id <GrapicPasswordDelegate> delegate; // @synthesize delegate;
@property(retain, nonatomic) NSMutableString *gesturePw; // @synthesize gesturePw;
- (id)removeRepeatChar:(id)arg1;
- (void)drawRect:(struct CGRect)arg1;
- (void)buttonSelectedWithTouch:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

