//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MajorViewController.h"

#import "GrapicPasswordDelegate.h"
#import "UIAlertViewDelegate.h"

@class APIDataManager, EWalletUtils, GraphicPasswordView, LAContext, NSMutableArray, NSMutableDictionary, NSMutableString, NSNumber, NSString, NSTimer, UIButton, UILabel, UIView;

@interface GraphicPasswordSettingViewController : MajorViewController <GrapicPasswordDelegate, UIAlertViewDelegate>
{
    float _version;
    APIDataManager *_dataManager;
    GraphicPasswordView *_graphicPwdView;
    NSMutableString *_strFirstPwd;
    NSMutableString *_strSecondPwd;
    UILabel *_lbTopTitle;
    UIButton *_btnRight;
    UIButton *_btnConfirmPay;
    NSString *_is_touchID;
    NSString *_need_pwd;
    long long _viewType;
    NSNumber *_tmId;
    NSNumber *_maId;
    NSString *_theNewPwType;
    LAContext *_myContext;
    UIView *_navTopView;
    NSMutableArray *_cardArray;
    EWalletUtils *_ewallet;
    NSMutableDictionary *_dic;
    NSString *_taskId;
    NSTimer *_timer;
    NSString *_mtsTypeId;
    NSString *_removeCardType;
    NSString *_qrcode;
    NSString *_pBalance;
    NSString *_pRedeemState;
    NSString *_pIsQueryAgain;
    NSString *_pIconPointDesc;
    long long _keypascoStartTime;
}

- (void).cxx_destruct;
@property(nonatomic) long long keypascoStartTime; // @synthesize keypascoStartTime=_keypascoStartTime;
@property(retain, nonatomic) NSString *pIconPointDesc; // @synthesize pIconPointDesc=_pIconPointDesc;
@property(retain, nonatomic) NSString *pIsQueryAgain; // @synthesize pIsQueryAgain=_pIsQueryAgain;
@property(retain, nonatomic) NSString *pRedeemState; // @synthesize pRedeemState=_pRedeemState;
@property(retain, nonatomic) NSString *pBalance; // @synthesize pBalance=_pBalance;
@property(nonatomic) float version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *qrcode; // @synthesize qrcode=_qrcode;
@property(retain, nonatomic) NSString *removeCardType; // @synthesize removeCardType=_removeCardType;
@property(retain, nonatomic) NSString *mtsTypeId; // @synthesize mtsTypeId=_mtsTypeId;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSString *taskId; // @synthesize taskId=_taskId;
@property(retain, nonatomic) NSMutableDictionary *dic; // @synthesize dic=_dic;
@property(retain, nonatomic) EWalletUtils *ewallet; // @synthesize ewallet=_ewallet;
@property(retain, nonatomic) NSMutableArray *cardArray; // @synthesize cardArray=_cardArray;
@property(retain, nonatomic) UIView *navTopView; // @synthesize navTopView=_navTopView;
@property(retain, nonatomic) LAContext *myContext; // @synthesize myContext=_myContext;
@property(retain, nonatomic) NSString *theNewPwType; // @synthesize theNewPwType=_theNewPwType;
@property(retain, nonatomic) NSNumber *maId; // @synthesize maId=_maId;
@property(retain, nonatomic) NSNumber *tmId; // @synthesize tmId=_tmId;
@property(nonatomic) long long viewType; // @synthesize viewType=_viewType;
@property(retain, nonatomic) NSString *need_pwd; // @synthesize need_pwd=_need_pwd;
@property(retain, nonatomic) NSString *is_touchID; // @synthesize is_touchID=_is_touchID;
@property(retain, nonatomic) UIButton *btnConfirmPay; // @synthesize btnConfirmPay=_btnConfirmPay;
@property(retain, nonatomic) UIButton *btnRight; // @synthesize btnRight=_btnRight;
@property(retain, nonatomic) UILabel *lbTopTitle; // @synthesize lbTopTitle=_lbTopTitle;
@property(retain, nonatomic) NSMutableString *strSecondPwd; // @synthesize strSecondPwd=_strSecondPwd;
@property(retain, nonatomic) NSMutableString *strFirstPwd; // @synthesize strFirstPwd=_strFirstPwd;
@property(retain, nonatomic) GraphicPasswordView *graphicPwdView; // @synthesize graphicPwdView=_graphicPwdView;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
- (void)system_maintenance:(id)arg1;
- (void)removeAcc_FAILED:(id)arg1;
- (void)removeAcc_SUCCESS:(id)arg1;
- (void)isNotLogin:(id)arg1;
- (void)apiError:(id)arg1;
- (void)GET_FIRST_LOGIN_FAILED:(id)arg1;
- (void)GET_FIRST_LOGIN_SUCCESS:(id)arg1;
- (void)FORGET_PW_BY_MOB_FAILED:(id)arg1;
- (void)FORGET_PW_BY_MOB_SUCCESS:(id)arg1;
- (void)verifyMeth:(id)arg1 mobile:(id)arg2;
- (void)timerFunc;
- (void)keypascoClock;
- (void)dokeypasco;
- (void)completeSignEndCallBackWithStatusCode:(id)arg1 resultCode:(id)arg2;
- (void)completeSignBeginCallBackWithStatusCode:(id)arg1 taskId:(id)arg2;
- (void)completeDetectKeypascoStatusCallBackWithStatusCode:(id)arg1 keypascoStatus:(id)arg2 deviceName:(id)arg3 deviceCount:(id)arg4;
- (void)graphicError;
- (void)addMember;
- (void)setGraphicPassword:(id)arg1;
- (void)detectKeypasco;
- (void)btnRight:(id)arg1;
- (void)btnLeft:(id)arg1;
- (void)createContentView;
- (void)verifyPwFailed:(id)arg1;
- (void)verifyPwSuccess:(id)arg1;
- (void)didUpdatePwFailed:(id)arg1;
- (void)creatQrcodeFail:(id)arg1;
- (void)creatQrcode:(id)arg1;
- (void)pwpayIdTokenType:(id)arg1;
- (void)didUpdatePwSuccess:(id)arg1;
- (void)goToSetNewNumberPw;
- (void)backToChangePW;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)didQRCodeBuyerConfirmFailed:(id)arg1;
- (void)didQRCodeBuyerConfirmSuccess:(id)arg1;
- (void)getCreditCardListFailed:(id)arg1;
- (void)getCreditCardListSuccess:(id)arg1;
- (void)addMemberFailed:(id)arg1;
- (void)addMemberSuccess:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

