//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSURLSessionDelegate.h"

@class NSString, NSURLSession;

@interface HBURLSessionManager : NSObject <NSURLSessionDelegate>
{
    NSURLSession *_session;
}

+ (id)defaultManager;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSURLSession *session; // @synthesize session=_session;
- (void)URLSession:(id)arg1 didReceiveChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

