//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface HNCConstants : NSObject
{
    _Bool _inFullFunc;
    NSString *_sMBServerProtocol;
    NSString *_sMBServer;
    NSString *_sBackupServer;
    NSString *_sServiceServer;
    NSString *_sURLSysjustCookie;
    NSString *_sURLSysjustInternationalIndex;
    NSString *_sURLSysjustFund;
    NSString *_sURLSysjustTWStock;
    NSString *_sRCError;
    NSString *_sRCNoData;
    NSString *_sRCSuccess;
    NSString *_sLoginTypeForAlertMsg;
    NSMutableDictionary *_mtdSession;
    NSString *_gaCode;
}

+ (id)getVIDWithTxSN:(id)arg1 withUDID:(id)arg2;
@property(nonatomic) _Bool inFullFunc; // @synthesize inFullFunc=_inFullFunc;
@property(retain, nonatomic) NSString *gaCode; // @synthesize gaCode=_gaCode;
@property(retain, nonatomic) NSMutableDictionary *mtdSession; // @synthesize mtdSession=_mtdSession;
@property(retain, nonatomic) NSString *sLoginTypeForAlertMsg; // @synthesize sLoginTypeForAlertMsg=_sLoginTypeForAlertMsg;
@property(retain, nonatomic) NSString *sRCSuccess; // @synthesize sRCSuccess=_sRCSuccess;
@property(retain, nonatomic) NSString *sRCNoData; // @synthesize sRCNoData=_sRCNoData;
@property(retain, nonatomic) NSString *sRCError; // @synthesize sRCError=_sRCError;
@property(retain, nonatomic) NSString *sURLSysjustTWStock; // @synthesize sURLSysjustTWStock=_sURLSysjustTWStock;
@property(retain, nonatomic) NSString *sURLSysjustFund; // @synthesize sURLSysjustFund=_sURLSysjustFund;
@property(retain, nonatomic) NSString *sURLSysjustInternationalIndex; // @synthesize sURLSysjustInternationalIndex=_sURLSysjustInternationalIndex;
@property(retain, nonatomic) NSString *sURLSysjustCookie; // @synthesize sURLSysjustCookie=_sURLSysjustCookie;
@property(retain, nonatomic) NSString *sServiceServer; // @synthesize sServiceServer=_sServiceServer;
@property(retain, nonatomic) NSString *sBackupServer; // @synthesize sBackupServer=_sBackupServer;
@property(retain, nonatomic) NSString *sMBServer; // @synthesize sMBServer=_sMBServer;
@property(retain, nonatomic) NSString *sMBServerProtocol; // @synthesize sMBServerProtocol=_sMBServerProtocol;
- (void)showDefaultAlertMessageView:(id)arg1 withMessage:(id)arg2 withDelegate:(id)arg3 withTag:(long long)arg4;
- (void)showDefaultAlertMessageView:(id)arg1 withMessage:(id)arg2;
- (_Bool)isiBankingLogin;
- (id)getMBServerURL:(id)arg1;
- (void)dealloc;
- (id)init;

@end

