//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIWindow.h"

@class UIPanGestureRecognizer, UITapGestureRecognizer;

@interface HNCFloatingIconWindow : UIWindow
{
    UIPanGestureRecognizer *_panGestureRecognizer;
    UITapGestureRecognizer *_tapGestureRecognizer;
    struct CGRect _originalFrame;
    struct CGRect _moveScopeFrame;
}

@property(nonatomic) struct CGRect moveScopeFrame; // @synthesize moveScopeFrame=_moveScopeFrame;
@property(nonatomic) struct CGRect originalFrame; // @synthesize originalFrame=_originalFrame;
@property(retain, nonatomic) UITapGestureRecognizer *tapGestureRecognizer; // @synthesize tapGestureRecognizer=_tapGestureRecognizer;
@property(retain, nonatomic) UIPanGestureRecognizer *panGestureRecognizer; // @synthesize panGestureRecognizer=_panGestureRecognizer;
- (void)floatingIconWindowTapGestureEvent:(id)arg1;
- (void)floatingIconWindowPanGestureEvent:(id)arg1;
- (void)floatingIconWindowRemoveGestureRecognizer;
- (void)floatingIconWindowAddGestureRecognizer;
- (void)changeWithFrame:(struct CGRect)arg1 isChangeOriginalFrame:(_Bool)arg2;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 moveScopeFrame:(struct CGRect)arg2 image:(id)arg3 windowLevel:(double)arg4;

@end

