//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface HNCTools : NSObject
{
}

+ (id)initDate:(id)arg1;
+ (id)countNumAndChangeformat:(id)arg1;
+ (id)nullToString:(id)arg1;
+ (id)getBonusLabelText:(id)arg1 atIndex:(long long)arg2;
+ (void)checkAESKey;
+ (id)readUserDefaultWithKey:(id)arg1;
+ (void)saveUserDefaultWithKey:(id)arg1 withValue:(id)arg2;
+ (id)getBundleProperty:(id)arg1;
+ (id)machineName;
+ (_Bool)isIntegrityApp;
+ (_Bool)isMyDeviceIDFromUserDefault;
+ (void);

@end

