//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "EWalletUtilsDelegate.h"
#import "INUIAddVoiceShortcutViewControllerDelegate.h"
#import "UIAlertViewDelegate.h"
#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"
#import "WebServiceObjectDelegate.h"

@class MMBPickerView, NSString, UIPickerView, WebServiceObject;

@interface HNCViewController : UIViewController <INUIAddVoiceShortcutViewControllerDelegate, EWalletUtilsDelegate, UIAlertViewDelegate, UIPickerViewDataSource, UIPickerViewDelegate, WebServiceObjectDelegate>
{
    WebServiceObject *_wsObject;
    UIPickerView *_optionsPickerView;
    MMBPickerView *_optionsMMBPickerView;
}

@property(retain, nonatomic) MMBPickerView *optionsMMBPickerView; // @synthesize optionsMMBPickerView=_optionsMMBPickerView;
@property(retain, nonatomic) UIPickerView *optionsPickerView; // @synthesize optionsPickerView=_optionsPickerView;
@property(retain, nonatomic) WebServiceObject *wsObject; // @synthesize wsObject=_wsObject;
- (void)showWillOpenBrowserAlert:(id)arg1;
- (void)WebServiceObject:(id)arg1 didCompleteGenAuthenticateParamWithHeader:(id)arg2 withGenAuthenticateParamResponseBody:(id)arg3;
- (void)addVoiceShortcutViewControllerDidCancel:(id)arg1;
- (void)addVoiceShortcutViewController:(id)arg1 didFinishWithVoiceShortcut:(id)arg2 error:(id)arg3;
- (_Bool)checkCurrentLoginTypeWithFuncLoginType:(id)arg1;
- (void)loginVerificationWithLoginType:(int)arg1 guideWFID1:(id)arg2 guideWFID2:(id)arg3 guideWFID3:(id)arg4 forceGuideMobileBankWFID:(id)arg5 isOpenAIRobot:(id)arg6 funcTXID:(id)arg7 param1:(id)arg8;
- (void)guideViewControllerWithWFID1:(id)arg1 guideWFID2:(id)arg2 guideWFID3:(id)arg3 forceGuideMobileBankWFID:(id)arg4 isOpenAIRobot:(id)arg5 funcTXID:(id)arg6 param1:(id)arg7;
- (void)delayShowAIRobotInstructionView:(id)arg1;
- (void)mmbPickerViewBtnCancelClickEvent:(id)arg1;
- (void)mmbPickerViewBtnDoneClickEvent:(id)arg1;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)hiddenOptionRowsMMBPickView;
- (void)showOptionRowsMMBPickViewWithSelectText:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)logoutButtonClickEvent:(id)arg1;
- (void)homeButtonClickEvent:(id)arg1;
- (void)backButtonClickEvent:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

