//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCViewController.h"

#import "NSURLConnectionDataDelegate.h"
#import "NSURLConnectionDelegate.h"
#import "WKNavigationDelegate.h"
#import "WKScriptMessageHandler.h"
#import "WKUIDelegate.h"

@class NSLayoutConstraint, NSMutableArray, NSMutableData, NSString, UIActivityIndicatorView, UIToolbar, UIView, WKUserContentController, WKWebView;

@interface HNCWebKitViewController : HNCViewController <NSURLConnectionDataDelegate, NSURLConnectionDelegate, WKUIDelegate, WKNavigationDelegate, WKScriptMessageHandler>
{
    _Bool _isHiddenNavigationBar;
    _Bool _isHiddenToolbarBrowser;
    _Bool _isURLConnectionRequest;
    _Bool _isPost;
    _Bool _isHiddenAIRobotFloatingIconWindow;
    WKWebView *_commonWebKitView;
    UIView *_commonWebKitContainerView;
    UIToolbar *_toolbarBrowser;
    NSLayoutConstraint *_toolbarBrowserHeightConstraint;
    NSString *_requestURLStr;
    NSString *_requestBodyStr;
    NSMutableArray *_addScriptMessageNameArray;
    UIView *_loadingView;
    UIActivityIndicatorView *_activityIndicatorView;
    WKUserContentController *_userContentController;
    NSMutableData *_urlConnectionReceiveData;
    long long _urlConnectionResponseStatusCode;
}

@property(nonatomic) long long urlConnectionResponseStatusCode; // @synthesize urlConnectionResponseStatusCode=_urlConnectionResponseStatusCode;
@property(retain, nonatomic) NSMutableData *urlConnectionReceiveData; // @synthesize urlConnectionReceiveData=_urlConnectionReceiveData;
@property(retain, nonatomic) WKUserContentController *userContentController; // @synthesize userContentController=_userContentController;
@property(retain, nonatomic) UIActivityIndicatorView *activityIndicatorView; // @synthesize activityIndicatorView=_activityIndicatorView;
@property(retain, nonatomic) UIView *loadingView; // @synthesize loadingView=_loadingView;
@property(nonatomic) _Bool isHiddenAIRobotFloatingIconWindow; // @synthesize isHiddenAIRobotFloatingIconWindow=_isHiddenAIRobotFloatingIconWindow;
@property(nonatomic) _Bool isPost; // @synthesize isPost=_isPost;
@property(nonatomic) _Bool isURLConnectionRequest; // @synthesize isURLConnectionRequest=_isURLConnectionRequest;
@property(nonatomic) _Bool isHiddenToolbarBrowser; // @synthesize isHiddenToolbarBrowser=_isHiddenToolbarBrowser;
@property(nonatomic) _Bool isHiddenNavigationBar; // @synthesize isHiddenNavigationBar=_isHiddenNavigationBar;
@property(retain, nonatomic) NSMutableArray *addScriptMessageNameArray; // @synthesize addScriptMessageNameArray=_addScriptMessageNameArray;
@property(retain, nonatomic) NSString *requestBodyStr; // @synthesize requestBodyStr=_requestBodyStr;
@property(retain, nonatomic) NSString *requestURLStr; // @synthesize requestURLStr=_requestURLStr;
@property(retain, nonatomic) NSLayoutConstraint *toolbarBrowserHeightConstraint; // @synthesize toolbarBrowserHeightConstraint=_toolbarBrowserHeightConstraint;
@property(retain, nonatomic) UIToolbar *toolbarBrowser; // @synthesize toolbarBrowser=_toolbarBrowser;
@property(retain, nonatomic) UIView *commonWebKitContainerView; // @synthesize commonWebKitContainerView=_commonWebKitContainerView;
@property(retain, nonatomic) WKWebView *commonWebKitView; // @synthesize commonWebKitView=_commonWebKitView;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)showConnectionErrorAlertViewWithError:(id)arg1;
- (void)userContentController:(id)arg1 didReceiveScriptMessage:(id)arg2;
- (void)webViewWebContentProcessDidTerminate:(id)arg1;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)delayUrlConnectionFinishLoadHTML:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)connection:(id)arg1 didReceiveResponse:(id)arg2;
- (void)settingWebKitViewStoreCookieWithName:(id)arg1 cookieValue:(id)arg2 cookieDomain:(id)arg3 cookiePath:(id)arg4;
- (void)doRequest;
- (void)webKitViewLoadRequest;
- (void)stopLoadingView;
- (void)startLoadingView;
- (void)toolbarBrowserClickEvent:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

