//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL;

@interface HNFHCServiceDataDetail : NSObject
{
    NSString *_serviceName;
    NSURL *_url;
    long long _subsidiary;
}

@property(nonatomic) long long subsidiary; // @synthesize subsidiary=_subsidiary;
@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
@property(retain, nonatomic) NSString *serviceName; // @synthesize serviceName=_serviceName;
- (id)initWithServiceName:(id)arg1 destinationURL:(id)arg2 subsidiary:(long long)arg3;

@end

