//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface IntumitRobotEntity : NSObject
{
    NSString *_question;
    NSString *_channel;
    NSString *_command;
    NSString *_gps;
    NSString *_userType;
    NSString *_category;
    NSString *_language;
    NSString *_appOperation;
    NSString *_personalId;
    NSString *_needReset;
    NSString *_loginId;
    NSDictionary *_other;
}

@property(retain, nonatomic) NSDictionary *other; // @synthesize other=_other;
@property(retain, nonatomic) NSString *loginId; // @synthesize loginId=_loginId;
@property(retain, nonatomic) NSString *needReset; // @synthesize needReset=_needReset;
@property(retain, nonatomic) NSString *personalId; // @synthesize personalId=_personalId;
@property(retain, nonatomic) NSString *appOperation; // @synthesize appOperation=_appOperation;
@property(retain, nonatomic) NSString *language; // @synthesize language=_language;
@property(retain, nonatomic) NSString *category; // @synthesize category=_category;
@property(retain, nonatomic) NSString *userType; // @synthesize userType=_userType;
@property(retain, nonatomic) NSString *gps; // @synthesize gps=_gps;
@property(retain, nonatomic) NSString *command; // @synthesize command=_command;
@property(retain, nonatomic) NSString *channel; // @synthesize channel=_channel;
@property(retain, nonatomic) NSString *question; // @synthesize question=_question;

@end

