//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class AVCaptureDeviceInput, AVCaptureVideoDataOutput, NSString;

@interface IOSCapture : UIView <AVCaptureVideoDataOutputSampleBufferDelegate>
{
    AVCaptureDeviceInput *input;
    AVCaptureVideoDataOutput *output;
    struct _opaque_pthread_mutex_t {
        long long __sig;
        char __opaque[56];
    } mutex;
    struct msgb *msframe;
    int frame_ind;
    float fps;
    float start_time;
    int frame_count;
    struct MSVideoSize mOutputVideoSize;
    struct MSVideoSize mCameraVideoSize;
    unsigned char mDownScalingRequired;
    int mDeviceOrientation;
    struct _MSAverageFPS averageFps;
    char fps_context[64];
    const char *deviceId;
    struct _msgb_allocator {
        struct _queue {
            struct msgb _field1;
            int _field2;
        } _field1;
    } *bufAllocator;
    UIView *parentView;
}

+ (Class)layerClass;
@property(retain, nonatomic) UIView *parentView; // @synthesize parentView;
- (void)setFps:(float)arg1;
- (struct MSVideoSize *)getSize;
- (void)setSize:(struct MSVideoSize)arg1;
- (void)configureSize:(struct MSVideoSize)arg1 withSession:(id)arg2;
- (int)stop;
- (int)start;
- (void)dealloc;
- (void)openDevice:(const char *)arg1;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)computeCroppingOffsets:(int *)arg1 cbcr_offset:(int *)arg2;
- (void)initIOSCapture;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

