//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class EAGLContext, NSRecursiveLock;

@interface IOSDisplay : UIView
{
    struct opengles_display *display_helper;
    NSRecursiveLock *lock;
    EAGLContext *context;
    unsigned int defaultFrameBuffer;
    unsigned int colorRenderBuffer;
    id displayLink;
    _Bool animating;
    struct CGRect prevBounds;
    int deviceRotation;
    int displayRotation;
    UIView *parentView;
}

+ (Class)layerClass;
@property int displayRotation; // @synthesize displayRotation;
@property int deviceRotation; // @synthesize deviceRotation;
@property(retain, nonatomic) UIView *parentView; // @synthesize parentView;
- (void)dealloc;
- (void)drawView;
- (void)initOpenGL;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)initIOSDisplay;

@end

