//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilWeakHashMap_Entry_Type.h"

@interface JavaUtilWeakHashMap_$1_$1 : NSObject <JavaUtilWeakHashMap_Entry_Type>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)init;
- (id)getWithJavaUtilMap_Entry:(id)arg1;

@end

