//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilEnumeration.h"

@class NSString;

@interface JavaUtilStringTokenizer : NSObject <JavaUtilEnumeration>
{
    NSString *string_;
    NSString *delimiters_;
    _Bool returnDelimiters_;
    int position_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)nextTokenWithNSString:(id)arg1;
- (id)nextToken;
- (id)nextElement;
- (_Bool)hasMoreTokens;
- (_Bool)hasMoreElements;
- (int)countTokens;
- (id)initWithNSString:(id)arg1 withNSString:(id)arg2 withBoolean:(_Bool)arg3;
- (id)initJavaUtilStringTokenizerWithNSString:(id)arg1 withNSString:(id)arg2 withBoolean:(_Bool)arg3;
- (id)initWithNSString:(id)arg1 withNSString:(id)arg2;
- (id)initWithNSString:(id)arg1;

@end

