//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaLangThread_UncaughtExceptionHandler.h"

@class IOSObjectArray, NSString;

@interface JavaLangThreadGroup : NSObject <JavaLangThread_UncaughtExceptionHandler>
{
    JavaLangThreadGroup *parent_;
    int numThreads_;
    int numGroups_;
    NSString *name_;
    int maxPriority_;
    IOSObjectArray *childrenThreads_;
    IOSObjectArray *childrenGroups_;
    id childrenGroupsLock_;
    id childrenThreadsLock_;
    _Bool isDestroyed__;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)uncaughtExceptionWithJavaLangThread:(id)arg1 withJavaLangThrowable:(id)arg2;
- (id)description;
- (void)setParentWithJavaLangThreadGroup:(id)arg1;
- (void)setMaxPriorityWithInt:(int)arg1;
- (void)removeWithJavaLangThreadGroup:(id)arg1;
- (void)removeWithJavaLangThread:(id)arg1;
- (_Bool)parentOfWithJavaLangThreadGroup:(id)arg1;
- (void)listWithInt:(int)arg1;
- (void)list;
- (_Bool)isDestroyed;
- (id)getParent;
- (id)getName;
- (int)getMaxPriority;
- (int)enumerateGenericWithNSObjectArray:(id)arg1 withBoolean:(_Bool)arg2 withInt:(int)arg3 withBoolean:(_Bool)arg4;
- (int)enumerateWithJavaLangThreadGroupArray:(id)arg1 withBoolean:(_Bool)arg2;
- (int)enumerateWithJavaLangThreadGroupArray:(id)arg1;
- (int)enumerateWithJavaLangThreadArray:(id)arg1 withBoolean:(_Bool)arg2;
- (int)enumerateWithJavaLangThreadArray:(id)arg1;
- (void)destroy;
- (void)checkAccess;
- (void)addWithJavaLangThreadGroup:(id)arg1;
- (void)addWithJavaLangThread:(id)arg1;
- (int)activeGroupCount;
- (int)activeCount;
- (id)initWithJavaLangThreadGroup:(id)arg1;
- (id)initWithJavaLangThreadGroup:(id)arg1 withNSString:(id)arg2;
- (id)initJavaLangThreadGroupWithJavaLangThreadGroup:(id)arg1 withNSString:(id)arg2;
- (id)initWithNSString:(id)arg1;
- (id)init;

@end

