//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilIterator.h"

@class JavaUtilCollections_SingletonMap_$1;

@interface JavaUtilCollections_SingletonMap_$1_$1 : NSObject <JavaUtilIterator>
{
    _Bool hasNext__;
    JavaUtilCollections_SingletonMap_$1 *this$0_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)initWithJavaUtilCollections_SingletonMap_$1:(id)arg1;
- (void)remove;
- (id)next;
- (_Bool)hasNext;

@end

