//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaNioChannelsSpiAbstractSelectableChannel.h"

#import "JavaNioChannelsGatheringByteChannel.h"
#import "JavaNioChannelsWritableByteChannel.h"

@interface JavaNioChannelsPipe_SinkChannel : JavaNioChannelsSpiAbstractSelectableChannel <JavaNioChannelsWritableByteChannel, JavaNioChannelsGatheringByteChannel>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (int)validOps;
- (id)initWithJavaNioChannelsSpiSelectorProvider:(id)arg1;

@end

