//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class IOSByteArray, JavaNioCharsetCharset, JavaNioCharsetCharsetDecoder, JavaNioCharsetCodingErrorAction;

@interface JavaNioCharsetCharsetEncoder : NSObject
{
    JavaNioCharsetCharset *cs_;
    float averageBytesPerChar__;
    float maxBytesPerChar__;
    IOSByteArray *replacementBytes_;
    int status_;
    _Bool finished_;
    JavaNioCharsetCodingErrorAction *malformedInputAction__;
    JavaNioCharsetCodingErrorAction *unmappableCharacterAction__;
    JavaNioCharsetCharsetDecoder *decoder_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)unmappableCharacterAction;
- (id)reset;
- (id)replaceWithWithByteArray:(id)arg1;
- (id)replacement;
- (id)onUnmappableCharacterWithJavaNioCharsetCodingErrorAction:(id)arg1;
- (id)onMalformedInputWithJavaNioCharsetCodingErrorAction:(id)arg1;
- (float)maxBytesPerChar;
- (id)malformedInputAction;
- (id)flushWithJavaNioByteBuffer:(id)arg1;
- (id)encodeLoopWithJavaNioCharBuffer:(id)arg1 withJavaNioByteBuffer:(id)arg2;
- (id)encodeWithJavaNioCharBuffer:(id)arg1 withJavaNioByteBuffer:(id)arg2 withBoolean:(_Bool)arg3;
- (id)encodeWithJavaNioCharBuffer:(id)arg1;
- (id)charset;
- (_Bool)canEncodeWithJavaLangCharSequence:(id)arg1;
- (_Bool)implCanEncodeWithJavaNioCharBuffer:(id)arg1;
- (_Bool)canEncodeWithChar:(unsigned short)arg1;
- (float)averageBytesPerChar;
- (id)initWithJavaNioCharsetCharset:(id)arg1 withFloat:(float)arg2 withFloat:(float)arg3 withByteArray:(id)arg4;
- (id)initJavaNioCharsetCharsetEncoderWithJavaNioCharsetCharset:(id)arg1 withFloat:(float)arg2 withFloat:(float)arg3 withByteArray:(id)arg4;
- (id)initWithJavaNioCharsetCharset:(id)arg1 withFloat:(float)arg2 withFloat:(float)arg3;

@end

