//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoCloseable.h"
#import "JavaIoFlushable.h"

@interface JavaIoOutputStream : NSObject <JavaIoCloseable, JavaIoFlushable>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (_Bool)checkError;
- (void)writeWithInt:(int)arg1;
- (void)writeWithByteArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (void)writeWithByteArray:(id)arg1;
- (void)flush;
- (void)close;
- (id)init;

@end

