//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaIoFilterOutputStream.h"

@class IOSByteArray;

@interface JavaIoBufferedOutputStream : JavaIoFilterOutputStream
{
    IOSByteArray *buf_;
    int count_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)flushInternal;
- (void)writeWithInt:(int)arg1;
- (void)close;
- (void)writeWithByteArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (void)checkNotClosed;
- (void)flush;
- (id)initWithJavaIoOutputStream:(id)arg1 withInt:(int)arg2;
- (id)initJavaIoBufferedOutputStreamWithJavaIoOutputStream:(id)arg1 withInt:(int)arg2;
- (id)initWithJavaIoOutputStream:(id)arg1;

@end

