//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaLangReflectTypeVariable.h"

@class NSString;

@interface JavaLangReflectTypeVariableImpl : NSObject <JavaLangReflectTypeVariable>
{
    NSString *name_;
}

+ (id)typeVariableWithName:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)getName;
- (id)getGenericDeclaration;
- (id)getBounds;
- (id)initWithName:(id)arg1;

@end

