//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilCollections_SynchronizedCollection.h"

#import "JavaUtilSet.h"

@interface JavaUtilCollections_SynchronizedSet : JavaUtilCollections_SynchronizedCollection <JavaUtilSet>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)writeObjectWithJavaIoObjectOutputStream:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithJavaUtilSet:(id)arg1 withId:(id)arg2;
- (id)initWithJavaUtilSet:(id)arg1;

@end

