//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JavaLangStackTraceElement : NSObject
{
    NSString *className__;
    NSString *methodName_;
    NSString *fileName_;
    int lineNumber_;
    long long address_;
    NSString *hexAddress_;
    NSString *offset_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)initializeFromAddress;
- (id)description;
- (id)initWithLong:(long long)arg1;
- (id)initWithNSString:(id)arg1 withNSString:(id)arg2 withNSString:(id)arg3 withInt:(int)arg4;
- (id)initJavaLangStackTraceElementWithNSString:(id)arg1 withNSString:(id)arg2 withNSString:(id)arg3 withInt:(int)arg4;
- (int)getLineNumber;
- (id)getFileName;
- (id)getMethodName;
- (id)getClassName;

@end

