//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractSet.h"

#import "JavaUtilNavigableSet.h"

@class JavaUtilTreeMap_BoundedMap;

@interface JavaUtilTreeMap_BoundedMap_BoundedKeySet : JavaUtilAbstractSet <JavaUtilNavigableSet>
{
    JavaUtilTreeMap_BoundedMap *this$0_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)dealloc;
- (id)initWithJavaUtilTreeMap_BoundedMap:(id)arg1;
- (id)descendingSet;
- (id)tailSetWithId:(id)arg1;
- (id)tailSetWithId:(id)arg1 withBoolean:(_Bool)arg2;
- (id)headSetWithId:(id)arg1;
- (id)headSetWithId:(id)arg1 withBoolean:(_Bool)arg2;
- (id)subSetWithId:(id)arg1 withId:(id)arg2;
- (id)subSetWithId:(id)arg1 withBoolean:(_Bool)arg2 withId:(id)arg3 withBoolean:(_Bool)arg4;
- (id)comparator;
- (id)higherWithId:(id)arg1;
- (id)ceilingWithId:(id)arg1;
- (id)floorWithId:(id)arg1;
- (id)lowerWithId:(id)arg1;
- (id)pollLast;
- (id)last;
- (id)pollFirst;
- (id)first;
- (_Bool)removeWithId:(id)arg1;
- (_Bool)containsWithId:(id)arg1;
- (id)descendingIterator;
- (id)iterator;
- (_Bool)isEmpty;
- (int)size;

@end

