//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JavaIoFileDescriptor : NSObject
{
    int descriptor_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (id)description;
- (void)setInt$WithInt:(int)arg1;
- (int)getInt$;
- (_Bool)valid;
- (void)sync;
- (id)init;

@end

