//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaNioChannelsSpiAbstractSelectableChannel.h"

#import "JavaNioChannelsReadableByteChannel.h"
#import "JavaNioChannelsScatteringByteChannel.h"

@interface JavaNioChannelsPipe_SourceChannel : JavaNioChannelsSpiAbstractSelectableChannel <JavaNioChannelsReadableByteChannel, JavaNioChannelsScatteringByteChannel>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (int)validOps;
- (id)initWithJavaNioChannelsSpiSelectorProvider:(id)arg1;

@end

