//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface JavaLangStringToReal_StringExponentPair : NSObject
{
    NSString *s_;
    long long e_;
    _Bool negative_;
    _Bool infinity_;
    _Bool zero_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)init;
- (float)specialValue;

@end

