//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaNioChannelsSelectableChannel.h"

@class JavaNioChannelsSpiSelectorProvider;

@interface JavaNioChannelsSpiAbstractSelectableChannel : JavaNioChannelsSelectableChannel
{
    _Bool isBlocking__;
    JavaNioChannelsSpiSelectorProvider *provider__;
    id <JavaUtilList> keyList_;
    id blockingLock__;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (_Bool)containsValidKeys;
- (void)deregisterWithJavaNioChannelsSelectionKey:(id)arg1;
- (void)implConfigureBlockingWithBoolean:(_Bool)arg1;
- (id)configureBlockingWithBoolean:(_Bool)arg1;
- (id)blockingLock;
- (_Bool)isBlocking;
- (void)implCloseSelectableChannel;
- (void)implCloseChannel;
- (id)register__WithJavaNioChannelsSelector:(id)arg1 withInt:(int)arg2 withId:(id)arg3;
- (id)keyForWithJavaNioChannelsSelector:(id)arg1;
- (_Bool)isRegistered;
- (id)provider;
- (id)initWithJavaNioChannelsSpiSelectorProvider:(id)arg1;

@end

