//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilIterator.h"

@class IOSClass;

@interface JavaUtilCollections_CheckedMap_CheckedEntrySet_CheckedEntryIterator : NSObject <JavaUtilIterator>
{
    id <JavaUtilIterator> i_;
    IOSClass *valueType_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)next;
- (void)remove;
- (_Bool)hasNext;
- (id)initWithJavaUtilIterator:(id)arg1 withIOSClass:(id)arg2;

@end

