//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JavaUtilHashMap, JavaUtilHashMap_Entry;

@interface JavaUtilHashMap_AbstractMapIterator : NSObject
{
    int position_;
    int expectedModCount_;
    JavaUtilHashMap_Entry *futureEntry_;
    JavaUtilHashMap_Entry *currentEntry_;
    JavaUtilHashMap_Entry *prevEntry_;
    JavaUtilHashMap *associatedMap_;
}

@property(retain, nonatomic) JavaUtilHashMap *associatedMap; // @synthesize associatedMap=associatedMap_;
@property(nonatomic) JavaUtilHashMap_Entry *prevEntry; // @synthesize prevEntry=prevEntry_;
@property(nonatomic) JavaUtilHashMap_Entry *currentEntry; // @synthesize currentEntry=currentEntry_;
@property(nonatomic) JavaUtilHashMap_Entry *futureEntry; // @synthesize futureEntry=futureEntry_;
@property(nonatomic) int expectedModCount; // @synthesize expectedModCount=expectedModCount_;
@property(nonatomic) int position; // @synthesize position=position_;
- (void)dealloc;
- (void)remove;
- (void)makeNext;
- (void)checkConcurrentMod;
- (_Bool)hasNext;
- (id)initWithJavaUtilHashMap:(id)arg1;

@end

