//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilMapEntry.h"

@interface JavaUtilHashtable_Entry : JavaUtilMapEntry
{
    JavaUtilHashtable_Entry *next_;
    int hashcode_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)description;
- (_Bool)equalsKeyWithId:(id)arg1 withInt:(int)arg2;
- (int)getKeyHash;
- (id)setValueWithId:(id)arg1;
- (id)clone;
- (id)initWithId:(id)arg1 withId:(id)arg2;

@end

