//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilCollections_CheckedList.h"

#import "JavaUtilRandomAccess.h"

@interface JavaUtilCollections_CheckedRandomAccessList : JavaUtilCollections_CheckedList <JavaUtilRandomAccess>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)initWithJavaUtilList:(id)arg1 withIOSClass:(id)arg2;

@end

