//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractSet.h"

#import "JavaIoSerializable.h"
#import "JavaUtilNavigableSet.h"
#import "NSCopying.h"

@interface JavaUtilTreeSet : JavaUtilAbstractSet <JavaUtilNavigableSet, NSCopying, JavaIoSerializable>
{
    id <JavaUtilNavigableMap> backingMap_;
    id <JavaUtilNavigableSet> descendingSet__;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)readObjectWithJavaIoObjectInputStream:(id)arg1;
- (void)writeObjectWithJavaIoObjectOutputStream:(id)arg1;
- (id)tailSetWithId:(id)arg1;
- (id)headSetWithId:(id)arg1;
- (id)subSetWithId:(id)arg1 withId:(id)arg2;
- (id)tailSetWithId:(id)arg1 withBoolean:(_Bool)arg2;
- (id)headSetWithId:(id)arg1 withBoolean:(_Bool)arg2;
- (id)subSetWithId:(id)arg1 withBoolean:(_Bool)arg2 withId:(id)arg3 withBoolean:(_Bool)arg4;
- (id)descendingSet;
- (id)floorWithId:(id)arg1;
- (id)ceilingWithId:(id)arg1;
- (id)lowerWithId:(id)arg1;
- (id)higherWithId:(id)arg1;
- (id)pollLast;
- (id)pollFirst;
- (id)last;
- (id)first;
- (int)size;
- (_Bool)removeWithId:(id)arg1;
- (id)descendingIterator;
- (id)iterator;
- (_Bool)isEmpty;
- (_Bool)containsWithId:(id)arg1;
- (id)comparator;
- (id)clone;
- (void)clear;
- (_Bool)addAllWithJavaUtilCollection:(id)arg1;
- (_Bool)addWithId:(id)arg1;
- (id)initWithJavaUtilSortedSet:(id)arg1;
- (id)initWithJavaUtilComparator:(id)arg1;
- (id)initJavaUtilTreeSetWithJavaUtilComparator:(id)arg1;
- (id)initWithJavaUtilCollection:(id)arg1;
- (id)init;
- (id)initJavaUtilTreeSet;
- (id)initWithJavaUtilNavigableMap:(id)arg1;

@end

