//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractList_SubAbstractList.h"

#import "JavaUtilRandomAccess.h"

@interface JavaUtilAbstractList_SubAbstractListRandomAccess : JavaUtilAbstractList_SubAbstractList <JavaUtilRandomAccess>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)initWithJavaUtilAbstractList:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;

@end

