//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaIoOutputStream.h"

@class DalvikSystemCloseGuard, JavaIoFileDescriptor, JavaNioChannelsFileChannel;

@interface JavaIoFileOutputStream : JavaIoOutputStream
{
    JavaIoFileDescriptor *fd_;
    _Bool shouldClose_;
    JavaNioChannelsFileChannel *channel_;
    int mode_;
    DalvikSystemCloseGuard *guard_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)writeWithInt:(int)arg1;
- (void)writeWithByteArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (id)getFD;
- (id)getChannel;
- (void)dealloc;
- (void)close;
- (id)initWithNSString:(id)arg1 withBoolean:(_Bool)arg2;
- (id)initJavaIoFileOutputStreamWithNSString:(id)arg1 withBoolean:(_Bool)arg2;
- (id)initWithNSString:(id)arg1;
- (id)initWithJavaIoFileDescriptor:(id)arg1;
- (id)initWithJavaIoFile:(id)arg1 withBoolean:(_Bool)arg2;
- (id)initJavaIoFileOutputStreamWithJavaIoFile:(id)arg1 withBoolean:(_Bool)arg2;
- (id)initWithJavaIoFile:(id)arg1;

@end

