//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaIoReader.h"

@class JavaIoInputStream, JavaNioByteBuffer, JavaNioCharsetCharsetDecoder;

@interface JavaIoInputStreamReader : JavaIoReader
{
    JavaIoInputStream *in_;
    _Bool endOfInput_;
    JavaNioCharsetCharsetDecoder *decoder_;
    JavaNioByteBuffer *bytes_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (_Bool)ready;
- (_Bool)isOpen;
- (int)readWithCharArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (int)read;
- (id)getEncoding;
- (void)close;
- (id)initWithJavaIoInputStream:(id)arg1 withJavaNioCharsetCharset:(id)arg2;
- (id)initJavaIoInputStreamReaderWithJavaIoInputStream:(id)arg1 withJavaNioCharsetCharset:(id)arg2;
- (id)initWithJavaIoInputStream:(id)arg1 withJavaNioCharsetCharsetDecoder:(id)arg2;
- (id)initWithJavaIoInputStream:(id)arg1 withNSString:(id)arg2;
- (id)initWithJavaIoInputStream:(id)arg1;

@end

