//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractCollection.h"

#import "JavaUtilQueue.h"

@interface JavaUtilAbstractQueue : JavaUtilAbstractCollection <JavaUtilQueue>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)clear;
- (id)element;
- (id)remove;
- (_Bool)addAllWithJavaUtilCollection:(id)arg1;
- (_Bool)addWithId:(id)arg1;
- (id)init;

@end

