//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoSerializable.h"

@interface JavaUtilRandom : NSObject <JavaIoSerializable>
{
    _Bool haveNextNextGaussian_;
    long long seed_;
    double nextNextGaussian_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (double)iOS_logWithDouble:(double)arg1;
+ (double)iOS_sqrtWithDouble:(double)arg1;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)setSeedWithLong:(long long)arg1;
- (long long)nextLong;
- (int)nextIntWithInt:(int)arg1;
- (int)nextInt;
- (double)nextGaussian;
- (float)nextFloat;
- (double)nextDouble;
- (void)nextBytesWithByteArray:(id)arg1;
- (_Bool)nextBoolean;
- (int)nextWithInt:(int)arg1;
- (id)initWithLong:(long long)arg1;
- (id)init;

@end

