//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilEnumeration.h"

@interface JavaUtilCollections_$3 : NSObject <JavaUtilEnumeration>
{
    id <JavaUtilIterator> it_;
    id <JavaUtilCollection> val$c_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)initWithJavaUtilCollection:(id)arg1;
- (id)nextElement;
- (_Bool)hasMoreElements;

@end

