//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilListIterator.h"

@class JavaUtilAbstractList_SubAbstractList;

@interface JavaUtilAbstractList_SubAbstractList_SubAbstractListIterator : NSObject <JavaUtilListIterator>
{
    JavaUtilAbstractList_SubAbstractList *subList_;
    id <JavaUtilListIterator> iterator_;
    int start_;
    int end_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)setWithId:(id)arg1;
- (void)remove;
- (int)previousIndex;
- (id)previous;
- (int)nextIndex;
- (id)next;
- (_Bool)hasPrevious;
- (_Bool)hasNext;
- (void)addWithId:(id)arg1;
- (id)initWithJavaUtilListIterator:(id)arg1 withJavaUtilAbstractList_SubAbstractList:(id)arg2 withInt:(int)arg3 withInt:(int)arg4;

@end

