//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaNioChannelsChannel.h"
#import "JavaNioChannelsInterruptibleChannel.h"

@class JavaNioChannelsSpiAbstractInterruptibleChannel_ChannelCloser;

@interface JavaNioChannelsSpiAbstractInterruptibleChannel : NSObject <JavaNioChannelsChannel, JavaNioChannelsInterruptibleChannel>
{
    _Bool interrupted_;
    _Bool closed_;
    JavaNioChannelsSpiAbstractInterruptibleChannel_ChannelCloser *interruptAndCloseRunnable_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)implCloseChannel;
- (void)endWithBoolean:(_Bool)arg1;
- (void)begin;
- (void)close;
- (_Bool)isOpen;
- (id)init;

@end

