//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractList.h"

#import "JavaIoSerializable.h"
#import "JavaUtilRandomAccess.h"
#import "NSCopying.h"

@class IOSObjectArray;

@interface JavaUtilArrayList : JavaUtilAbstractList <NSCopying, JavaIoSerializable, JavaUtilRandomAccess>
{
    int size__;
    IOSObjectArray *array_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)throwIndexOutOfBoundsExceptionWithInt:(int)arg1 withInt:(int)arg2;
+ (int)newCapacityWithInt:(int)arg1;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)readObjectWithJavaIoObjectInputStream:(id)arg1;
- (void)writeObjectWithJavaIoObjectOutputStream:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)iterator;
- (void)trimToSize;
- (id)toArrayWithNSObjectArray:(id)arg1;
- (id)toArray;
- (id)setWithInt:(int)arg1 withId:(id)arg2;
- (void)removeRangeWithInt:(int)arg1 withInt:(int)arg2;
- (_Bool)removeWithId:(id)arg1;
- (id)removeWithInt:(int)arg1;
- (int)lastIndexOfWithId:(id)arg1;
- (int)indexOfWithId:(id)arg1;
- (_Bool)containsWithId:(id)arg1;
- (_Bool)isEmpty;
- (int)size;
- (id)getWithInt:(int)arg1;
- (void)ensureCapacityWithInt:(int)arg1;
- (id)clone;
- (void)clear;
- (_Bool)addAllWithInt:(int)arg1 withJavaUtilCollection:(id)arg2;
- (_Bool)addAllWithJavaUtilCollection:(id)arg1;
- (void)addWithInt:(int)arg1 withId:(id)arg2;
- (_Bool)addWithId:(id)arg1;
- (id)initWithJavaUtilCollection:(id)arg1;
- (id)init;
- (id)initWithInt:(int)arg1;

@end

