//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoCloseable.h"

@class JavaNetInetAddress, JavaNetSocketImpl;

@interface JavaNetServerSocket : NSObject <JavaIoCloseable>
{
    JavaNetSocketImpl *impl_;
    _Bool isBound__;
    _Bool isClosed__;
    JavaNetInetAddress *localAddress_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)setSocketFactoryWithJavaNetSocketImplFactory:(id)arg1;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)setPerformancePreferencesWithInt:(int)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (id)getChannel;
- (int)getReceiveBufferSize;
- (void)setReceiveBufferSizeWithInt:(int)arg1;
- (_Bool)getReuseAddress;
- (void)setReuseAddressWithBoolean:(_Bool)arg1;
- (void)checkOpen;
- (_Bool)isClosed;
- (_Bool)isBound;
- (id)getLocalSocketAddress;
- (void)bindWithJavaNetSocketAddress:(id)arg1 withInt:(int)arg2;
- (void)bindWithJavaNetSocketAddress:(id)arg1;
- (id)description;
- (void)setSoTimeoutWithInt:(int)arg1;
- (void)implAcceptWithJavaNetSocket:(id)arg1;
- (int)getSoTimeout;
- (int)getLocalPort;
- (id)getInetAddress;
- (void)close;
- (void)checkListenWithInt:(int)arg1;
- (id)accept;
- (void)readBackBindState;
- (id)initWithInt:(int)arg1 withInt:(int)arg2 withJavaNetInetAddress:(id)arg3;
- (id)initJavaNetServerSocketWithInt:(int)arg1 withInt:(int)arg2 withJavaNetInetAddress:(id)arg3;
- (id)initWithInt:(int)arg1 withInt:(int)arg2;
- (id)initWithInt:(int)arg1;
- (id)init;
- (id)getImpl$;

@end

