//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JavaUtilLinkedHashMap, JavaUtilLinkedHashMap_LinkedHashMapEntry;

@interface JavaUtilLinkedHashMap_AbstractMapIterator : NSObject
{
    int expectedModCount_;
    JavaUtilLinkedHashMap_LinkedHashMapEntry *futureEntry_;
    JavaUtilLinkedHashMap_LinkedHashMapEntry *currentEntry_;
    JavaUtilLinkedHashMap *associatedMap_;
}

- (void)dealloc;
- (void)remove;
- (void)makeNext;
- (void)checkConcurrentMod;
- (_Bool)hasNext;
- (id)initWithJavaUtilLinkedHashMap:(id)arg1;

@end

