//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilIterator.h"

@class JavaUtilArrayList;

@interface JavaUtilArrayList_ArrayListIterator : NSObject <JavaUtilIterator>
{
    JavaUtilArrayList *this$0_;
    int remaining_;
    int removalIndex_;
    int expectedModCount_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)initWithJavaUtilArrayList:(id)arg1;
- (void)remove;
- (id)next;
- (_Bool)hasNext;

@end

