//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaLangIllegalArgumentException.h"

#import "JavaIoSerializable.h"

@interface JavaUtilIllegalFormatException : JavaLangIllegalArgumentException <JavaIoSerializable>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)init;

@end

