//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractMap.h"

#import "JavaIoSerializable.h"

@interface JavaUtilCollections_EmptyMap : JavaUtilAbstractMap <JavaIoSerializable>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)init;
- (id)readResolve;
- (id)values;
- (id)keySet;
- (id)getWithId:(id)arg1;
- (id)entrySet;
- (_Bool)containsValueWithId:(id)arg1;
- (_Bool)containsKeyWithId:(id)arg1;

@end

