//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilIterator.h"

@class JavaUtilWeakHashMap, JavaUtilWeakHashMap_Entry;

@interface JavaUtilWeakHashMap_HashIterator : NSObject <JavaUtilIterator>
{
    id <JavaUtilWeakHashMap_Entry_Type> type_;
    JavaUtilWeakHashMap *this$0_;
    int position_;
    int expectedModCount_;
    JavaUtilWeakHashMap_Entry *currentEntry_;
    JavaUtilWeakHashMap_Entry *nextEntry_;
    id nextKey_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)remove;
- (id)next;
- (_Bool)hasNext;
- (id)initWithJavaUtilWeakHashMap:(id)arg1 withJavaUtilWeakHashMap_Entry_Type:(id)arg2;

@end

