//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaNioChannelsDatagramChannel.h"

#import "JavaNioFileDescriptorChannel.h"

@class JavaIoFileDescriptor, JavaNetDatagramSocket, JavaNetInetAddress, JavaNetInetSocketAddress;

@interface JavaNioDatagramChannelImpl : JavaNioChannelsDatagramChannel <JavaNioFileDescriptorChannel>
{
    JavaNetInetSocketAddress *connectAddress_;
    JavaNetInetAddress *localAddress_;
    _Bool connected_;
    _Bool isBound_;
    JavaIoFileDescriptor *fd_;
    JavaNetDatagramSocket *socket__;
    int localPort_;
    id readLock_;
    id writeLock_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)getFD;
- (void)checkNotNullWithJavaNioByteBuffer:(id)arg1;
- (void)checkOpenConnected;
- (void)checkOpen;
- (void)implConfigureBlockingWithBoolean:(_Bool)arg1;
- (void)implCloseSelectableChannel;
- (int)writeImplWithJavaNioByteBuffer:(id)arg1;
- (long long)writeWithJavaNioByteBufferArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (int)writeWithJavaNioByteBuffer:(id)arg1;
- (int)readImplWithJavaNioByteBuffer:(id)arg1;
- (long long)readWithJavaNioByteBufferArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (int)readWithJavaNioByteBuffer:(id)arg1;
- (int)sendWithJavaNioByteBuffer:(id)arg1 withJavaNetSocketAddress:(id)arg2;
- (id)receiveDirectImplWithJavaNioByteBuffer:(id)arg1 withBoolean:(_Bool)arg2;
- (id)receiveImplWithJavaNioByteBuffer:(id)arg1 withBoolean:(_Bool)arg2;
- (id)receiveWithJavaNioByteBuffer:(id)arg1;
- (void)onDisconnectWithBoolean:(_Bool)arg1;
- (id)disconnect;
- (void)onConnectWithJavaNetInetAddress:(id)arg1 withInt:(int)arg2 withBoolean:(_Bool)arg3;
- (id)connectWithJavaNetSocketAddress:(id)arg1;
- (_Bool)isConnected;
- (id)supportedOptions;
- (id)setOptionWithJavaNetSocketOption:(id)arg1 withId:(id)arg2;
- (id)getOptionWithJavaNetSocketOption:(id)arg1;
- (id)getLocalAddress;
- (void)onBindWithBoolean:(_Bool)arg1;
- (id)bindWithJavaNetSocketAddress:(id)arg1;
- (id)socket;
- (id)init;
- (id)initWithJavaNioChannelsSpiSelectorProvider:(id)arg1;

@end

