//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilMap_Entry.h"

@interface JavaUtilTreeMap_Node : NSObject <JavaUtilMap_Entry>
{
    JavaUtilTreeMap_Node *parent_;
    JavaUtilTreeMap_Node *left_;
    JavaUtilTreeMap_Node *right_;
    id key_;
    id value_;
    int height_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)last;
- (id)first;
- (id)prev;
- (id)next;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)setValueWithId:(id)arg1;
- (id)getValue;
- (id)getKey;
- (id)copy__WithJavaUtilTreeMap_Node:(id)arg1;
- (id)initWithJavaUtilTreeMap_Node:(id)arg1 withId:(id)arg2;

@end

