//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoSerializable.h"
#import "JavaUtilList.h"
#import "JavaUtilRandomAccess.h"
#import "NSCopying.h"

@class IOSObjectArray;

@interface JavaUtilConcurrentCopyOnWriteArrayList : NSObject <JavaUtilList, JavaUtilRandomAccess, NSCopying, JavaIoSerializable>
{
    IOSObjectArray *elements_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (int)indexOfWithId:(id)arg1 withNSObjectArray:(id)arg2 withInt:(int)arg3 withInt:(int)arg4;
+ (int)lastIndexOfWithId:(id)arg1 withNSObjectArray:(id)arg2 withInt:(int)arg3 withInt:(int)arg4;
+ (_Bool)containsAllWithJavaUtilCollection:(id)arg1 withNSObjectArray:(id)arg2 withInt:(int)arg3 withInt:(int)arg4;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)getArray;
- (void)removeRangeWithInt:(int)arg1 withInt:(int)arg2;
- (id)setWithInt:(int)arg1 withId:(id)arg2;
- (int)removeOrRetainWithJavaUtilCollection:(id)arg1 withBoolean:(_Bool)arg2 withInt:(int)arg3 withInt:(int)arg4;
- (_Bool)retainAllWithJavaUtilCollection:(id)arg1;
- (_Bool)removeAllWithJavaUtilCollection:(id)arg1;
- (_Bool)removeWithId:(id)arg1;
- (id)removeWithInt:(int)arg1;
- (void)clear;
- (_Bool)addIfAbsentWithId:(id)arg1;
- (int)addAllAbsentWithJavaUtilCollection:(id)arg1;
- (_Bool)addAllWithInt:(int)arg1 withJavaUtilCollection:(id)arg2;
- (_Bool)addAllWithJavaUtilCollection:(id)arg1;
- (void)addWithInt:(int)arg1 withId:(id)arg2;
- (_Bool)addWithId:(id)arg1;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)toArrayWithNSObjectArray:(id)arg1;
- (id)toArray;
- (id)subListWithInt:(int)arg1 withInt:(int)arg2;
- (id)listIterator;
- (id)listIteratorWithInt:(int)arg1;
- (id)iterator;
- (_Bool)isEmpty;
- (int)lastIndexOfWithId:(id)arg1;
- (int)lastIndexOfWithId:(id)arg1 withInt:(int)arg2;
- (int)indexOfWithId:(id)arg1;
- (int)indexOfWithId:(id)arg1 withInt:(int)arg2;
- (_Bool)containsAllWithJavaUtilCollection:(id)arg1;
- (_Bool)containsWithId:(id)arg1;
- (id)getWithInt:(int)arg1;
- (int)size;
- (id)clone;
- (id)initWithNSObjectArray:(id)arg1;
- (id)initJavaUtilConcurrentCopyOnWriteArrayListWithNSObjectArray:(id)arg1;
- (id)initWithJavaUtilCollection:(id)arg1;
- (id)init;

@end

