//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractSet.h"

#import "JavaIoSerializable.h"

@interface JavaUtilCollections_SetFromMap : JavaUtilAbstractSet <JavaIoSerializable>
{
    id <JavaUtilMap> m_;
    id <JavaUtilSet> backingSet_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)readObjectWithJavaIoObjectInputStream:(id)arg1;
- (int)size;
- (id)iterator;
- (id)toArrayWithNSObjectArray:(id)arg1;
- (id)toArray;
- (_Bool)retainAllWithJavaUtilCollection:(id)arg1;
- (_Bool)removeWithId:(id)arg1;
- (_Bool)isEmpty;
- (_Bool)containsAllWithJavaUtilCollection:(id)arg1;
- (_Bool)containsWithId:(id)arg1;
- (id)description;
- (void)clear;
- (_Bool)addWithId:(id)arg1;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithJavaUtilMap:(id)arg1;

@end

