//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JavaUtilConcurrentCountDownLatch_Sync;

@interface JavaUtilConcurrentCountDownLatch : NSObject
{
    JavaUtilConcurrentCountDownLatch_Sync *sync_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)description;
- (long long)getCount;
- (void)countDown;
- (_Bool)awaitWithLong:(long long)arg1 withJavaUtilConcurrentTimeUnitEnum:(id)arg2;
- (void)await;
- (id)initWithInt:(int)arg1;

@end

