//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractSet.h"

@class JavaUtilHashMap;

@interface JavaUtilHashMap_HashMapEntrySet : JavaUtilAbstractSet
{
    JavaUtilHashMap *associatedMap_;
}

+ (_Bool)valuesEqWithJavaUtilHashMap_Entry:(id)arg1 withJavaUtilMap_Entry:(id)arg2;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)iterator;
- (_Bool)containsWithId:(id)arg1;
- (_Bool)removeWithId:(id)arg1;
- (void)clear;
- (int)size;
- (id)hashMap;
- (id)initWithJavaUtilHashMap:(id)arg1;

@end

