//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaNioDoubleBuffer.h"

@class IOSDoubleArray;

@interface JavaNioDoubleArrayBuffer : JavaNioDoubleBuffer
{
    IOSDoubleArray *backingArray_;
    int arrayOffset_;
    _Bool isReadOnly__;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)copy__WithJavaNioDoubleArrayBuffer:(id)arg1 withInt:(int)arg2 withBoolean:(_Bool)arg3;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)putWithDoubleArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (id)putWithInt:(int)arg1 withDouble:(double)arg2;
- (id)putWithDouble:(double)arg1;
- (id)order;
- (_Bool)isDirect;
- (id)getWithDoubleArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (double)getWithInt:(int)arg1;
- (double)get;
- (_Bool)protectedHasArray;
- (int)protectedArrayOffset;
- (id)protectedArray;
- (_Bool)isReadOnly;
- (id)slice;
- (id)duplicate;
- (id)compact;
- (id)asReadOnlyBuffer;
- (id)initWithInt:(int)arg1 withDoubleArray:(id)arg2 withInt:(int)arg3 withBoolean:(_Bool)arg4;
- (id)initJavaNioDoubleArrayBufferWithInt:(int)arg1 withDoubleArray:(id)arg2 withInt:(int)arg3 withBoolean:(_Bool)arg4;
- (id)initWithDoubleArray:(id)arg1;

@end

