//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractList.h"

@class JavaUtilConcurrentCopyOnWriteArrayList, JavaUtilConcurrentCopyOnWriteArrayList_Slice;

@interface JavaUtilConcurrentCopyOnWriteArrayList_CowSubList : JavaUtilAbstractList
{
    JavaUtilConcurrentCopyOnWriteArrayList *this$0_;
    JavaUtilConcurrentCopyOnWriteArrayList_Slice *slice_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (_Bool)retainAllWithJavaUtilCollection:(id)arg1;
- (_Bool)removeAllWithJavaUtilCollection:(id)arg1;
- (_Bool)removeWithId:(id)arg1;
- (id)setWithInt:(int)arg1 withId:(id)arg2;
- (_Bool)addAllWithJavaUtilCollection:(id)arg1;
- (_Bool)addAllWithInt:(int)arg1 withJavaUtilCollection:(id)arg2;
- (_Bool)addWithId:(id)arg1;
- (void)addWithInt:(int)arg1 withId:(id)arg2;
- (void)clear;
- (id)removeWithInt:(int)arg1;
- (id)subListWithInt:(int)arg1 withInt:(int)arg2;
- (_Bool)containsAllWithJavaUtilCollection:(id)arg1;
- (_Bool)containsWithId:(id)arg1;
- (int)lastIndexOfWithId:(id)arg1;
- (int)indexOfWithId:(id)arg1;
- (id)listIteratorWithInt:(int)arg1;
- (id)listIterator;
- (id)iterator;
- (id)getWithInt:(int)arg1;
- (_Bool)isEmpty;
- (int)size;
- (id)initWithJavaUtilConcurrentCopyOnWriteArrayList:(id)arg1 withNSObjectArray:(id)arg2 withInt:(int)arg3 withInt:(int)arg4;

@end

