//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JavaLangThread;

@interface JavaUtilConcurrentLocksAbstractQueuedSynchronizer_Node : NSObject
{
    int waitStatus_;
    JavaUtilConcurrentLocksAbstractQueuedSynchronizer_Node *prev_;
    JavaUtilConcurrentLocksAbstractQueuedSynchronizer_Node *next_;
    JavaLangThread *thread_;
    JavaUtilConcurrentLocksAbstractQueuedSynchronizer_Node *nextWaiter_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)initWithJavaLangThread:(id)arg1 withInt:(int)arg2;
- (id)initWithJavaLangThread:(id)arg1 withJavaUtilConcurrentLocksAbstractQueuedSynchronizer_Node:(id)arg2;
- (id)init;
- (id)predecessor;
- (_Bool)isShared;

@end

