//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoCloseable.h"

@class JavaNetDatagramSocketImpl, JavaNetInetAddress, JavaNetSocketException;

@interface JavaNetDatagramSocket : NSObject <JavaIoCloseable>
{
    JavaNetDatagramSocketImpl *impl_;
    JavaNetInetAddress *address_;
    int port_;
    _Bool isBound__;
    _Bool isConnected__;
    JavaNetSocketException *pendingConnectException_;
    _Bool isClosed__;
    id lock_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)setDatagramSocketImplFactoryWithJavaNetDatagramSocketImplFactory:(id)arg1;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)getFileDescriptor$;
- (id)getChannel;
- (_Bool)isClosed;
- (int)getTrafficClass;
- (void)setTrafficClassWithInt:(int)arg1;
- (_Bool)getBroadcast;
- (void)setBroadcastWithBoolean:(_Bool)arg1;
- (_Bool)getReuseAddress;
- (void)setReuseAddressWithBoolean:(_Bool)arg1;
- (id)getLocalSocketAddress;
- (id)getRemoteSocketAddress;
- (_Bool)isConnected;
- (_Bool)isBound;
- (void)connectWithJavaNetInetAddress:(id)arg1 withInt:(int)arg2;
- (void)onConnectWithJavaNetInetAddress:(id)arg1 withInt:(int)arg2;
- (void)connectWithJavaNetSocketAddress:(id)arg1;
- (void)onBindWithJavaNetInetAddress:(id)arg1 withInt:(int)arg2;
- (void)bindWithJavaNetSocketAddress:(id)arg1;
- (void)ensureBound;
- (void)checkOpen;
- (id)initWithJavaNetSocketAddress:(id)arg1;
- (id)initWithJavaNetDatagramSocketImpl:(id)arg1;
- (void)setSoTimeoutWithInt:(int)arg1;
- (void)setReceiveBufferSizeWithInt:(int)arg1;
- (void)setSendBufferSizeWithInt:(int)arg1;
- (void)setNetworkInterfaceWithJavaNetNetworkInterface:(id)arg1;
- (void)sendWithJavaNetDatagramPacket:(id)arg1;
- (void)receiveWithJavaNetDatagramPacket:(id)arg1;
- (int)getSoTimeout;
- (int)getSendBufferSize;
- (int)getReceiveBufferSize;
- (_Bool)isMulticastSocket;
- (int)getPort;
- (int)getLocalPort;
- (id)getLocalAddress;
- (id)getInetAddress;
- (void)createSocketWithInt:(int)arg1 withJavaNetInetAddress:(id)arg2;
- (void)onDisconnect;
- (void)disconnect;
- (void)onClose;
- (void)close;
- (void)checkPortWithInt:(int)arg1;
- (id)initWithInt:(int)arg1 withJavaNetInetAddress:(id)arg2;
- (id)initWithInt:(int)arg1;
- (id)initJavaNetDatagramSocketWithInt:(int)arg1;
- (id)init;

@end

