//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractList.h"

#import "JavaIoSerializable.h"
#import "JavaUtilList.h"
#import "JavaUtilRandomAccess.h"

@class IOSObjectArray;

@interface JavaUtilArrays_ArrayList : JavaUtilAbstractList <JavaUtilList, JavaIoSerializable, JavaUtilRandomAccess>
{
    IOSObjectArray *a_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)toArrayWithNSObjectArray:(id)arg1;
- (id)toArray;
- (int)size;
- (id)setWithInt:(int)arg1 withId:(id)arg2;
- (int)lastIndexOfWithId:(id)arg1;
- (int)indexOfWithId:(id)arg1;
- (id)getWithInt:(int)arg1;
- (_Bool)containsWithId:(id)arg1;
- (id)initWithNSObjectArray:(id)arg1;

@end

