//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoSerializable.h"
#import "JavaUtilCollection.h"

@interface JavaUtilCollections_SynchronizedCollection : NSObject <JavaUtilCollection, JavaIoSerializable>
{
    id <JavaUtilCollection> c_;
    id mutex_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)writeObjectWithJavaIoObjectOutputStream:(id)arg1;
- (id)toArrayWithNSObjectArray:(id)arg1;
- (id)description;
- (id)toArray;
- (int)size;
- (_Bool)retainAllWithJavaUtilCollection:(id)arg1;
- (_Bool)removeAllWithJavaUtilCollection:(id)arg1;
- (_Bool)removeWithId:(id)arg1;
- (id)iterator;
- (_Bool)isEmpty;
- (_Bool)containsAllWithJavaUtilCollection:(id)arg1;
- (_Bool)containsWithId:(id)arg1;
- (void)clear;
- (_Bool)addAllWithJavaUtilCollection:(id)arg1;
- (_Bool)addWithId:(id)arg1;
- (id)initWithJavaUtilCollection:(id)arg1 withId:(id)arg2;
- (id)initWithJavaUtilCollection:(id)arg1;

@end

