//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilHashSet.h"

#import "JavaIoSerializable.h"
#import "JavaUtilSet.h"
#import "NSCopying.h"

@interface JavaUtilLinkedHashSet : JavaUtilHashSet <JavaUtilSet, NSCopying, JavaIoSerializable>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)createBackingMapWithInt:(int)arg1 withFloat:(float)arg2;
- (id)initWithJavaUtilCollection:(id)arg1;
- (id)initWithInt:(int)arg1 withFloat:(float)arg2;
- (id)initWithInt:(int)arg1;
- (id)init;

@end

