//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JavaLangRuntime : NSObject
{
    id <JavaUtilList> shutdownHooks_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)getRuntime;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)registerShutdownHooks;
- (void)runShutdownHooks;
- (_Bool)removeShutdownHookWithJavaLangThread:(id)arg1;
- (void)addShutdownHookWithJavaLangThread:(id)arg1;
- (long long)freeMemory;
- (long long)totalMemory;
- (long long)maxMemory;
- (void)gc;
- (void)haltWithInt:(int)arg1;
- (void)exitWithInt:(int)arg1;
- (int)availableProcessors;
- (id)init;

@end

