//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSNumber.h"

#import "JavaLangComparable.h"

@interface JavaLangShort : NSNumber <JavaLangComparable>
{
    short value_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)valueOfWithShort:(short)arg1;
+ (short)reverseBytesWithShort:(short)arg1;
+ (id)valueOfWithNSString:(id)arg1 withInt:(int)arg2;
+ (id)valueOfWithNSString:(id)arg1;
+ (id)toStringWithShort:(short)arg1;
+ (short)parseShortWithNSString:(id)arg1 withInt:(int)arg2;
+ (short)parseShortWithNSString:(id)arg1;
+ (id)decodeWithNSString:(id)arg1;
+ (int)compareWithShort:(short)arg1 withShort:(short)arg2;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)getValue:(void *)arg1;
- (const char *)objCType;
- (void)copyAllFieldsTo:(id)arg1;
- (id)description;
- (short)shortValue;
- (long long)longLongValue;
- (int)intValue;
- (unsigned long long)hash;
- (float)floatValue;
- (_Bool)isEqual:(id)arg1;
- (double)doubleValue;
- (int)compareToWithId:(id)arg1;
- (BOOL)charValue;
- (id)initWithShort:(short)arg1;
- (id)initJavaLangShortWithShort:(short)arg1;
- (id)initWithNSString:(id)arg1;

@end

