//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaObject.h"
#import "NSObject.h"

@protocol JavaUtilMap_Entry <NSObject, JavaObject>
- (id)setValueWithId:(id)arg1;
- (unsigned long long)hash;
- (id)getValue;
- (id)getKey;
- (_Bool)isEqual:(id)arg1;
@end

