//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoCloseable.h"

@class JavaNetInetAddress, JavaNetProxy, JavaNetSocketImpl;

@interface JavaNetSocket : NSObject <JavaIoCloseable>
{
    JavaNetSocketImpl *impl_;
    _Bool isCreated_;
    JavaNetProxy *proxy_;
    _Bool isBound__;
    _Bool isConnected__;
    _Bool isClosed__;
    _Bool isInputShutdown__;
    _Bool isOutputShutdown__;
    JavaNetInetAddress *localAddress_;
    id connectLock_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations_JavaNetSocketWithJavaNetInetAddress_withInt_withBoolean_;
+ (id)__annotations_JavaNetSocketWithNSString_withInt_withBoolean_;
+ (void)setSocketImplFactoryWithJavaNetSocketImplFactory:(id)arg1;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)setPerformancePreferencesWithInt:(int)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (id)getFileDescriptor$;
- (id)getChannel;
- (void)cacheLocalAddress;
- (void)accepted;
- (void)sendUrgentDataWithInt:(int)arg1;
- (int)getTrafficClass;
- (void)setTrafficClassWithInt:(int)arg1;
- (_Bool)getOOBInline;
- (void)setOOBInlineWithBoolean:(_Bool)arg1;
- (_Bool)getReuseAddress;
- (void)setReuseAddressWithBoolean:(_Bool)arg1;
- (_Bool)isOutputShutdown;
- (_Bool)isInputShutdown;
- (void)onConnectWithJavaNetInetAddress:(id)arg1 withInt:(int)arg2;
- (void)connectWithJavaNetSocketAddress:(id)arg1 withInt:(int)arg2;
- (void)connectWithJavaNetSocketAddress:(id)arg1;
- (void)onBindWithJavaNetInetAddress:(id)arg1 withInt:(int)arg2;
- (void)bindWithJavaNetSocketAddress:(id)arg1;
- (_Bool)isClosed;
- (_Bool)isConnected;
- (_Bool)isBound;
- (id)getRemoteSocketAddress;
- (id)getLocalSocketAddress;
- (void)checkOpenAndCreateWithBoolean:(_Bool)arg1;
- (void)shutdownOutput;
- (void)shutdownInput;
- (id)description;
- (_Bool)usingSocks;
- (void)startupSocketWithJavaNetInetAddress:(id)arg1 withInt:(int)arg2 withJavaNetInetAddress:(id)arg3 withInt:(int)arg4 withBoolean:(_Bool)arg5;
- (void)setTcpNoDelayWithBoolean:(_Bool)arg1;
- (void)setSoTimeoutWithInt:(int)arg1;
- (void)setSoLingerWithBoolean:(_Bool)arg1 withInt:(int)arg2;
- (void)setReceiveBufferSizeWithInt:(int)arg1;
- (void)setSendBufferSizeWithInt:(int)arg1;
- (void)setKeepAliveWithBoolean:(_Bool)arg1;
- (_Bool)getTcpNoDelay;
- (int)getSoTimeout;
- (int)getSendBufferSize;
- (int)getReceiveBufferSize;
- (int)getSoLinger;
- (int)getPort;
- (id)getOutputStream;
- (int)getLocalPort;
- (id)getLocalAddress;
- (_Bool)getKeepAlive;
- (id)getInputStream;
- (id)getInetAddress;
- (void)onClose;
- (void)close;
- (void)checkDestinationWithJavaNetInetAddress:(id)arg1 withInt:(int)arg2;
- (id)initWithJavaNetSocketImpl:(id)arg1;
- (id)initWithJavaNetInetAddress:(id)arg1 withInt:(int)arg2 withBoolean:(_Bool)arg3;
- (id)initWithJavaNetInetAddress:(id)arg1 withInt:(int)arg2 withJavaNetInetAddress:(id)arg3 withInt:(int)arg4;
- (id)initWithJavaNetInetAddress:(id)arg1 withInt:(int)arg2;
- (id)initWithNSString:(id)arg1 withInt:(int)arg2 withBoolean:(_Bool)arg3;
- (id)initWithNSString:(id)arg1 withInt:(int)arg2 withJavaNetInetAddress:(id)arg3 withInt:(int)arg4;
- (id)initJavaNetSocketWithNSString:(id)arg1 withInt:(int)arg2 withJavaNetInetAddress:(id)arg3 withInt:(int)arg4;
- (id)initWithNSString:(id)arg1 withInt:(int)arg2;
- (void)tryAllAddressesWithNSString:(id)arg1 withInt:(int)arg2 withJavaNetInetAddress:(id)arg3 withInt:(int)arg4 withBoolean:(_Bool)arg5;
- (id)initWithJavaNetProxy:(id)arg1;
- (id)init;
- (id)initJavaNetSocket;

@end

