//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JavaMethodMetadata : NSObject
{
    const struct J2ObjcMethodInfo *data_;
}

- (_Bool)isConstructor;
- (id)exceptionTypes;
- (id)returnType;
- (int)modifiers;
- (id)javaName;
- (id)name;
- (SEL)selector;
- (id)initWithMetadata:(const struct J2ObjcMethodInfo *)arg1;

@end

