//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoSerializable.h"

@class NSString;

@interface JavaUtilRegexPattern : NSObject <JavaIoSerializable>
{
    id nativePattern_;
    NSString *pattern__;
    int flags__;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)quoteWithNSString:(id)arg1;
+ (_Bool)matchesWithNSString:(id)arg1 withJavaLangCharSequence:(id)arg2;
+ (id)compileWithNSString:(id)arg1;
+ (id)compileWithNSString:(id)arg1 withInt:(int)arg2;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)releaseNativePattern;
- (void)compileImplWithNSString:(id)arg1 withInt:(int)arg2;
- (void)dealloc;
- (int)javaToIosFlags;
- (void)compile;
- (id)initWithNSString:(id)arg1 withInt:(int)arg2;
- (int)flags;
- (id)description;
- (id)pattern;
- (id)splitWithJavaLangCharSequence:(id)arg1;
- (id)splitWithJavaLangCharSequence:(id)arg1 withInt:(int)arg2;
- (id)matcherWithJavaLangCharSequence:(id)arg1;

@end

