//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaLangAnnotationRetention.h"

@class JavaLangAnnotationRetentionPolicyEnum;

@interface JavaLangAnnotationRetention : NSObject <JavaLangAnnotationRetention>
{
    JavaLangAnnotationRetentionPolicyEnum *value;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations;
@property(readonly) JavaLangAnnotationRetentionPolicyEnum *value; // @synthesize value;
- (id)annotationType;
- (id)initWithValue:(id)arg1;

@end

