//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaNioChannelsSocketChannel.h"

#import "JavaNioFileDescriptorChannel.h"

@class JavaIoFileDescriptor, JavaNetInetAddress, JavaNetInetSocketAddress, JavaNioSocketChannelImpl_SocketAdapter;

@interface JavaNioSocketChannelImpl : JavaNioChannelsSocketChannel <JavaNioFileDescriptorChannel>
{
    JavaIoFileDescriptor *fd_;
    JavaNioSocketChannelImpl_SocketAdapter *socket__;
    JavaNetInetSocketAddress *connectAddress_;
    JavaNetInetAddress *localAddress_;
    int localPort_;
    int status_;
    _Bool isBound_;
    id readLock_;
    id writeLock_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)validateAddressWithJavaNetSocketAddress:(id)arg1;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)onAcceptWithJavaNetInetSocketAddress:(id)arg1 withBoolean:(_Bool)arg2;
- (id)getFD;
- (void)implConfigureBlockingWithBoolean:(_Bool)arg1;
- (void)implCloseSelectableChannel;
- (void)checkUnconnected;
- (void)checkOpenConnected;
- (int)writeImplWithJavaNioByteBuffer:(id)arg1;
- (long long)writeWithJavaNioByteBufferArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (int)writeWithJavaNioByteBuffer:(id)arg1;
- (int)readImplWithJavaNioByteBuffer:(id)arg1;
- (long long)readWithJavaNioByteBufferArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (int)readWithJavaNioByteBuffer:(id)arg1;
- (_Bool)finishConnect;
- (_Bool)isEINPROGRESSWithJavaIoIOException:(id)arg1;
- (void)onConnectStatusChangedWithJavaNetInetSocketAddress:(id)arg1 withInt:(int)arg2 withBoolean:(_Bool)arg3;
- (_Bool)connectWithJavaNetSocketAddress:(id)arg1;
- (_Bool)isConnectionPending;
- (_Bool)isConnected;
- (id)supportedOptions;
- (id)setOptionWithJavaNetSocketOption:(id)arg1 withId:(id)arg2;
- (id)getOptionWithJavaNetSocketOption:(id)arg1;
- (id)getLocalAddress;
- (void)onBindWithBoolean:(_Bool)arg1;
- (id)bindWithJavaNetSocketAddress:(id)arg1;
- (id)socket;
- (id)initWithJavaNioChannelsSpiSelectorProvider:(id)arg1 withJavaIoFileDescriptor:(id)arg2;
- (id)initWithJavaNioChannelsSpiSelectorProvider:(id)arg1 withBoolean:(_Bool)arg2;
- (id)initJavaNioSocketChannelImplWithJavaNioChannelsSpiSelectorProvider:(id)arg1 withBoolean:(_Bool)arg2;
- (id)initWithJavaNioChannelsSpiSelectorProvider:(id)arg1;

@end

