//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class JavaNetProxy_TypeEnum, JavaNetSocketAddress;

@interface JavaNetProxy : NSObject
{
    JavaNetProxy_TypeEnum *type__;
    JavaNetSocketAddress *address__;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)description;
- (id)address;
- (id)type;
- (id)init;
- (id)initWithJavaNetProxy_TypeEnum:(id)arg1 withJavaNetSocketAddress:(id)arg2;

@end

