//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoSerializable.h"
#import "JavaUtilComparator.h"

@interface JavaUtilCollections_ReverseComparator2 : NSObject <JavaUtilComparator, JavaIoSerializable>
{
    id <JavaUtilComparator> cmp_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (int)compareWithId:(id)arg1 withId:(id)arg2;
- (id)initWithJavaUtilComparator:(id)arg1;

@end

