//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractSet.h"

#import "JavaIoSerializable.h"
#import "JavaUtilSet.h"
#import "NSCopying.h"

@class JavaUtilHashMap;

@interface JavaUtilHashSet : JavaUtilAbstractSet <JavaUtilSet, NSCopying, JavaIoSerializable>
{
    JavaUtilHashMap *backingMap_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)createBackingMapWithInt:(int)arg1 withFloat:(float)arg2;
- (int)size;
- (_Bool)removeWithId:(id)arg1;
- (id)iterator;
- (_Bool)isEmpty;
- (_Bool)containsWithId:(id)arg1;
- (id)clone;
- (void)clear;
- (_Bool)addWithId:(id)arg1;
- (id)initWithJavaUtilHashMap:(id)arg1;
- (id)initJavaUtilHashSetWithJavaUtilHashMap:(id)arg1;
- (id)initWithJavaUtilCollection:(id)arg1;
- (id)initWithInt:(int)arg1 withFloat:(float)arg2;
- (id)initWithInt:(int)arg1;
- (id)init;

@end

