//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilEnumeration.h"

@class JavaUtilPropertyResourceBundle, NSString;

@interface JavaUtilPropertyResourceBundle_$1 : NSObject <JavaUtilEnumeration>
{
    id <JavaUtilEnumeration> local_;
    id <JavaUtilEnumeration> pEnum_;
    NSString *nextElement__;
    JavaUtilPropertyResourceBundle *this$0_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)initWithJavaUtilPropertyResourceBundle:(id)arg1;
- (id)nextElement;
- (_Bool)hasMoreElements;
- (_Bool)findNext;

@end

