//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilCalendar.h"

@interface JavaUtilGregorianCalendar : JavaUtilCalendar
{
    long long gregorianCutover_;
    int changeYear_;
    int julianSkew_;
    int currentYearSkew_;
    int lastYearSkew_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)readObjectWithJavaIoObjectInputStream:(id)arg1;
- (void)writeObjectWithJavaIoObjectOutputStream:(id)arg1;
- (void)setGregorianChangeWithJavaUtilDate:(id)arg1;
- (void)rollWithInt:(int)arg1 withBoolean:(_Bool)arg2;
- (void)rollWithInt:(int)arg1 withInt:(int)arg2;
- (int)mod7WithLong:(long long)arg1;
- (int)modWithInt:(int)arg1 withInt:(int)arg2;
- (int)julianError;
- (_Bool)isLeapYearWithInt:(int)arg1;
- (unsigned long long)hash;
- (int)getOffsetWithLong:(long long)arg1;
- (int)getMinimumWithInt:(int)arg1;
- (int)getMaximumWithInt:(int)arg1;
- (int)getLeastMaximumWithInt:(int)arg1;
- (id)getGregorianChange;
- (int)getGreatestMinimumWithInt:(int)arg1;
- (int)getActualMinimumWithInt:(int)arg1;
- (int)getActualMaximumWithInt:(int)arg1;
- (_Bool)isEqual:(id)arg1;
- (int)daysInYearWithBoolean:(_Bool)arg1 withInt:(int)arg2;
- (int)daysInYearWithInt:(int)arg1;
- (int)daysInMonthWithBoolean:(_Bool)arg1 withInt:(int)arg2;
- (int)daysInMonth;
- (long long)daysFromBaseYearWithLong:(long long)arg1;
- (int)computeYearAndDayWithLong:(long long)arg1 withLong:(long long)arg2;
- (void)computeTime;
- (void)computeFields;
- (void)fullFieldsCalcWithLong:(long long)arg1 withInt:(int)arg2;
- (void)addWithInt:(int)arg1 withInt:(int)arg2;
- (id)initWithBoolean:(_Bool)arg1;
- (id)initJavaUtilGregorianCalendarWithBoolean:(_Bool)arg1;
- (id)initWithJavaUtilTimeZone:(id)arg1 withJavaUtilLocale:(id)arg2;
- (id)initJavaUtilGregorianCalendarWithJavaUtilTimeZone:(id)arg1 withJavaUtilLocale:(id)arg2;
- (id)initWithJavaUtilTimeZone:(id)arg1;
- (id)initWithJavaUtilLocale:(id)arg1;
- (id)initWithLong:(long long)arg1;
- (id)initWithInt:(int)arg1 withInt:(int)arg2 withInt:(int)arg3 withInt:(int)arg4 withInt:(int)arg5 withInt:(int)arg6;
- (id)initWithInt:(int)arg1 withInt:(int)arg2 withInt:(int)arg3 withInt:(int)arg4 withInt:(int)arg5;
- (id)initWithInt:(int)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (id)init;

@end

