//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaNioLongBuffer.h"

@class IOSLongArray;

@interface JavaNioLongArrayBuffer : JavaNioLongBuffer
{
    IOSLongArray *backingArray_;
    int arrayOffset_;
    _Bool isReadOnly__;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)copy__WithJavaNioLongArrayBuffer:(id)arg1 withInt:(int)arg2 withBoolean:(_Bool)arg3;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)putWithLongArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (id)putWithInt:(int)arg1 withLong:(long long)arg2;
- (id)putWithLong:(long long)arg1;
- (id)order;
- (_Bool)isDirect;
- (id)getWithLongArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (long long)getWithInt:(int)arg1;
- (long long)get;
- (_Bool)protectedHasArray;
- (int)protectedArrayOffset;
- (id)protectedArray;
- (_Bool)isReadOnly;
- (id)slice;
- (id)duplicate;
- (id)compact;
- (id)asReadOnlyBuffer;
- (id)initWithInt:(int)arg1 withLongArray:(id)arg2 withInt:(int)arg3 withBoolean:(_Bool)arg4;
- (id)initJavaNioLongArrayBufferWithInt:(int)arg1 withLongArray:(id)arg2 withInt:(int)arg3 withBoolean:(_Bool)arg4;
- (id)initWithLongArray:(id)arg1;

@end

