//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilRegexMatchResult.h"

@class IOSIntArray, NSString;

@interface JavaUtilRegexMatchResultImpl : NSObject <JavaUtilRegexMatchResult>
{
    NSString *text_;
    IOSIntArray *offsets_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (int)startWithInt:(int)arg1;
- (int)start;
- (int)groupCount;
- (id)groupWithInt:(int)arg1;
- (id)group;
- (int)endWithInt:(int)arg1;
- (int)end;
- (id)initWithNSString:(id)arg1 withIntArray:(id)arg2;

@end

