//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilDictionary.h"

#import "JavaIoSerializable.h"
#import "JavaUtilMap.h"
#import "NSCopying.h"

@class IOSObjectArray;

@interface JavaUtilHashtable : JavaUtilDictionary <JavaUtilMap, NSCopying, JavaIoSerializable>
{
    int elementCount_;
    IOSObjectArray *elementData_;
    int firstSlot_;
    int lastSlot_;
    int modCount_;
    float loadFactor_;
    int threshold_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)newEntryWithId:(id)arg1 withId:(id)arg2 withInt:(int)arg3;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)values;
- (id)description;
- (int)size;
- (id)removeWithId:(id)arg1;
- (void)rehash;
- (void)putAllWithJavaUtilMap:(id)arg1;
- (id)putWithId:(id)arg1 withId:(id)arg2;
- (id)keySet;
- (id)keys;
- (_Bool)isEmpty;
- (unsigned long long)hash;
- (id)getEntryWithId:(id)arg1;
- (id)getWithId:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)entrySet;
- (id)elements;
- (_Bool)containsValueWithId:(id)arg1;
- (_Bool)containsKeyWithId:(id)arg1;
- (_Bool)containsWithId:(id)arg1;
- (void)computeMaxSize;
- (id)clone;
- (void)clear;
- (id)newElementArrayWithInt:(int)arg1;
- (id)initWithJavaUtilMap:(id)arg1;
- (id)initWithInt:(int)arg1 withFloat:(float)arg2;
- (id)initWithInt:(int)arg1;
- (id)initJavaUtilHashtableWithInt:(int)arg1;
- (id)init;

@end

