//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "ExecutableMember.h"

#import "JavaLangReflectGenericDeclaration.h"
#import "JavaLangReflectMember.h"

@interface JavaLangReflectConstructor : ExecutableMember <JavaLangReflectGenericDeclaration, JavaLangReflectMember>
{
}

+ (id)constructorWithMethodSignature:(id)arg1 selector:(SEL)arg2 class:(id)arg3 metadata:(id)arg4;
- (id)internalName;
- (id)getName;
- (id)newInstanceWithNSObjectArray:(id)arg1;

@end

