//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractMap.h"

#import "JavaIoSerializable.h"
#import "JavaUtilNavigableMap.h"
#import "JavaUtilSortedMap.h"
#import "NSCopying.h"

@class JavaUtilTreeMap_EntrySet, JavaUtilTreeMap_KeySet, JavaUtilTreeMap_Node, JavaUtilTreeMap_ValuesCollection;

@interface JavaUtilTreeMap : JavaUtilAbstractMap <JavaUtilSortedMap, JavaUtilNavigableMap, NSCopying, JavaIoSerializable>
{
    id <JavaUtilComparator> comparator__;
    JavaUtilTreeMap_Node *root_;
    int size__;
    int modCount_;
    JavaUtilTreeMap_EntrySet *entrySet__;
    JavaUtilTreeMap_KeySet *keySet_TreeMap_;
    JavaUtilTreeMap_ValuesCollection *valuesCollection_TreeMap_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (int)countWithJavaUtilIterator:(id)arg1;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)descendingKeySet;
- (id)descendingMap;
- (id)tailMapWithId:(id)arg1;
- (id)tailMapWithId:(id)arg1 withBoolean:(_Bool)arg2;
- (id)headMapWithId:(id)arg1;
- (id)headMapWithId:(id)arg1 withBoolean:(_Bool)arg2;
- (id)subMapWithId:(id)arg1 withId:(id)arg2;
- (id)subMapWithId:(id)arg1 withBoolean:(_Bool)arg2 withId:(id)arg3 withBoolean:(_Bool)arg4;
- (id)values;
- (id)navigableKeySet;
- (id)keySet;
- (id)entrySet;
- (id)comparator;
- (id)higherKeyWithId:(id)arg1;
- (id)higherEntryWithId:(id)arg1;
- (id)ceilingKeyWithId:(id)arg1;
- (id)ceilingEntryWithId:(id)arg1;
- (id)floorKeyWithId:(id)arg1;
- (id)floorEntryWithId:(id)arg1;
- (id)lowerKeyWithId:(id)arg1;
- (id)lowerEntryWithId:(id)arg1;
- (id)lastKey;
- (id)pollLastEntry;
- (id)internalPollLastEntry;
- (id)lastEntry;
- (id)lastNode;
- (id)firstKey;
- (id)pollFirstEntry;
- (id)internalPollFirstEntry;
- (id)firstEntry;
- (id)firstNode;
- (id)immutableCopyWithJavaUtilMap_Entry:(id)arg1;
- (void)rotateRightWithJavaUtilTreeMap_Node:(id)arg1;
- (void)rotateLeftWithJavaUtilTreeMap_Node:(id)arg1;
- (void)rebalanceWithJavaUtilTreeMap_Node:(id)arg1 withBoolean:(_Bool)arg2;
- (void)replaceInParentWithJavaUtilTreeMap_Node:(id)arg1 withJavaUtilTreeMap_Node:(id)arg2;
- (id)removeInternalByKeyWithId:(id)arg1;
- (void)removeInternalWithJavaUtilTreeMap_Node:(id)arg1;
- (id)findByEntryWithJavaUtilMap_Entry:(id)arg1;
- (id)findByObjectWithId:(id)arg1;
- (id)findWithId:(id)arg1 withJavaUtilTreeMap_RelationEnum:(id)arg2;
- (id)putInternalWithId:(id)arg1 withId:(id)arg2;
- (id)removeWithId:(id)arg1;
- (void)clear;
- (id)putWithId:(id)arg1 withId:(id)arg2;
- (_Bool)containsKeyWithId:(id)arg1;
- (id)getWithId:(id)arg1;
- (_Bool)isEmpty;
- (int)size;
- (id)clone;
- (id)initWithJavaUtilSortedMap:(id)arg1;
- (id)initWithJavaUtilComparator:(id)arg1;
- (id)initWithJavaUtilMap:(id)arg1;
- (id)init;
- (id)initJavaUtilTreeMap;

@end

