//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilIllegalFormatException.h"

#import "JavaIoSerializable.h"

@class IOSClass;

@interface JavaUtilIllegalFormatConversionException : JavaUtilIllegalFormatException <JavaIoSerializable>
{
    unsigned short c_;
    IOSClass *arg_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)getMessage;
- (unsigned short)getConversion;
- (id)getArgumentClass;
- (id)initWithChar:(unsigned short)arg1 withIOSClass:(id)arg2;

@end

