//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilListIterator.h"

@class IOSClass;

@interface JavaUtilCollections_CheckedListIterator : NSObject <JavaUtilListIterator>
{
    id <JavaUtilListIterator> i_;
    IOSClass *type_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)addWithId:(id)arg1;
- (void)setWithId:(id)arg1;
- (int)previousIndex;
- (int)nextIndex;
- (id)previous;
- (_Bool)hasPrevious;
- (void)remove;
- (id)next;
- (_Bool)hasNext;
- (id)initWithJavaUtilListIterator:(id)arg1 withIOSClass:(id)arg2;

@end

