//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoSerializable.h"
#import "JavaUtilMap.h"

@interface JavaUtilCollections_UnmodifiableMap : NSObject <JavaUtilMap, JavaIoSerializable>
{
    id <JavaUtilMap> m_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)values;
- (int)size;
- (id)removeWithId:(id)arg1;
- (void)putAllWithJavaUtilMap:(id)arg1;
- (id)putWithId:(id)arg1 withId:(id)arg2;
- (id)keySet;
- (_Bool)isEmpty;
- (unsigned long long)hash;
- (id)getWithId:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)entrySet;
- (_Bool)containsValueWithId:(id)arg1;
- (_Bool)containsKeyWithId:(id)arg1;
- (void)clear;
- (id)initWithJavaUtilMap:(id)arg1;

@end

