//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoSerializable.h"

@class NSString;

@interface JavaUtilCurrency : NSObject <JavaIoSerializable>
{
    NSString *currencyCode_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)getAvailableCurrencies;
+ (id)getInstanceWithJavaUtilLocale:(id)arg1;
+ (id)getInstanceWithNSString:(id)arg1;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)description;
- (int)getDefaultFractionDigits;
- (id)getSymbolWithJavaUtilLocale:(id)arg1;
- (id)getSymbol;
- (id)getCurrencyCode;
- (id)initWithNSString:(id)arg1;

@end

