//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaLangAutoCloseable.h"

@class JavaNioChannelsFileChannel;

@interface JavaNioChannelsFileLock : NSObject <JavaLangAutoCloseable>
{
    JavaNioChannelsFileChannel *channel__;
    long long position__;
    long long size__;
    _Bool shared_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)description;
- (void)close;
- (void)release__;
- (_Bool)isValid;
- (_Bool)overlapsWithLong:(long long)arg1 withLong:(long long)arg2;
- (_Bool)isShared;
- (long long)size;
- (long long)position;
- (id)channel;
- (id)initWithJavaNioChannelsFileChannel:(id)arg1 withLong:(long long)arg2 withLong:(long long)arg3 withBoolean:(_Bool)arg4;

@end

