//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaNetInetAddress.h"

@class NSString;

@interface JavaNetInet6Address : JavaNetInetAddress
{
    _Bool scope_id_set_;
    int scope_id_;
    _Bool scope_ifname_set_;
    NSString *ifname_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)getByAddressWithNSString:(id)arg1 withByteArray:(id)arg2 withJavaNetNetworkInterface:(id)arg3;
+ (id)getByAddressWithNSString:(id)arg1 withByteArray:(id)arg2 withInt:(int)arg3;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)description;
- (void)readObjectWithJavaIoObjectInputStream:(id)arg1;
- (void)writeObjectWithJavaIoObjectOutputStream:(id)arg1;
- (id)getScopedInterface;
- (int)getScopeId;
- (_Bool)isSiteLocalAddress;
- (_Bool)isMulticastAddress;
- (_Bool)isMCSiteLocal;
- (_Bool)isMCOrgLocal;
- (_Bool)isMCNodeLocal;
- (_Bool)isMCLinkLocal;
- (_Bool)isMCGlobal;
- (_Bool)isLoopbackAddress;
- (_Bool)isLinkLocalAddress;
- (_Bool)isIPv4CompatibleAddress;
- (_Bool)isAnyLocalAddress;
- (_Bool)compareLocalTypeWithJavaNetInet6Address:(id)arg1;
- (id)initWithByteArray:(id)arg1 withNSString:(id)arg2 withInt:(int)arg3;

@end

