//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaNioBuffer.h"

#import "JavaLangComparable.h"

@interface JavaNioFloatBuffer : JavaNioBuffer <JavaLangComparable>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)wrapWithFloatArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
+ (id)wrapWithFloatArray:(id)arg1;
+ (id)allocateWithInt:(int)arg1;
+ (id)memDebugStaticReferences;
- (id)slice;
- (id)putWithInt:(int)arg1 withFloat:(float)arg2;
- (id)putWithJavaNioFloatBuffer:(id)arg1;
- (id)putWithFloatArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (id)putWithFloatArray:(id)arg1;
- (id)putWithFloat:(float)arg1;
- (_Bool)protectedHasArray;
- (int)protectedArrayOffset;
- (id)protectedArray;
- (id)order;
- (_Bool)isDirect;
- (unsigned long long)hash;
- (_Bool)hasArray;
- (float)getWithInt:(int)arg1;
- (id)getWithFloatArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (id)getWithFloatArray:(id)arg1;
- (float)get;
- (_Bool)isEqual:(id)arg1;
- (id)duplicate;
- (int)compareToWithId:(id)arg1;
- (id)compact;
- (id)asReadOnlyBuffer;
- (int)arrayOffset;
- (id)array;
- (id)initWithInt:(int)arg1 withLong:(long long)arg2;

@end

