//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractMap.h"

#import "JavaIoSerializable.h"
#import "JavaUtilMap.h"
#import "NSCopying.h"

@interface JavaUtilHashMap : JavaUtilAbstractMap <JavaUtilMap, NSCopying, JavaIoSerializable>
{
    int elementCount_;
    id *elementData_;
    int elementDataLength_;
    int modCount_;
    float loadFactor_;
    int threshold_;
}

+ (_Bool)areEqualValuesWithId:(id)arg1 withId:(id)arg2;
+ (_Bool)areEqualKeysWithId:(id)arg1 withId:(id)arg2;
+ (int)computeHashCodeWithId:(id)arg1;
+ (int)calculateCapacityWithInt:(int)arg1;
@property(nonatomic) int threshold; // @synthesize threshold=threshold_;
@property(nonatomic) float loadFactor; // @synthesize loadFactor=loadFactor_;
@property(nonatomic) int modCount; // @synthesize modCount=modCount_;
@property(nonatomic) int elementDataLength; // @synthesize elementDataLength=elementDataLength_;
@property(nonatomic) int elementCount; // @synthesize elementCount=elementCount_;
- (id)memDebugStrongReferences;
- (void)dealloc;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)values;
- (int)size;
- (id)removeEntryWithId:(id)arg1;
- (void)removeEntryWithJavaUtilHashMap_Entry:(id)arg1;
- (id)removeWithId:(id)arg1;
- (void)rehash;
- (void)rehashWithInt:(int)arg1;
- (void)putAllImplWithJavaUtilMap:(id)arg1;
- (void)putAllWithJavaUtilMap:(id)arg1;
- (id)createHashedEntryWithId:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (id)putImplWithId:(id)arg1 withId:(id)arg2;
- (id)putWithId:(id)arg1 withId:(id)arg2;
- (id)keySet;
- (_Bool)isEmpty;
- (id)findNullKeyEntry;
- (id)findNonNullKeyEntryWithId:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (id)getEntryWithId:(id)arg1;
- (id)getWithId:(id)arg1;
- (id)entrySet;
- (_Bool)containsValueWithId:(id)arg1;
- (_Bool)containsKeyWithId:(id)arg1;
- (void)computeThreshold;
- (id)clone;
- (void)copyAllFieldsTo:(id)arg1;
- (void)clear;
- (id)initWithJavaUtilMap:(id)arg1;
- (id)initWithInt:(int)arg1 withFloat:(float)arg2;
- (id)initJavaUtilHashMapWithInt:(int)arg1 withFloat:(float)arg2;
- (id)initWithInt:(int)arg1;
- (id)init;

@end

