//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilCollections_CheckedCollection.h"

#import "JavaUtilList.h"

@interface JavaUtilCollections_CheckedList : JavaUtilCollections_CheckedCollection <JavaUtilList>
{
    id <JavaUtilList> l_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)subListWithInt:(int)arg1 withInt:(int)arg2;
- (id)listIteratorWithInt:(int)arg1;
- (id)listIterator;
- (int)lastIndexOfWithId:(id)arg1;
- (int)indexOfWithId:(id)arg1;
- (id)removeWithInt:(int)arg1;
- (void)addWithInt:(int)arg1 withId:(id)arg2;
- (id)setWithInt:(int)arg1 withId:(id)arg2;
- (id)getWithInt:(int)arg1;
- (_Bool)addAllWithInt:(int)arg1 withJavaUtilCollection:(id)arg2;
- (id)initWithJavaUtilList:(id)arg1 withIOSClass:(id)arg2;

@end

