//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaNioChannelsFileLock.h"

@interface JavaNioFileChannelImpl_FileLockImpl : JavaNioChannelsFileLock
{
    _Bool isReleased_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)release__;
- (_Bool)isValid;
- (id)initWithJavaNioChannelsFileChannel:(id)arg1 withLong:(long long)arg2 withLong:(long long)arg3 withBoolean:(_Bool)arg4;

@end

