//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaObject.h"
#import "NSObject.h"

@protocol JavaLangCharSequence <NSObject, JavaObject>
- (id <JavaLangCharSequence>)subSequenceFrom:(int)arg1 to:(int)arg2;
- (unsigned short)charAtWithInt:(int)arg1;
- (int)sequenceLength;
@end

