//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilEventListenerProxy.h"

#import "JavaBeansPropertyChangeListener.h"

@class NSString;

@interface JavaBeansPropertyChangeListenerProxy : JavaUtilEventListenerProxy <JavaBeansPropertyChangeListener>
{
    NSString *propertyName_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)propertyChangeWithJavaBeansPropertyChangeEvent:(id)arg1;
- (id)getPropertyName;
- (id)initWithNSString:(id)arg1 withJavaBeansPropertyChangeListener:(id)arg2;

@end

