//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoCloseable.h"

@interface JavaNioChannelsSelector : NSObject <JavaIoCloseable>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)open;
+ (id)memDebugStaticReferences;
- (id)wakeup;
- (int)selectNow;
- (id)selectedKeys;
- (int)selectWithLong:(long long)arg1;
- (int)select;
- (id)provider;
- (id)keys;
- (_Bool)isOpen;
- (void)close;
- (id)init;

@end

