//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoSerializable.h"

@interface JavaUtilConcurrentAtomicAtomicReference : NSObject <JavaIoSerializable>
{
    id value_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)memoryBarrier;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (_Bool)compareAndSwapValueWithId:(id)arg1 withId:(id)arg2;
- (id)description;
- (id)getAndSetWithId:(id)arg1;
- (_Bool)weakCompareAndSetWithId:(id)arg1 withId:(id)arg2;
- (_Bool)compareAndSetWithId:(id)arg1 withId:(id)arg2;
- (void)lazySetWithId:(id)arg1;
- (void)setWithId:(id)arg1;
- (id)get;
- (id)init;
- (id)initWithId:(id)arg1;

@end

