//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractList.h"

@interface JavaUtilAbstractSequentialList : JavaUtilAbstractList
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)setWithInt:(int)arg1 withId:(id)arg2;
- (id)removeWithInt:(int)arg1;
- (id)listIteratorWithInt:(int)arg1;
- (id)iterator;
- (id)getWithInt:(int)arg1;
- (_Bool)addAllWithInt:(int)arg1 withJavaUtilCollection:(id)arg2;
- (void)addWithInt:(int)arg1 withId:(id)arg2;
- (id)init;

@end

