//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaIoFilterInputStream.h"

@class IOSByteArray;

@interface JavaIoBufferedInputStream : JavaIoFilterInputStream
{
    IOSByteArray *buf_;
    int count_;
    int marklimit_;
    int markpos_;
    int pos_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (long long)skipWithLong:(long long)arg1;
- (void)reset;
- (int)readWithByteArray:(id)arg1 withInt:(int)arg2 withInt:(int)arg3;
- (int)read;
- (_Bool)markSupported;
- (void)markWithInt:(int)arg1;
- (int)fillbufWithJavaIoInputStream:(id)arg1 withByteArray:(id)arg2;
- (void)close;
- (id)streamClosed;
- (int)available;
- (id)initWithJavaIoInputStream:(id)arg1 withInt:(int)arg2;
- (id)initJavaIoBufferedInputStreamWithJavaIoInputStream:(id)arg1 withInt:(int)arg2;
- (id)initWithJavaIoInputStream:(id)arg1;

@end

