//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class LibcoreIcuLocaleData, LibcoreIcuNativeDecimalFormat, NSString;

@interface JavaUtilFormatter_CachedDecimalFormat : NSObject
{
    LibcoreIcuNativeDecimalFormat *decimalFormat_;
    LibcoreIcuLocaleData *currentLocaleData_;
    NSString *currentPattern_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)updateWithLibcoreIcuLocaleData:(id)arg1 withNSString:(id)arg2;
- (id)init;

@end

