//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface JavaLangReflectModifier : NSObject
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)toStringWithInt:(int)arg1;
+ (_Bool)isVolatileWithInt:(int)arg1;
+ (_Bool)isTransientWithInt:(int)arg1;
+ (_Bool)isSynchronizedWithInt:(int)arg1;
+ (_Bool)isStrictWithInt:(int)arg1;
+ (_Bool)isStaticWithInt:(int)arg1;
+ (_Bool)isPublicWithInt:(int)arg1;
+ (_Bool)isProtectedWithInt:(int)arg1;
+ (_Bool)isPrivateWithInt:(int)arg1;
+ (_Bool)isNativeWithInt:(int)arg1;
+ (_Bool)isInterfaceWithInt:(int)arg1;
+ (_Bool)isFinalWithInt:(int)arg1;
+ (_Bool)isAbstractWithInt:(int)arg1;
+ (int)methodModifiers;
+ (int)interfaceModifiers;
+ (int)fieldModifiers;
+ (int)constructorModifiers;
+ (int)classModifiers;
+ (id)memDebugStaticReferences;
- (id)init;

@end

