//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaNioChannelsSpiAbstractInterruptibleChannel.h"

#import "JavaNioChannelsChannel.h"

@interface JavaNioChannelsSelectableChannel : JavaNioChannelsSpiAbstractInterruptibleChannel <JavaNioChannelsChannel>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (int)validOps;
- (id)register__WithJavaNioChannelsSelector:(id)arg1 withInt:(int)arg2 withId:(id)arg3;
- (id)register__WithJavaNioChannelsSelector:(id)arg1 withInt:(int)arg2;
- (id)provider;
- (id)keyForWithJavaNioChannelsSelector:(id)arg1;
- (_Bool)isRegistered;
- (_Bool)isBlocking;
- (id)configureBlockingWithBoolean:(_Bool)arg1;
- (id)blockingLock;
- (id)init;

@end

