//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaUtilAbstractCollection.h"

@class JavaUtilLinkedHashMap;

@interface JavaUtilLinkedHashMap_ValuesCollection : JavaUtilAbstractCollection
{
    JavaUtilLinkedHashMap *outer_;
}

- (unsigned long long)countByEnumeratingWithState:(CDStruct_70511ce9 *)arg1 objects:(id *)arg2 count:(unsigned long long)arg3;
- (id)initWithJavaUtilLinkedHashMap:(id)arg1;
- (id)iterator;
- (void)clear;
- (int)size;
- (_Bool)containsWithId:(id)arg1;

@end

