//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaLangSafeVarargs.h"

@interface JavaLangSafeVarargs : NSObject <JavaLangSafeVarargs>
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)__annotations;
- (id)annotationType;

@end

