//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaLangComparable.h"

@class JavaUtilHashSet, NSString;

@interface JavaNioCharsetCharset : NSObject <JavaLangComparable>
{
    NSString *canonicalName_;
    JavaUtilHashSet *aliasesSet_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)getDefaultCharset;
+ (id)defaultCharset;
+ (_Bool)isSupportedWithNSString:(id)arg1;
+ (id)forNameUEEWithNSString:(id)arg1;
+ (id)forNameWithNSString:(id)arg1;
+ (id)cacheCharsetWithNSString:(id)arg1 withJavaNioCharsetCharset:(id)arg2;
+ (id)availableCharsets;
+ (_Bool)isValidCharsetNameCharacterWithChar:(unsigned short)arg1;
+ (void)checkCharsetNameWithNSString:(id)arg1;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (int)compareToWithId:(id)arg1;
- (id)decodeWithJavaNioByteBuffer:(id)arg1;
- (id)encodeWithNSString:(id)arg1;
- (id)encodeWithJavaNioCharBuffer:(id)arg1;
- (_Bool)canEncode;
- (_Bool)isRegistered;
- (id)displayNameWithJavaUtilLocale:(id)arg1;
- (id)displayName;
- (id)aliases;
- (id)name;
- (id)newDecoder;
- (id)newEncoder;
- (_Bool)containsWithJavaNioCharsetCharset:(id)arg1;
- (id)initWithNSString:(id)arg1 withNSStringArray:(id)arg2;

@end

