//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaUtilMap_Entry.h"

@interface JavaUtilCollections_UnmodifiableMap_UnmodifiableEntrySet_UnmodifiableMapEntry : NSObject <JavaUtilMap_Entry>
{
    id <JavaUtilMap_Entry> mapEntry_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)description;
- (id)setValueWithId:(id)arg1;
- (unsigned long long)hash;
- (id)getValue;
- (id)getKey;
- (_Bool)isEqual:(id)arg1;
- (id)initWithJavaUtilMap_Entry:(id)arg1;

@end

