//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaNetDatagramSocket.h"

@class JavaNioDatagramChannelImpl;

@interface JavaNioDatagramChannelImpl_DatagramSocketAdapter : JavaNetDatagramSocket
{
    JavaNioDatagramChannelImpl *channelImpl_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (void)disconnect;
- (void)close;
- (void)sendWithJavaNetDatagramPacket:(id)arg1;
- (void)receiveWithJavaNetDatagramPacket:(id)arg1;
- (void)connectWithJavaNetInetAddress:(id)arg1 withInt:(int)arg2;
- (void)connectWithJavaNetSocketAddress:(id)arg1;
- (void)bindWithJavaNetSocketAddress:(id)arg1;
- (id)getChannel;
- (id)initWithJavaNetDatagramSocketImpl:(id)arg1 withJavaNioDatagramChannelImpl:(id)arg2;

@end

