//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "JavaIoSerializable.h"

@class JavaMathRoundingModeEnum;

@interface JavaMathMathContext : NSObject <JavaIoSerializable>
{
    int precision_;
    JavaMathRoundingModeEnum *roundingMode_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (void)initialize;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)getRoundingMode;
- (int)getPrecision;
- (id)initWithNSString:(id)arg1;
- (id)initWithInt:(int)arg1 withJavaMathRoundingModeEnum:(id)arg2;
- (id)initJavaMathMathContextWithInt:(int)arg1 withJavaMathRoundingModeEnum:(id)arg2;
- (id)initWithInt:(int)arg1;

@end

