//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "JavaNioChannelsSpiAbstractSelectionKey.h"

@class JavaNioChannelsSpiAbstractSelectableChannel, JavaNioSelectorImpl;

@interface JavaNioSelectionKeyImpl : JavaNioChannelsSpiAbstractSelectionKey
{
    JavaNioChannelsSpiAbstractSelectableChannel *channel__;
    int interestOps__;
    int readyOps__;
    JavaNioSelectorImpl *selector__;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)memDebugStaticReferences;
- (id)memDebugStrongReferences;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (_Bool)isConnected;
- (void)checkValid;
- (void)setReadyOpsWithInt:(int)arg1;
- (id)selector;
- (int)readyOps;
- (id)interestOpsWithInt:(int)arg1;
- (int)interestOpsNoCheck;
- (int)interestOps;
- (id)channel;
- (id)initWithJavaNioChannelsSpiAbstractSelectableChannel:(id)arg1 withInt:(int)arg2 withId:(id)arg3 withJavaNioSelectorImpl:(id)arg4;

@end

