//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCTableViewController.h"

@class NSLayoutConstraint, NSMutableArray, NSMutableDictionary;

@interface LatestInfoDetailViewController : HNCTableViewController
{
    NSLayoutConstraint *_latestInfoDetailListHeightConstraint;
    NSMutableDictionary *_selectLatestInfoDictionary;
    NSMutableArray *_latestInfoDetailArray;
}

@property(retain, nonatomic) NSMutableArray *latestInfoDetailArray; // @synthesize latestInfoDetailArray=_latestInfoDetailArray;
@property(retain, nonatomic) NSMutableDictionary *selectLatestInfoDictionary; // @synthesize selectLatestInfoDictionary=_selectLatestInfoDictionary;
@property(retain, nonatomic) NSLayoutConstraint *latestInfoDetailListHeightConstraint; // @synthesize latestInfoDetailListHeightConstraint=_latestInfoDetailListHeightConstraint;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)WebServiceObject:(id)arg1 didCompleteAT0002WithHeader:(id)arg2 withAT0002ResponseBody:(id)arg3;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)updateViewConstraints;
- (void)viewDidLoad;

@end

