//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface LibcoreIoOsConstants : NSObject
{
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)errnoNameWithInt:(int)arg1;
+ (id)gaiNameWithInt:(int)arg1;
+ (_Bool)WIFSIGNALEDWithInt:(int)arg1;
+ (_Bool)WIFSTOPPEDWithInt:(int)arg1;
+ (_Bool)WIFEXITEDWithInt:(int)arg1;
+ (int)WSTOPSIGWithInt:(int)arg1;
+ (int)WTERMSIGWithInt:(int)arg1;
+ (_Bool)WCOREDUMPWithInt:(int)arg1;
+ (int)WEXITSTATUSWithInt:(int)arg1;
+ (_Bool)S_ISSOCKWithInt:(int)arg1;
+ (_Bool)S_ISLNKWithInt:(int)arg1;
+ (_Bool)S_ISREGWithInt:(int)arg1;
+ (_Bool)S_ISFIFOWithInt:(int)arg1;
+ (_Bool)S_ISDIRWithInt:(int)arg1;
+ (_Bool)S_ISCHRWithInt:(int)arg1;
+ (_Bool)S_ISBLKWithInt:(int)arg1;
+ (id)memDebugStaticReferences;
- (id)init;

@end

