//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MajorViewController.h"

@class APIDataManager, NSMutableArray, NSTimer, UIButton, UIScrollView;

@interface lookBarCode : MajorViewController
{
    float _currentBrightness;
    int _viewType;
    NSMutableArray *_strBarCodeArray;
    NSMutableArray *_strTitleArray;
    UIScrollView *_scrollView;
    UIButton *_btnRight;
    APIDataManager *_dataManager;
    long long _qrCodeCreateTime;
    NSTimer *_timer;
}

@property(nonatomic) int viewType; // @synthesize viewType=_viewType;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) long long qrCodeCreateTime; // @synthesize qrCodeCreateTime=_qrCodeCreateTime;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
@property(nonatomic) float currentBrightness; // @synthesize currentBrightness=_currentBrightness;
@property(retain, nonatomic) UIButton *btnRight; // @synthesize btnRight=_btnRight;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(retain, nonatomic) NSMutableArray *strTitleArray; // @synthesize strTitleArray=_strTitleArray;
@property(retain, nonatomic) NSMutableArray *strBarCodeArray; // @synthesize strBarCodeArray=_strBarCodeArray;
- (void)btnRight:(id)arg1;
- (void)countTimer;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

