//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCViewController.h"

#import "CLLocationManagerDelegate.h"
#import "MKMapViewDelegate.h"

@class CLLocationManager, MKMapView, NSMutableArray, NSString;

@interface MapViewController : HNCViewController <CLLocationManagerDelegate, MKMapViewDelegate>
{
    _Bool _isAlreadyDetectGPSLocation;
    MKMapView *_mapView;
    NSMutableArray *_mapAnnotationsArray;
    CLLocationManager *_locationManager;
}

@property(nonatomic) _Bool isAlreadyDetectGPSLocation; // @synthesize isAlreadyDetectGPSLocation=_isAlreadyDetectGPSLocation;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) NSMutableArray *mapAnnotationsArray; // @synthesize mapAnnotationsArray=_mapAnnotationsArray;
@property(retain, nonatomic) MKMapView *mapView; // @synthesize mapView=_mapView;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (void)loadMapAnnotationsAndUserLocationCoordinate:(struct CLLocationCoordinate2D)arg1;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

