//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCTableViewController.h"

@class NSArray, UILabel, UIView, WKWebView;

@interface MessageViewController : HNCTableViewController
{
    int _iMessageType;
    WKWebView *_webKitView;
    UIView *_logoutView;
    UILabel *_logoutMessageLabel;
    NSArray *_aryNotice;
    long long _iMessageIndex;
}

@property(nonatomic) long long iMessageIndex; // @synthesize iMessageIndex=_iMessageIndex;
@property(nonatomic) int iMessageType; // @synthesize iMessageType=_iMessageType;
@property(retain, nonatomic) NSArray *aryNotice; // @synthesize aryNotice=_aryNotice;
@property(retain, nonatomic) UILabel *logoutMessageLabel; // @synthesize logoutMessageLabel=_logoutMessageLabel;
@property(retain, nonatomic) UIView *logoutView; // @synthesize logoutView=_logoutView;
@property(retain, nonatomic) WKWebView *webKitView; // @synthesize webKitView=_webKitView;
- (void)backDecisionEvent;
- (void)tableFootViewButtonClickEvent:(id)arg1;
- (void)changeTableFootViewButtonStyle;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

