//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewController.h"

#import "UIAlertViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSMutableArray, NSString;

@interface MMBLibraryTableViewController : UITableViewController <UIAlertViewDelegate, UITableViewDataSource, UITableViewDelegate>
{
    int iRightButtonItemType;
    int iLeftButtonItemType;
    _Bool isWebServiceRunning;
    NSMutableArray *mtaList;
}

@property(retain, nonatomic) NSMutableArray *mtaList; // @synthesize mtaList;
@property(nonatomic) _Bool isWebServiceRunning; // @synthesize isWebServiceRunning;
@property(nonatomic) int iLeftButtonItemType; // @synthesize iLeftButtonItemType;
@property(nonatomic) int iRightButtonItemType; // @synthesize iRightButtonItemType;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)resetLeftButtonItem:(int)arg1;
- (void)resetRightButtonItem:(int)arg1;
- (void)keyboardDidShow:(id)arg1;
- (void)goHome;
- (void)doLogout;
- (void)doAdd;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

