//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCWebKitViewController.h"

#import "CLLocationManagerDelegate.h"
#import "InspectionCertificateDelegate.h"

@class CLLocationManager, NSString, UIButton;

@interface MobileBankViewController : HNCWebKitViewController <CLLocationManagerDelegate, InspectionCertificateDelegate>
{
    _Bool _isGetChangeAuthorizationStatus;
    _Bool _isAlreadyDetectGPSLocation;
    _Bool _isRecordGoogleAnalyzeAndBigDataLocation;
    _Bool _isShaking;
    _Bool _isWebControlLoadingPag;
    _Bool _isWebCallShowLoadingPage;
    NSString *_moneyDJFundID;
    UIButton *_notShowCheckBox;
    NSString *_detectType;
    NSString *_detectGPSFuctionWfid;
    CLLocationManager *_locationManager;
}

@property(nonatomic) _Bool isWebCallShowLoadingPage; // @synthesize isWebCallShowLoadingPage=_isWebCallShowLoadingPage;
@property(nonatomic) _Bool isWebControlLoadingPag; // @synthesize isWebControlLoadingPag=_isWebControlLoadingPag;
@property(nonatomic) _Bool isShaking; // @synthesize isShaking=_isShaking;
@property(nonatomic) _Bool isRecordGoogleAnalyzeAndBigDataLocation; // @synthesize isRecordGoogleAnalyzeAndBigDataLocation=_isRecordGoogleAnalyzeAndBigDataLocation;
@property(nonatomic) _Bool isAlreadyDetectGPSLocation; // @synthesize isAlreadyDetectGPSLocation=_isAlreadyDetectGPSLocation;
@property(nonatomic) _Bool isGetChangeAuthorizationStatus; // @synthesize isGetChangeAuthorizationStatus=_isGetChangeAuthorizationStatus;
@property(retain, nonatomic) CLLocationManager *locationManager; // @synthesize locationManager=_locationManager;
@property(retain, nonatomic) NSString *detectGPSFuctionWfid; // @synthesize detectGPSFuctionWfid=_detectGPSFuctionWfid;
@property(retain, nonatomic) NSString *detectType; // @synthesize detectType=_detectType;
@property(retain, nonatomic) UIButton *notShowCheckBox; // @synthesize notShowCheckBox=_notShowCheckBox;
@property(retain, nonatomic) NSString *moneyDJFundID; // @synthesize moneyDJFundID=_moneyDJFundID;
- (void)handleCAResponseFailure:(id)arg1 WithMessage:(id)arg2;
- (_Bool)checkWhiteListURL:(id)arg1;
- (void)delayEnableViewAnimations:(id)arg1;
- (_Bool)saveDataToCalendarWithEKEventStore:(id)arg1 title:(id)arg2 notes:(id)arg3 location:(id)arg4 startDate:(id)arg5 endDate:(id)arg6;
- (id)formatStringToDate:(id)arg1;
- (void)addSystemCalendarWithTitle:(id)arg1 startDate:(id)arg2 endDate:(id)arg3;
- (void)detectGPSStatus:(id)arg1;
- (void)motionEnded:(long long)arg1 withEvent:(id)arg2;
- (void)motionBegan:(long long)arg1 withEvent:(id)arg2;
- (void)detectShakeStatus:(id)arg1;
- (void)receiveKeypascoCallbackWithResult:(id)arg1;
- (void)buttonClickEvent:(id)arg1;
- (void)showPrivatePushBindingAlertView;
- (void)locationManager:(id)arg1 didFailWithError:(id)arg2;
- (void)locationManager:(id)arg1 didUpdateLocations:(id)arg2;
- (void)locationManager:(id)arg1 didChangeAuthorizationStatus:(int)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)WebServiceObject:(id)arg1 didCompletePH00EWithHeader:(id)arg2 withPH00EResponseBody:(id)arg3;
- (void)WebServiceObject:(id)arg1 didCompletePH00CWithHeader:(id)arg2 withPH00CResponseBody:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (void)webView:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)didReceiveMemoryWarning;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

