//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface MTKUtility : NSObject
{
}

+ (id)decryptWithData:(id)arg1 withAESKey:(id)arg2;
+ (id)decryptWithData:(id)arg1;
+ (id)encryptWithData:(id)arg1 withAESKey:(id)arg2;
+ (id)encryptWithData:(id)arg1;
+ (id)getAESKey:(id)arg1;

@end

