//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class UIImageView, UILabel, UIView;

@interface MyppwordSettingViewControllerCell : UITableViewCell
{
    UIImageView *_imgTitle;
    UIImageView *_img;
    UIView *_lineView;
}

@property(retain, nonatomic) UIView *lineView; // @synthesize lineView=_lineView;
@property(retain, nonatomic) UIImageView *img; // @synthesize img=_img;
@property(retain, nonatomic) UIImageView *imgTitle; // @synthesize imgTitle=_imgTitle;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

// Remaining properties
@property(retain, nonatomic) UILabel *textLabel;

@end

