//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MajorViewController.h"

#import "UIPickerViewDataSource.h"
#import "UIPickerViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"
#import "UITextFieldDelegate.h"

@class APIDataManager, BonusdetailsData, NSMutableArray, NSNumber, NSString, UIDatePicker, UIPickerView, UITableView, UITextField, UIToolbar, UIView;

@interface MytwordRecordViewController : MajorViewController <UITextFieldDelegate, UIPickerViewDelegate, UIPickerViewDataSource, UITableViewDataSource, UITableViewDelegate>
{
    APIDataManager *_dataManager;
    UIView *_topView;
    UIView *_contentView;
    UIView *_customView;
    UIView *_blankView;
    UIView *_blockView;
    UIView *_dateView;
    NSMutableArray *_timeIntervalButtons;
    NSMutableArray *_arrayMyaword;
    NSMutableArray *_arrayTmList;
    UIPickerView *_transactionStatusPickerView;
    UIToolbar *_toolBar;
    UITextField *_txtTransactionStatus;
    UITextField *_txtBeginDate;
    UITextField *_txtEndDate;
    UIDatePicker *_startDatePicker;
    UIDatePicker *_endDatePicker;
    UITableView *_transactionRecordTableView;
    NSNumber *_accId;
    NSString *_accType;
    NSString *_type;
    NSNumber *_page;
    NSString *_txtTransactionNo;
    NSString *_back;
    NSString *_startDate;
    NSString *_endDate;
    BonusdetailsData *_bonusdetailsData;
}

- (void).cxx_destruct;
@property(nonatomic) __weak BonusdetailsData *bonusdetailsData; // @synthesize bonusdetailsData=_bonusdetailsData;
@property(retain, nonatomic) NSString *endDate; // @synthesize endDate=_endDate;
@property(retain, nonatomic) NSString *startDate; // @synthesize startDate=_startDate;
@property(retain, nonatomic) NSString *back; // @synthesize back=_back;
@property(retain, nonatomic) NSString *txtTransactionNo; // @synthesize txtTransactionNo=_txtTransactionNo;
@property(retain, nonatomic) NSNumber *page; // @synthesize page=_page;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *accType; // @synthesize accType=_accType;
@property(retain, nonatomic) NSNumber *accId; // @synthesize accId=_accId;
@property(retain, nonatomic) UITableView *transactionRecordTableView; // @synthesize transactionRecordTableView=_transactionRecordTableView;
@property(retain, nonatomic) UIDatePicker *endDatePicker; // @synthesize endDatePicker=_endDatePicker;
@property(retain, nonatomic) UIDatePicker *startDatePicker; // @synthesize startDatePicker=_startDatePicker;
@property(retain, nonatomic) UITextField *txtEndDate; // @synthesize txtEndDate=_txtEndDate;
@property(retain, nonatomic) UITextField *txtBeginDate; // @synthesize txtBeginDate=_txtBeginDate;
@property(retain, nonatomic) UITextField *txtTransactionStatus; // @synthesize txtTransactionStatus=_txtTransactionStatus;
@property(retain, nonatomic) UIToolbar *toolBar; // @synthesize toolBar=_toolBar;
@property(retain, nonatomic) UIPickerView *transactionStatusPickerView; // @synthesize transactionStatusPickerView=_transactionStatusPickerView;
@property(retain, nonatomic) NSMutableArray *arrayTmList; // @synthesize arrayTmList=_arrayTmList;
@property(retain, nonatomic) NSMutableArray *arrayMyaword; // @synthesize arrayMyaword=_arrayMyaword;
@property(retain, nonatomic) NSMutableArray *timeIntervalButtons; // @synthesize timeIntervalButtons=_timeIntervalButtons;
@property(retain, nonatomic) UIView *dateView; // @synthesize dateView=_dateView;
@property(retain, nonatomic) UIView *blockView; // @synthesize blockView=_blockView;
@property(retain, nonatomic) UIView *blankView; // @synthesize blankView=_blankView;
@property(retain, nonatomic) UIView *customView; // @synthesize customView=_customView;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(retain, nonatomic) UIView *topView; // @synthesize topView=_topView;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
- (void)system_maintenance:(id)arg1;
- (void)getTransaction;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)endDateChanged:(id)arg1;
- (void)startDateChanged:(id)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (id)pickerView:(id)arg1 viewForRow:(long long)arg2 forComponent:(long long)arg3 reusingView:(id)arg4;
- (void)pickerView:(id)arg1 didSelectRow:(long long)arg2 inComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)btnConfirmDateClick:(id)arg1;
- (void)pickerDone:(id)arg1;
- (void)pickerClean:(id)arg1;
- (void)onTypeButtonValueChanged:(id)arg1;
- (void)createCustomView;
- (void)createTransactionView;
- (void)createContentView;
- (void)createPickerView;
- (void)createTypeButtons;
- (void)didGetTransactionFailed:(id)arg1;
- (void)didGetTransactionSuccess:(id)arg1;
- (void)didGetMemberAccCardFailed:(id)arg1;
- (void)didGetMemberAccCardSuccess:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

