//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface NodeEntity : NSObject
{
    NSString *_mediaType;
    NSString *_channel;
    NSString *_subSysCode;
    NSString *_contactID;
    NSString *_actionType;
    NSString *_personalID;
    NSDictionary *_attachData;
}

@property(retain, nonatomic) NSDictionary *attachData; // @synthesize attachData=_attachData;
@property(retain, nonatomic) NSString *personalID; // @synthesize personalID=_personalID;
@property(retain, nonatomic) NSString *actionType; // @synthesize actionType=_actionType;
@property(retain, nonatomic) NSString *contactID; // @synthesize contactID=_contactID;
@property(retain, nonatomic) NSString *subSysCode; // @synthesize subSysCode=_subSysCode;
@property(retain, nonatomic) NSString *channel; // @synthesize channel=_channel;
@property(retain, nonatomic) NSString *mediaType; // @synthesize mediaType=_mediaType;

@end

