//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (MMBExtensions)
- (id)md5;
- (id)base64Encoding;
- (id)AES256DecryptWithKey:(id)arg1;
- (id)AES256EncryptWithKey:(id)arg1;
- (id)AES128DecryptWithKey:(id)arg1 withIV:(unsigned int)arg2;
- (id)AES128DecryptWithKey:(id)arg1;
- (id)AES128EncryptWithKey:(id)arg1 withIV:(unsigned int)arg2;
- (id)AES128EncryptWithKey:(id)arg1;
@end

