//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSString.h"

#import "JavaIoSerializable.h"
#import "JavaLangCharSequence.h"
#import "JavaLangComparable.h"

@interface NSString (JavaString) <JavaIoSerializable, JavaLangComparable, JavaLangCharSequence>
+ (struct J2ObjcClassInfo *)__metadata;
+ (id)formatWithJavaUtilLocale:(id)arg1 withNSString:(id)arg2 withNSObjectArray:(id)arg3;
+ (id)formatWithNSString:(id)arg1 withNSObjectArray:(id)arg2;
+ (id)stringWithInts:(id)arg1 offset:(int)arg2 length:(int)arg3;
+ (id)stringWithBytes:(id)arg1 offset:(int)arg2 length:(int)arg3 encoding:(unsigned long long)arg4;
+ (id)stringWithBytes:(id)arg1 hibyte:(unsigned long long)arg2 offset:(unsigned long long)arg3 length:(unsigned long long)arg4;
+ (id)stringWithBytes:(id)arg1 offset:(int)arg2 length:(int)arg3 charset:(id)arg4;
+ (id)stringWithBytes:(id)arg1 offset:(int)arg2 length:(int)arg3 charsetName:(id)arg4;
+ (id)stringWithBytes:(id)arg1 offset:(int)arg2 length:(int)arg3;
+ (id)stringWithBytes:(id)arg1 hibyte:(int)arg2;
+ (id)stringWithBytes:(id)arg1 charset:(id)arg2;
+ (id)stringWithBytes:(id)arg1 charsetName:(id)arg2;
+ (id)stringWithBytes:(id)arg1;
+ (id)stringWithJavaLangStringBuilder:(id)arg1;
+ (id)stringWithJavaLangStringBuffer:(id)arg1;
+ (id)stringWithOffset:(int)arg1 length:(int)arg2 characters:(id)arg3;
+ (id)stringWithCharacters:(id)arg1 offset:(int)arg2 length:(int)arg3;
+ (id)stringWithCharacters:(id)arg1;
+ (id)valueOfLong:(long long)arg1;
+ (id)valueOfInt:(int)arg1;
+ (id)valueOfFloat:(float)arg1;
+ (id)valueOfDouble:(double)arg1;
+ (id)valueOfChars:(id)arg1 offset:(int)arg2 count:(int)arg3;
+ (id)valueOfChars:(id)arg1;
+ (id)valueOfChar:(unsigned short)arg1;
+ (id)valueOfBool:(_Bool)arg1;
+ (id)valueOf:(id)arg1;
- (unsigned long long)hash;
- (_Bool)contentEqualsStringBuffer:(id)arg1;
- (_Bool)contentEqualsCharSequence:(id)arg1;
- (_Bool)matches:(id)arg1;
- (int)offsetByCodePoints:(int)arg1 codePointOffset:(int)arg2;
- (int)codePointCount:(int)arg1 endIndex:(int)arg2;
- (int)codePointBefore:(int)arg1;
- (int)codePointAt:(int)arg1;
- (_Bool)contains:(id)arg1;
- (id)concat:(id)arg1;
- (id)intern;
- (_Bool)regionMatches:(_Bool)arg1 thisOffset:(int)arg2 aString:(id)arg3 otherOffset:(int)arg4 count:(int)arg5;
- (_Bool)regionMatches:(int)arg1 aString:(id)arg2 otherOffset:(int)arg3 count:(int)arg4;
- (id)uppercaseStringWithJRELocale:(id)arg1;
- (id)lowercaseStringWithJRELocale:(id)arg1;
- (_Bool)equalsIgnoreCase:(id)arg1;
- (id)split:(id)arg1 limit:(int)arg2;
- (id)split:(id)arg1;
- (id)trim;
- (_Bool)hasPrefix:(id)arg1 offset:(int)arg2;
- (void)getBytesWithSrcBegin:(int)arg1 withSrcEnd:(int)arg2 withDst:(id)arg3 withDstBegin:(int)arg4;
- (id)getBytesWithEncoding:(unsigned long long)arg1;
- (id)getBytesWithCharset:(id)arg1;
- (id)getBytesWithCharsetName:(id)arg1;
- (id)getBytes;
- (id)replaceFirst:(id)arg1 withReplacement:(id)arg2;
- (id)replaceAll:(id)arg1 withReplacement:(id)arg2;
- (id)replace:(id)arg1 withSequence:(id)arg2;
- (id)replace:(unsigned short)arg1 withChar:(unsigned short)arg2;
- (id)subSequenceFrom:(int)arg1 to:(int)arg2;
- (int)sequenceLength;
- (unsigned short)charAtWithInt:(int)arg1;
- (id)toCharArray;
- (int)lastIndexOfString:(id)arg1 fromIndex:(int)arg2;
- (int)lastIndexOfString:(id)arg1;
- (int)lastIndexOf:(int)arg1 fromIndex:(int)arg2;
- (int)lastIndexOf:(int)arg1;
- (_Bool)isEmpty;
- (int)indexOfString:(id)arg1 fromIndex:(int)arg2;
- (int)indexOfString:(id)arg1;
- (int)indexOf:(int)arg1 fromIndex:(int)arg2;
- (int)indexOf:(int)arg1;
- (id)substring:(int)arg1 endIndex:(int)arg2;
- (id)substring:(int)arg1;
- (int)compareToIgnoreCase:(id)arg1;
- (int)compareToWithId:(id)arg1;
- (void)getChars:(int)arg1 sourceEnd:(int)arg2 destination:(id)arg3 destinationBegin:(int)arg4;
@end

