//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVAudioPlayer, AVSpeechSynthesizer, NSString;

@interface OctonTTS : NSObject
{
    AVSpeechSynthesizer *synthesizer;
    AVAudioPlayer *player;
    NSString *playFileNeme;
    NSString *status;
}

@property(retain, nonatomic) NSString *status; // @synthesize status;
@property(retain, nonatomic) NSString *playFileNeme; // @synthesize playFileNeme;
@property(retain, nonatomic) AVAudioPlayer *player; // @synthesize player;
@property(retain, nonatomic) AVSpeechSynthesizer *synthesizer; // @synthesize synthesizer;
- (void)playerRelease;
- (void)stop;
- (id)TTS:(id)arg1;
- (id)init;

@end

