//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OctonSipChat : NSObject
{
    id <OctonSipChatDelegate> _delegate;
}

+ (void)sendDeviceInfo:(id)arg1;
+ (_Bool)getStatus;
+ (void)onMessageReceived:(struct _LinphoneChatMessage *)arg1;
+ (void)sendMessage:(id)arg1;
+ (void)OctonRobotSend:(id)arg1;
+ (void)chatAgentSend:(id)arg1 type:(id)arg2 showStatus:(_Bool)arg3;
+ (void)endChatAgent;
+ (void)startChatAgent:(id)arg1 IdentityID:(id)arg2 UserType:(id)arg3;
+ (void)intumitRobotSend:(id)arg1 showStatus:(_Bool)arg2;
+ (void)endIntumitRobot;
+ (void)startIntumitRobot;
+ (void)guestLogin;
+ (id)instance;
@property(retain, nonatomic) id <OctonSipChatDelegate> delegate; // @synthesize delegate=_delegate;
- (void)_performDelegateBlock:(CDUnknownBlockType)arg1;
- (id)init;

@end

