//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OctonSipUtils : NSObject
{
}

+ (id)HTMLEscapeString:(id)arg1;
+ (id)HTMLUnescapeString:(id)arg1;
+ (id)getParam:(id)arg1 value:(id)arg2;
+ (id)attachDataEntityToParams:(id)arg1;
+ (id)urlEncode:(id)arg1;
+ (id)toString:(id)arg1;
+ (id)dicToParams:(id)arg1;
+ (id)getBASE64:(id)arg1;
+ (id)getMD5:(id)arg1;
+ (id)getSHA1:(id)arg1;
+ (id)fixOrientation:(id)arg1;
+ (id)getFilePath:(id)arg1 fileName:(id)arg2;
+ (void)downloadFile:(id)arg1 fileName:(id)arg2 url:(id)arg3;
+ (_Bool)checkFile:(id)arg1 fileName:(id)arg2;
+ (float)cpu_usage;
+ (id)dataFromHexString:(id)arg1;
+ (void)alertMessage:(id)arg1;
+ (id)toArrayOrNSDictionary:(id)arg1;

@end

