//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OctonDES : NSObject
{
    _Bool isInit_;
    id <JavaUtilList> key1L_;
    int key1LSize_;
    id <JavaUtilList> key2L_;
    int key2LSize_;
    id <JavaUtilList> key3L_;
    int key3LSize_;
}

+ (const struct J2ObjcClassInfo *)__metadata;
+ (id)getInstance;
- (void)copyAllFieldsTo:(id)arg1;
- (void)dealloc;
- (id)xor__WithIntArray:(id)arg1 withIntArray:(id)arg2;
- (id)strToBtWithNSString:(id)arg1;
- (id)sBoxPermuteWithIntArray:(id)arg1;
- (id)pPermuteWithIntArray:(id)arg1;
- (id)initPermuteWithIntArray:(id)arg1;
- (void)init__WithNSString:(id)arg1 withNSString:(id)arg2 withNSString:(id)arg3;
- (id)hexToBt64WithNSString:(id)arg1;
- (id)hexToBt4WithNSString:(id)arg1;
- (id)getKeyBytesWithNSString:(id)arg1;
- (id)getBoxBinaryWithInt:(int)arg1;
- (id)generateKeysWithIntArray:(id)arg1;
- (id)finallyPermuteWithIntArray:(id)arg1;
- (id)expandPermuteWithIntArray:(id)arg1;
- (id)encryptWithNSString:(id)arg1;
- (id)encWithIntArray:(id)arg1 withIntArray:(id)arg2;
- (id)decryptWithNSString:(id)arg1;
- (id)decWithIntArray:(id)arg1 withIntArray:(id)arg2;
- (id)byteToStringWithIntArray:(id)arg1;
- (id)bt64ToHexWithIntArray:(id)arg1;
- (id)bt4ToHexWithNSString:(id)arg1;
- (id)init;

@end

