//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OctonSipLicense : NSObject
{
}

+ (id)sendVerifyLog:(id)arg1;
+ (id)sendNodeLog:(id)arg1;
+ (id)sendAttachData:(id)arg1;
+ (id)releaseLicense:(id)arg1 Identifier:(id)arg2;
+ (_Bool)checkLicense;
+ (id)setLicense:(id)arg1;
+ (id)getLicenseInfo:(id)arg1;
+ (id)getLicense:(id)arg1 Identifier:(id)arg2 type:(id)arg3;

@end

