//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface OctonSipSDK : NSObject
{
}

+ (void)reset;
+ (void)fillDefaultValues;
+ (void)enableSpeaker:(_Bool)arg1;
+ (void)enableVideo:(_Bool)arg1 display_enabled:(_Bool)arg2;
+ (void)setPreviewWindow:(id)arg1;
+ (void)setVideoWindow:(id)arg1;
+ (void)call:(id)arg1 displayName:(id)arg2 userData:(id)arg3;
+ (void)toCall:(id)arg1;
+ (void)clearProxyConfig;
+ (void)setDefaultSettings:(struct _LinphoneProxyConfig *)arg1;
+ (id)loginSipServer:(id)arg1;

@end

