//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MajorViewController.h"

#import "WKNavigationDelegate.h"

@class APIDataManager, NSString, WKWebView;

@interface OrderMealViewController : MajorViewController <WKNavigationDelegate>
{
    APIDataManager *_dataManager;
    WKWebView *_webKitView;
    long long _actionType;
    NSString *_rtnCode;
    NSString *_rtnMsg;
    NSString *_mobile_no;
    NSString *_mm_id;
    NSString *_merchantNos;
    NSString *_testurl;
    NSString *_orderNo;
    NSString *_amt;
    NSString *_merchantNo;
    NSString *_disCntAmt;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *disCntAmt; // @synthesize disCntAmt=_disCntAmt;
@property(retain, nonatomic) NSString *merchantNo; // @synthesize merchantNo=_merchantNo;
@property(retain, nonatomic) NSString *amt; // @synthesize amt=_amt;
@property(retain, nonatomic) NSString *orderNo; // @synthesize orderNo=_orderNo;
@property(retain, nonatomic) NSString *testurl; // @synthesize testurl=_testurl;
@property(retain, nonatomic) NSString *merchantNos; // @synthesize merchantNos=_merchantNos;
@property(retain, nonatomic) NSString *mm_id; // @synthesize mm_id=_mm_id;
@property(retain, nonatomic) NSString *mobile_no; // @synthesize mobile_no=_mobile_no;
@property(retain, nonatomic) NSString *rtnMsg; // @synthesize rtnMsg=_rtnMsg;
@property(retain, nonatomic) NSString *rtnCode; // @synthesize rtnCode=_rtnCode;
@property(nonatomic) long long actionType; // @synthesize actionType=_actionType;
@property(retain, nonatomic) WKWebView *webKitView; // @synthesize webKitView=_webKitView;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)system_maintenance:(id)arg1;
- (void)callWhenOrderMealFailed:(id)arg1;
- (void)callWhenOrderMealSuccess:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

