//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCTableViewController.h"

@class NSLayoutConstraint, NSMutableArray, NSString, NSTimer, UIButton, UIImageView;

@interface PushMsgViewController : HNCTableViewController
{
    _Bool _isReceivePushNotFromForeground;
    _Bool _isDeleteMode;
    _Bool _isNotBackPushMsgViewController;
    UIImageView *_funcImageView;
    UIImageView *_unreadPublicMessagesSymbolView;
    UIImageView *_unreadPrivateMessagesSymbolView;
    UIButton *_editMessagesButton;
    NSLayoutConstraint *_pushMsgListHeightConstraint;
    NSString *_receivePushMessageType;
    NSString *_receivePushMessageBoxId;
    NSTimer *_countdownCalculateClickNavigationBarTitleTimesTimer;
    NSMutableArray *_publicArray;
    NSMutableArray *_privateArray;
    NSMutableArray *_deleteMessagesArray;
    long long _clickNavigationBarTitleTimes;
    long long _funcInx;
}

@property(nonatomic) _Bool isNotBackPushMsgViewController; // @synthesize isNotBackPushMsgViewController=_isNotBackPushMsgViewController;
@property(nonatomic) _Bool isDeleteMode; // @synthesize isDeleteMode=_isDeleteMode;
@property(nonatomic) long long funcInx; // @synthesize funcInx=_funcInx;
@property(nonatomic) long long clickNavigationBarTitleTimes; // @synthesize clickNavigationBarTitleTimes=_clickNavigationBarTitleTimes;
@property(retain, nonatomic) NSMutableArray *deleteMessagesArray; // @synthesize deleteMessagesArray=_deleteMessagesArray;
@property(retain, nonatomic) NSMutableArray *privateArray; // @synthesize privateArray=_privateArray;
@property(retain, nonatomic) NSMutableArray *publicArray; // @synthesize publicArray=_publicArray;
@property(retain, nonatomic) NSTimer *countdownCalculateClickNavigationBarTitleTimesTimer; // @synthesize countdownCalculateClickNavigationBarTitleTimesTimer=_countdownCalculateClickNavigationBarTitleTimesTimer;
@property(nonatomic) _Bool isReceivePushNotFromForeground; // @synthesize isReceivePushNotFromForeground=_isReceivePushNotFromForeground;
@property(retain, nonatomic) NSString *receivePushMessageBoxId; // @synthesize receivePushMessageBoxId=_receivePushMessageBoxId;
@property(retain, nonatomic) NSString *receivePushMessageType; // @synthesize receivePushMessageType=_receivePushMessageType;
@property(retain, nonatomic) NSLayoutConstraint *pushMsgListHeightConstraint; // @synthesize pushMsgListHeightConstraint=_pushMsgListHeightConstraint;
@property(retain, nonatomic) UIButton *editMessagesButton; // @synthesize editMessagesButton=_editMessagesButton;
@property(retain, nonatomic) UIImageView *unreadPrivateMessagesSymbolView; // @synthesize unreadPrivateMessagesSymbolView=_unreadPrivateMessagesSymbolView;
@property(retain, nonatomic) UIImageView *unreadPublicMessagesSymbolView; // @synthesize unreadPublicMessagesSymbolView=_unreadPublicMessagesSymbolView;
@property(retain, nonatomic) UIImageView *funcImageView; // @synthesize funcImageView=_funcImageView;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)editMessagesButtonClickEvent:(id)arg1;
- (void)funcRight:(id)arg1;
- (void)funcLeft:(id)arg1;
- (_Bool)isShowUnreadMessagesPromptWithMessageArray:(id)arg1;
- (void)WebServiceObject:(id)arg1 didCompletePH00AWithHeader:(id)arg2 withPH00AResponseBody:(id)arg3;
- (void)WebServiceObject:(id)arg1 didCompletePH009WithHeader:(id)arg2 withPH009ResponseBody:(id)arg3;
- (void)WebServiceObject:(id)arg1 didCompletePH004WithHeader:(id)arg2 withPH004ResponseBody:(id)arg3;
- (void)WebServiceObject:(id)arg1 didCompletePH001WithHeader:(id)arg2 withPH001ResponseBody:(id)arg3;
- (void)WebServiceObject:(id)arg1 didCompletePH000WithHeader:(id)arg2 withPH000ResponseBody:(id)arg3;
- (void)doPH004:(id)arg1;
- (void)timeoutCountdownCalculateEvent;
- (void)buttonClickEvent:(id)arg1;
- (void)backButtonClickEvent:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)dealloc;
- (void)updateViewConstraints;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

