//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCViewController.h"

#import "UITextFieldDelegate.h"

@class NSArray, NSString, UIButton, UIImage, UIImageView, UILabel, UITextField;

@interface QRCodeCollectionPictureViewController : HNCViewController <UITextFieldDelegate>
{
    UIButton *_backScanViewButton;
    UITextField *_qrCodeNicknameField;
    UITextField *_collectionAmountField;
    UIButton *_immediateShareButton;
    UIButton *_accValueButton;
    UILabel *_expiredTimeLabel;
    UIImageView *_qrCodeGenerationPictureImageView;
    NSArray *_accountArray;
    NSString *_selectBankCode;
    NSString *_selectAccountNumber;
    NSString *_selectCurrency;
    NSString *_twqrpTransferStr;
    NSString *_encodeTwqrpTransferStr;
    UIImage *_shareQRCodeImage;
    struct CGRect _qrCodeCollectionPictureViewFrame;
}

@property(nonatomic) struct CGRect qrCodeCollectionPictureViewFrame; // @synthesize qrCodeCollectionPictureViewFrame=_qrCodeCollectionPictureViewFrame;
@property(retain, nonatomic) UIImage *shareQRCodeImage; // @synthesize shareQRCodeImage=_shareQRCodeImage;
@property(retain, nonatomic) NSString *encodeTwqrpTransferStr; // @synthesize encodeTwqrpTransferStr=_encodeTwqrpTransferStr;
@property(retain, nonatomic) NSString *twqrpTransferStr; // @synthesize twqrpTransferStr=_twqrpTransferStr;
@property(retain, nonatomic) NSString *selectCurrency; // @synthesize selectCurrency=_selectCurrency;
@property(retain, nonatomic) NSString *selectAccountNumber; // @synthesize selectAccountNumber=_selectAccountNumber;
@property(retain, nonatomic) NSString *selectBankCode; // @synthesize selectBankCode=_selectBankCode;
@property(retain, nonatomic) NSArray *accountArray; // @synthesize accountArray=_accountArray;
@property(retain, nonatomic) UIImageView *qrCodeGenerationPictureImageView; // @synthesize qrCodeGenerationPictureImageView=_qrCodeGenerationPictureImageView;
@property(retain, nonatomic) UILabel *expiredTimeLabel; // @synthesize expiredTimeLabel=_expiredTimeLabel;
@property(retain, nonatomic) UIButton *accValueButton; // @synthesize accValueButton=_accValueButton;
@property(retain, nonatomic) UIButton *immediateShareButton; // @synthesize immediateShareButton=_immediateShareButton;
@property(retain, nonatomic) UITextField *collectionAmountField; // @synthesize collectionAmountField=_collectionAmountField;
@property(retain, nonatomic) UITextField *qrCodeNicknameField; // @synthesize qrCodeNicknameField=_qrCodeNicknameField;
@property(retain, nonatomic) UIButton *backScanViewButton; // @synthesize backScanViewButton=_backScanViewButton;
- (id)drawTextOnShareQRCodePictureImage:(id)arg1 withTopTextStr:(id)arg2 withBottomTextStr:(id)arg3;
- (id)generateShareQRCodePicture;
- (id)generateQRCodePictureWithContentStr:(id)arg1 imageSize:(struct CGSize)arg2 imagePadding:(double)arg3;
- (void)makeTwqrpTransferStrAndShowQRCodePicture;
- (void)mmbPickerViewBtnCancelClickEvent:(id)arg1;
- (void)mmbPickerViewBtnDoneClickEvent:(id)arg1;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (void)inputQRCodeNicknameOrCollectionAmountKeyboardWillHide:(id)arg1;
- (void)inputQRCodeNicknameOrCollectionAmountKeyboardWillShow:(id)arg1;
- (void)nickNamePadDoneClickEvent:(id)arg1;
- (void)numberPadDoneClickEvent:(id)arg1;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)textFieldTextDidChange:(id)arg1;
- (void)buttonClickEvent:(id)arg1;
- (void)WebServiceObject:(id)arg1 didCompleteCheckQRCodeP2PWithHeader:(id)arg2 withCheckQRCodeP2PResponseBody:(id)arg3;
- (void)WebServiceObject:(id)arg1 didCompleteGetUserAccountWithHeader:(id)arg2 withGetUserAccountResponseBody:(id)arg3;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

