//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCViewController.h"

#import "GesturePasswordViewDelegate.h"

@class LAContext, NSLayoutConstraint, NSString, UILabel, UIView;

@interface QuickLoginGestureSettingViewController : HNCViewController <GesturePasswordViewDelegate>
{
    int _gestureSettingType;
    NSLayoutConstraint *_stepViewHeightConstraint;
    UILabel *_gestureSettingTitleLabel;
    UIView *_gestureAreaView;
    NSString *_authenticationID;
    NSString *_UUID;
    NSString *_identityID;
    NSString *_nickName;
    LAContext *_context;
    NSString *_gestureConnectPosition;
    NSString *_verificationIdentityType;
    long long _gestureSettingAgainErrorCount;
}

@property(nonatomic) long long gestureSettingAgainErrorCount; // @synthesize gestureSettingAgainErrorCount=_gestureSettingAgainErrorCount;
@property(retain, nonatomic) NSString *verificationIdentityType; // @synthesize verificationIdentityType=_verificationIdentityType;
@property(retain, nonatomic) NSString *gestureConnectPosition; // @synthesize gestureConnectPosition=_gestureConnectPosition;
@property(retain, nonatomic) LAContext *context; // @synthesize context=_context;
@property(nonatomic) int gestureSettingType; // @synthesize gestureSettingType=_gestureSettingType;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(retain, nonatomic) NSString *identityID; // @synthesize identityID=_identityID;
@property(retain, nonatomic) NSString *UUID; // @synthesize UUID=_UUID;
@property(retain, nonatomic) NSString *authenticationID; // @synthesize authenticationID=_authenticationID;
@property(retain, nonatomic) UIView *gestureAreaView; // @synthesize gestureAreaView=_gestureAreaView;
@property(retain, nonatomic) UILabel *gestureSettingTitleLabel; // @synthesize gestureSettingTitleLabel=_gestureSettingTitleLabel;
@property(retain, nonatomic) NSLayoutConstraint *stepViewHeightConstraint; // @synthesize stepViewHeightConstraint=_stepViewHeightConstraint;
- (void)WebServiceObject:(id)arg1 didCompleteQuickLoginSettingWithHeader:(id)arg2 withQuickLoginSettingResponseBody:(id)arg3;
- (void)sendQuickLoginSettingTelegramWithType:(id)arg1;
- (void)showFingerprintOpenAlertView;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)gesturePasswordView:(id)arg1 withIsCorrectPassword:(_Bool)arg2 withGetPassword:(id)arg3;
- (void)gesturePasswordView:(id)arg1 withFirstTimePassword:(id)arg2;
- (void)backButtonClickEvent:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)dealloc;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

