//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCViewController.h"

@class NSLayoutConstraint, UIImageView, UILabel;

@interface QuickLoginCompleteViewController : HNCViewController
{
    int _completeType;
    NSLayoutConstraint *_stepViewHeightConstraint;
    UILabel *_completeSubTitleLabel;
    UILabel *_completeContentLabel;
    UIImageView *_completeOrCancelImageView;
}

@property(nonatomic) int completeType; // @synthesize completeType=_completeType;
@property(retain, nonatomic) UIImageView *completeOrCancelImageView; // @synthesize completeOrCancelImageView=_completeOrCancelImageView;
@property(retain, nonatomic) UILabel *completeContentLabel; // @synthesize completeContentLabel=_completeContentLabel;
@property(retain, nonatomic) UILabel *completeSubTitleLabel; // @synthesize completeSubTitleLabel=_completeSubTitleLabel;
@property(retain, nonatomic) NSLayoutConstraint *stepViewHeightConstraint; // @synthesize stepViewHeightConstraint=_stepViewHeightConstraint;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)completeButtonClickEvent:(id)arg1;
- (void)backButtonClickEvent:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewDidLoad;

@end

