//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCViewController.h"

@class NSString, UIButton, UIView, WKWebView;

@interface QuickLoginClauseViewController : HNCViewController
{
    UIButton *_clauseCheckBox;
    UIView *_clauseContentContainerView;
    NSString *_clauseContent;
    NSString *_authenticationID;
    NSString *_UUID;
    NSString *_identityID;
    NSString *_nickName;
    WKWebView *_clauseContentView;
}

@property(retain, nonatomic) WKWebView *clauseContentView; // @synthesize clauseContentView=_clauseContentView;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(retain, nonatomic) NSString *identityID; // @synthesize identityID=_identityID;
@property(retain, nonatomic) NSString *UUID; // @synthesize UUID=_UUID;
@property(retain, nonatomic) NSString *authenticationID; // @synthesize authenticationID=_authenticationID;
@property(retain, nonatomic) NSString *clauseContent; // @synthesize clauseContent=_clauseContent;
@property(retain, nonatomic) UIView *clauseContentContainerView; // @synthesize clauseContentContainerView=_clauseContentContainerView;
@property(retain, nonatomic) UIButton *clauseCheckBox; // @synthesize clauseCheckBox=_clauseCheckBox;
- (void)buttonClickEvent:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)dealloc;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

