//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCViewController.h"

@class NSLayoutConstraint, NSString, UIView;

@interface QuickLoginFingerprintOpenViewController : HNCViewController
{
    int _fingerprintOpenType;
    UIView *_fpOpenAreaView;
    NSLayoutConstraint *_fpOpenAlertViewYConstraint;
    NSString *_authenticationID;
    NSString *_UUID;
    NSString *_identityID;
    NSString *_nickName;
    NSString *_gestureConnectPosition;
    NSString *_verificationIdentityType;
}

@property(retain, nonatomic) NSString *verificationIdentityType; // @synthesize verificationIdentityType=_verificationIdentityType;
@property(nonatomic) int fingerprintOpenType; // @synthesize fingerprintOpenType=_fingerprintOpenType;
@property(retain, nonatomic) NSString *gestureConnectPosition; // @synthesize gestureConnectPosition=_gestureConnectPosition;
@property(retain, nonatomic) NSString *nickName; // @synthesize nickName=_nickName;
@property(retain, nonatomic) NSString *identityID; // @synthesize identityID=_identityID;
@property(retain, nonatomic) NSString *UUID; // @synthesize UUID=_UUID;
@property(retain, nonatomic) NSString *authenticationID; // @synthesize authenticationID=_authenticationID;
@property(retain, nonatomic) NSLayoutConstraint *fpOpenAlertViewYConstraint; // @synthesize fpOpenAlertViewYConstraint=_fpOpenAlertViewYConstraint;
@property(retain, nonatomic) UIView *fpOpenAreaView; // @synthesize fpOpenAreaView=_fpOpenAreaView;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)WebServiceObject:(id)arg1 didCompleteQuickLoginSettingWithHeader:(id)arg2 withQuickLoginSettingResponseBody:(id)arg3;
- (void)sendQuickLoginSettingTelegramWithType:(id)arg1;
- (void)buttonClickEvent:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)dealloc;
- (void)viewDidLoad;

@end

