//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MajorViewController.h"

@class APIDataManager, NSNumber, NSString;

@interface RefundQRCodeViewController : MajorViewController
{
    NSNumber *_tmId;
    APIDataManager *_dataManager;
    NSString *_refundQrCode;
    NSString *_refundBarCode;
    NSString *_tmAmt;
    NSString *_tpOrderNo;
    NSString *_tmSellerName;
}

@property(retain, nonatomic) NSString *tmSellerName; // @synthesize tmSellerName=_tmSellerName;
@property(retain, nonatomic) NSString *tpOrderNo; // @synthesize tpOrderNo=_tpOrderNo;
@property(retain, nonatomic) NSString *tmAmt; // @synthesize tmAmt=_tmAmt;
@property(retain, nonatomic) NSString *refundBarCode; // @synthesize refundBarCode=_refundBarCode;
@property(retain, nonatomic) NSString *refundQrCode; // @synthesize refundQrCode=_refundQrCode;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
@property(retain, nonatomic) NSNumber *tmId; // @synthesize tmId=_tmId;
- (void)system_maintenance:(id)arg1;
- (void)CREATEREFUND_FAILED:(id)arg1;
- (void)CREATEREFUND_SUCCESS:(id)arg1;
- (void)didReceiveMemoryWarning;
- (id)barCodeImageWithInfo:(id)arg1;
- (void)createView;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)backRecord;
- (void)viewDidLoad;

@end

