//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class APIDataManager, UILabel, WKWebView;

@interface RevealDescriptionView : UIView
{
    UILabel *_headerLabel;
    UIView *_revealDescriptionView;
    UIView *_bakeView;
    WKWebView *_wkWebView;
    APIDataManager *_dataManager;
    id <RevealDescriptionViewDeleaget> _delegate;
}

- (void).cxx_destruct;
@property(nonatomic) __weak id <RevealDescriptionViewDeleaget> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
@property(retain, nonatomic) WKWebView *wkWebView; // @synthesize wkWebView=_wkWebView;
@property(retain, nonatomic) UIView *bakeView; // @synthesize bakeView=_bakeView;
@property(retain, nonatomic) UIView *revealDescriptionView; // @synthesize revealDescriptionView=_revealDescriptionView;
@property(retain, nonatomic) UILabel *headerLabel; // @synthesize headerLabel=_headerLabel;
- (void)doneButton:(id)arg1;
- (void)initLabelText:(id)arg1;
- (void)initTextColor;
- (void)coustomInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;

@end

