//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSString;

@interface SBConstants : NSObject
{
    NSString *_hostURL;
    NSString *_staticResourceHostURL;
    NSDictionary *_serviceOptionInfos;
    NSDictionary *_fieldOptionInfos;
    NSMutableDictionary *_jsonObjectInfos;
}

+ (id)sharedConstants;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSMutableDictionary *jsonObjectInfos; // @synthesize jsonObjectInfos=_jsonObjectInfos;
@property(readonly, nonatomic) NSDictionary *fieldOptionInfos; // @synthesize fieldOptionInfos=_fieldOptionInfos;
@property(readonly, nonatomic) NSDictionary *serviceOptionInfos; // @synthesize serviceOptionInfos=_serviceOptionInfos;
@property(readonly, nonatomic) NSString *staticResourceHostURL; // @synthesize staticResourceHostURL=_staticResourceHostURL;
@property(readonly, nonatomic) NSString *hostURL; // @synthesize hostURL=_hostURL;
- (id)jsonObjectForFilename:(id)arg1;
- (id)init;

@end

