//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBBaseTableViewController.h"

#import "SBSelectFieldViewCellDelegate.h"
#import "SBSelectionTableViewControllerDelegate.h"
#import "SBWebFieldViewCellDelegate.h"

@class NSArray, NSMutableArray, NSMutableDictionary, NSString;

@interface SBFieldListViewController : SBBaseTableViewController <SBSelectionTableViewControllerDelegate, SBSelectFieldViewCellDelegate, SBWebFieldViewCellDelegate>
{
    _Bool _webFieldViewCellAlertShowing;
    NSString *_serviceOption;
    NSArray *_fieldOptionArray;
    NSMutableDictionary *_prevFieldOptionInfos;
    NSMutableDictionary *_currentFieldOptionInfos;
    NSMutableArray *_visibleFieldOptionArray;
    double _remainingDistributedHeight;
    double _minDistributedHeight;
}

+ (_Bool)itemSelectedWithItemValue:(id)arg1 fieldOptionDict:(id)arg2;
+ (id)sortedArrayForSelectedItemDictArray:(id)arg1 fieldOptionDict:(id)arg2;
+ (id)selectedItemDictArrayWithFieldOptionDict:(id)arg1;
- (void).cxx_destruct;
@property(readonly, nonatomic) double minDistributedHeight; // @synthesize minDistributedHeight=_minDistributedHeight;
@property(readonly, nonatomic) double remainingDistributedHeight; // @synthesize remainingDistributedHeight=_remainingDistributedHeight;
@property(retain, nonatomic) NSMutableArray *visibleFieldOptionArray; // @synthesize visibleFieldOptionArray=_visibleFieldOptionArray;
@property(nonatomic) _Bool webFieldViewCellAlertShowing; // @synthesize webFieldViewCellAlertShowing=_webFieldViewCellAlertShowing;
@property(readonly, nonatomic) NSMutableDictionary *currentFieldOptionInfos; // @synthesize currentFieldOptionInfos=_currentFieldOptionInfos;
@property(retain, nonatomic) NSMutableDictionary *prevFieldOptionInfos; // @synthesize prevFieldOptionInfos=_prevFieldOptionInfos;
@property(retain, nonatomic) NSArray *fieldOptionArray; // @synthesize fieldOptionArray=_fieldOptionArray;
@property(retain, nonatomic) NSString *serviceOption; // @synthesize serviceOption=_serviceOption;
- (void)webFieldViewCellDidFailLoading:(id)arg1 withError:(id)arg2;
- (void)selectFieldViewCellDidLongPress:(id)arg1;
- (void)selectFieldViewCellDidUpdate:(id)arg1;
- (void)selectFieldViewCellDidSelect:(id)arg1 itemName:(id)arg2 itemValue:(id)arg3;
- (void)selectionTableViewController:(id)arg1 didSelectPaths:(id)arg2;
- (_Bool)selectionTableViewController:(id)arg1 shouldSelectPath:(id)arg2 selectItem:(id)arg3;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)buttonFieldButtonClick:(id)arg1;
- (void)searchFieldButtonClick:(id)arg1;
- (void)checkboxFieldButtonClick:(id)arg1;
- (void)selectFieldButtonClick:(id)arg1;
- (void)addUserParameters:(id)arg1 fieldOptionKey:(id)arg2 fieldOptionDict:(id)arg3;
- (void)searchDidComplete:(id)arg1 fieldOptionDict:(id)arg2 returnDict:(id)arg3;
- (_Bool)checkUserInput:(id)arg1 errorMsgPointer:(id *)arg2;
- (_Bool)checkBasicTextFormat:(id)arg1 errorMsgPointer:(id *)arg2;
- (_Bool)checkUserInput;
- (void)showReservationSuccess:(id)arg1;
- (id)urlString:(id)arg1 withParametersDict:(id)arg2;
- (void)prefetchDidComplete:(id)arg1 fieldOptionDict:(id)arg2 returnDict:(id)arg3;
- (void)prefetchIfNeeded;
- (void)updateVisibleFieldOptionArray;
- (void)updateAllPropertiesBySelectedPaths;
- (double)topDistance;
- (void)customizedInitialize:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

