//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIControl.h"

@class UIImageView, UILabel;

@interface SBIconButton : UIControl
{
    UIImageView *_iconImageView;
    UILabel *_titleLabel;
    struct CGSize _iconSize;
}

- (void).cxx_destruct;
@property(nonatomic) struct CGSize iconSize; // @synthesize iconSize=_iconSize;
@property(readonly, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(readonly, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
- (void)layoutSubviews;
- (id)init;

@end

