//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBBaseViewController.h"

@interface SBPrefillViewController : SBBaseViewController
{
    _Bool _iconButtonProcessing;
}

@property(nonatomic) _Bool iconButtonProcessing; // @synthesize iconButtonProcessing=_iconButtonProcessing;
- (void)iconButtonClick:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)loadView;

@end

