//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBBaseTableViewController.h"

@class NSArray, NSString;

@interface SBQueryDetailViewController : SBBaseTableViewController
{
    _Bool _hidesCancelButton;
    NSString *_apptNo;
    NSArray *_fillInfoArray;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) _Bool hidesCancelButton; // @synthesize hidesCancelButton=_hidesCancelButton;
@property(retain, nonatomic) NSArray *fillInfoArray; // @synthesize fillInfoArray=_fillInfoArray;
@property(retain, nonatomic) NSString *apptNo; // @synthesize apptNo=_apptNo;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)cancelButtonClick:(id)arg1;
- (void)updateFillInfoArray;
- (void)didReceiveMemoryWarning;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

