//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSLayoutConstraint, UIImageView, UILabel;

@interface SBQueryDetailCancelViewCell : UITableViewCell
{
    UILabel *_apptNoLabel;
    UIImageView *_qrCodeImageView;
    NSLayoutConstraint *_cancelButtonHeightConstraint;
}

- (void).cxx_destruct;
@property(nonatomic) __weak NSLayoutConstraint *cancelButtonHeightConstraint; // @synthesize cancelButtonHeightConstraint=_cancelButtonHeightConstraint;
@property(nonatomic) __weak UIImageView *qrCodeImageView; // @synthesize qrCodeImageView=_qrCodeImageView;
@property(nonatomic) __weak UILabel *apptNoLabel; // @synthesize apptNoLabel=_apptNoLabel;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

