//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class NSMutableDictionary, NSString, UIButton, UILabel;

@interface SBSelectFieldViewCell : UITableViewCell
{
    id <SBSelectFieldViewCellDelegate> _delegate;
    NSString *_fieldOption;
    NSMutableDictionary *_fieldOptionInfo;
    UILabel *_titleLabel;
    UIButton *_valueButton;
}

- (void).cxx_destruct;
@property(nonatomic) __weak UIButton *valueButton; // @synthesize valueButton=_valueButton;
@property(nonatomic) __weak UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak NSMutableDictionary *fieldOptionInfo; // @synthesize fieldOptionInfo=_fieldOptionInfo;
@property(retain, nonatomic) NSString *fieldOption; // @synthesize fieldOption=_fieldOption;
@property(nonatomic) __weak id <SBSelectFieldViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)longPress:(id)arg1;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)awakeFromNib;

@end

