//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary, SBSelectionTableViewController;

@protocol SBSelectionTableViewControllerDelegate <NSObject>
- (void)selectionTableViewController:(SBSelectionTableViewController *)arg1 didSelectPaths:(NSArray *)arg2;
- (_Bool)selectionTableViewController:(SBSelectionTableViewController *)arg1 shouldSelectPath:(NSArray *)arg2 selectItem:(NSDictionary *)arg3;
@end

