//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SBBaseTableViewController.h"

@class NSArray;

@interface SBSettingViewController : SBBaseTableViewController
{
    NSArray *_cellTitleArray;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) NSArray *cellTitleArray; // @synthesize cellTitleArray=_cellTitleArray;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)enterQueryTicketViewController;
- (void)enterBindingViewController;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

