//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

#import "UIGestureRecognizerDelegate.h"
#import "WKNavigationDelegate.h"

@class NSMutableDictionary, NSString, UIActivityIndicatorView, UITapGestureRecognizer, WKWebView;

@interface SBWebFieldViewCell : UITableViewCell <WKNavigationDelegate, UIGestureRecognizerDelegate>
{
    id <SBWebFieldViewCellDelegate> _delegate;
    NSString *_fieldOption;
    NSMutableDictionary *_fieldOptionInfo;
    WKWebView *_webView;
    UIActivityIndicatorView *_indicatorView;
    UITapGestureRecognizer *_doubleTap;
}

- (void).cxx_destruct;
@property(readonly, nonatomic) UITapGestureRecognizer *doubleTap; // @synthesize doubleTap=_doubleTap;
@property(readonly, nonatomic) UIActivityIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(readonly, nonatomic) WKWebView *webView; // @synthesize webView=_webView;
@property(nonatomic) __weak NSMutableDictionary *fieldOptionInfo; // @synthesize fieldOptionInfo=_fieldOptionInfo;
@property(retain, nonatomic) NSString *fieldOption; // @synthesize fieldOption=_fieldOption;
@property(nonatomic) __weak id <SBWebFieldViewCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void)webView:(id)arg1 didFailProvisionalNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFailNavigation:(id)arg2 withError:(id)arg3;
- (void)webView:(id)arg1 didFinishNavigation:(id)arg2;
- (void)webView:(id)arg1 didCommitNavigation:(id)arg2;
- (void)webView:(id)arg1 didStartProvisionalNavigation:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)doubleTap:(id)arg1;
- (void)tryLoading;
- (void)setSelected:(_Bool)arg1 animated:(_Bool)arg2;
- (void)layoutSubviews;
- (void)awakeFromNib;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

