//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCViewController.h"

#import "AVCaptureMetadataOutputObjectsDelegate.h"

@class AVCaptureSession, AVCaptureVideoPreviewLayer, NSString, UIButton, UIImageView, UIView, WKWebView;

@interface ScanQRCodeViewController : HNCViewController <AVCaptureMetadataOutputObjectsDelegate>
{
    UIView *_qrCodeScanAreaView;
    UIImageView *_qrCodeScanFrameView;
    UIButton *_closeButton;
    NSString *_type;
    WKWebView *_webKitView;
    NSString *_sCallbackFunctionName;
    AVCaptureSession *_captureSession;
    AVCaptureVideoPreviewLayer *_captureVideoPreviewLayer;
}

@property(retain, nonatomic) AVCaptureVideoPreviewLayer *captureVideoPreviewLayer; // @synthesize captureVideoPreviewLayer=_captureVideoPreviewLayer;
@property(retain, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
@property(retain, nonatomic) NSString *sCallbackFunctionName; // @synthesize sCallbackFunctionName=_sCallbackFunctionName;
@property(retain, nonatomic) WKWebView *webKitView; // @synthesize webKitView=_webKitView;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) UIButton *closeButton; // @synthesize closeButton=_closeButton;
@property(retain, nonatomic) UIImageView *qrCodeScanFrameView; // @synthesize qrCodeScanFrameView=_qrCodeScanFrameView;
@property(retain, nonatomic) UIView *qrCodeScanAreaView; // @synthesize qrCodeScanAreaView=_qrCodeScanAreaView;
- (void)closeButtonClickEvent:(id)arg1;
- (void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3;
- (void)settingQRCodeScan;
- (void)didReceiveMemoryWarning;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

