//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MajorViewController.h"

#import "AVCaptureMetadataOutputObjectsDelegate.h"
#import "RevealDescriptionViewDeleaget.h"
#import "UIImagePickerControllerDelegate.h"
#import "UINavigationControllerDelegate.h"
#import "UIScrollViewDelegate.h"

@class APIDataManager, AVCaptureMetadataOutput, AVCaptureSession, AVCaptureVideoPreviewLayer, EWalletUtils, NSMutableArray, NSMutableDictionary, NSString, NSTimer, RevealDescriptionView, UIButton, UIImageView, UILabel, UIScrollView, UISwitch, UIView;

@interface ScanReceiveViewController : MajorViewController <RevealDescriptionViewDeleaget, AVCaptureMetadataOutputObjectsDelegate, UIScrollViewDelegate, UIImagePickerControllerDelegate, UINavigationControllerDelegate>
{
    _Bool _lightingType;
    _Bool _canscan;
    _Bool _paytax;
    _Bool _quickPay;
    int _viewType;
    int _timerCount;
    int _timerChange;
    int _treemin;
    float _version;
    float _currentBrightness;
    EWalletUtils *_ewallet;
    APIDataManager *_dataManager;
    AVCaptureSession *_captureSession;
    AVCaptureVideoPreviewLayer *_captureLayer;
    AVCaptureMetadataOutput *_captureMetadataOutput;
    UIButton *_btnRight;
    UIButton *_btnSwitchInScanView;
    UIButton *_btnSwitchInBarcodeView;
    UIButton *_btnPhoto;
    NSMutableArray *_strBarcodeArray;
    NSString *_strQRCode;
    NSString *_strPayType;
    NSString *_strPayId;
    UIView *_scanView;
    UIView *_barcodeView;
    NSString *_capturedBarcode;
    NSMutableArray *_CardArray;
    UIView *_navView;
    NSMutableDictionary *_dic;
    UIImageView *_scanImg;
    UIImageView *_lightingImg;
    NSTimer *_timer;
    NSTimer *_timer2;
    UIView *_cover;
    UILabel *_timerString;
    UILabel *_textlabel;
    NSTimer *_timer300;
    NSString *_touchID;
    NSString *_order;
    NSString *_orderWebsite;
    NSString *_acc;
    UIScrollView *_scrollView;
    NSString *_btnViewCodestr;
    NSMutableArray *_arrayKey;
    UIImageView *_imgScrollLeft;
    UIImageView *_imgScrollRight;
    long long _qrCodeCreateTime;
    UIImageView *_creditCardLogoImageView;
    UIImageView *_creditLogoImgView;
    UIView *_bottomView;
    UISwitch *_bonusSwitch;
    UILabel *_nPoint;
    UIImageView *_imgQRCode;
    UILabel *_btnViewString;
    UIButton *_paymentCode128Btn;
    UIView *_blockView;
    RevealDescriptionView *_descriptionView;
    NSString *_pBalance;
    NSString *_pRedeemState;
    NSString *_pIconPointDesc;
    NSString *_pIsQueryAgain;
    NSString *_errMsg;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *errMsg; // @synthesize errMsg=_errMsg;
@property(retain, nonatomic) NSString *pIsQueryAgain; // @synthesize pIsQueryAgain=_pIsQueryAgain;
@property(retain, nonatomic) NSString *pIconPointDesc; // @synthesize pIconPointDesc=_pIconPointDesc;
@property(retain, nonatomic) NSString *pRedeemState; // @synthesize pRedeemState=_pRedeemState;
@property(retain, nonatomic) NSString *pBalance; // @synthesize pBalance=_pBalance;
@property(retain, nonatomic) RevealDescriptionView *descriptionView; // @synthesize descriptionView=_descriptionView;
@property(retain, nonatomic) UIView *blockView; // @synthesize blockView=_blockView;
@property(retain, nonatomic) UIButton *paymentCode128Btn; // @synthesize paymentCode128Btn=_paymentCode128Btn;
@property(retain, nonatomic) UILabel *btnViewString; // @synthesize btnViewString=_btnViewString;
@property(retain, nonatomic) UIImageView *imgQRCode; // @synthesize imgQRCode=_imgQRCode;
@property(retain, nonatomic) UILabel *nPoint; // @synthesize nPoint=_nPoint;
@property(retain, nonatomic) UISwitch *bonusSwitch; // @synthesize bonusSwitch=_bonusSwitch;
@property(nonatomic) _Bool quickPay; // @synthesize quickPay=_quickPay;
@property(retain, nonatomic) UIView *bottomView; // @synthesize bottomView=_bottomView;
@property(retain, nonatomic) UIImageView *creditLogoImgView; // @synthesize creditLogoImgView=_creditLogoImgView;
@property(retain, nonatomic) UIImageView *creditCardLogoImageView; // @synthesize creditCardLogoImageView=_creditCardLogoImageView;
@property(nonatomic) long long qrCodeCreateTime; // @synthesize qrCodeCreateTime=_qrCodeCreateTime;
@property(retain, nonatomic) UIImageView *imgScrollRight; // @synthesize imgScrollRight=_imgScrollRight;
@property(retain, nonatomic) UIImageView *imgScrollLeft; // @synthesize imgScrollLeft=_imgScrollLeft;
@property(nonatomic) float currentBrightness; // @synthesize currentBrightness=_currentBrightness;
@property(retain, nonatomic) NSMutableArray *arrayKey; // @synthesize arrayKey=_arrayKey;
@property(retain, nonatomic) NSString *btnViewCodestr; // @synthesize btnViewCodestr=_btnViewCodestr;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) _Bool paytax; // @synthesize paytax=_paytax;
@property(nonatomic) _Bool canscan; // @synthesize canscan=_canscan;
@property(nonatomic) float version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *acc; // @synthesize acc=_acc;
@property(retain, nonatomic) NSString *orderWebsite; // @synthesize orderWebsite=_orderWebsite;
@property(retain, nonatomic) NSString *order; // @synthesize order=_order;
@property(retain, nonatomic) NSString *touchID; // @synthesize touchID=_touchID;
@property(nonatomic) int treemin; // @synthesize treemin=_treemin;
@property(retain, nonatomic) NSTimer *timer300; // @synthesize timer300=_timer300;
@property(retain, nonatomic) UILabel *textlabel; // @synthesize textlabel=_textlabel;
@property(retain, nonatomic) UILabel *timerString; // @synthesize timerString=_timerString;
@property(retain, nonatomic) UIView *cover; // @synthesize cover=_cover;
@property(nonatomic) int timerChange; // @synthesize timerChange=_timerChange;
@property(nonatomic) int timerCount; // @synthesize timerCount=_timerCount;
@property(retain, nonatomic) NSTimer *timer2; // @synthesize timer2=_timer2;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) _Bool lightingType; // @synthesize lightingType=_lightingType;
@property(retain, nonatomic) UIImageView *lightingImg; // @synthesize lightingImg=_lightingImg;
@property(retain, nonatomic) UIImageView *scanImg; // @synthesize scanImg=_scanImg;
@property(retain, nonatomic) NSMutableDictionary *dic; // @synthesize dic=_dic;
@property(retain, nonatomic) UIView *navView; // @synthesize navView=_navView;
@property(retain, nonatomic) NSMutableArray *CardArray; // @synthesize CardArray=_CardArray;
@property(retain, nonatomic) NSString *capturedBarcode; // @synthesize capturedBarcode=_capturedBarcode;
@property(nonatomic) int viewType; // @synthesize viewType=_viewType;
@property(retain, nonatomic) UIView *barcodeView; // @synthesize barcodeView=_barcodeView;
@property(retain, nonatomic) UIView *scanView; // @synthesize scanView=_scanView;
@property(retain, nonatomic) NSString *strPayId; // @synthesize strPayId=_strPayId;
@property(retain, nonatomic) NSString *strPayType; // @synthesize strPayType=_strPayType;
@property(retain, nonatomic) NSString *strQRCode; // @synthesize strQRCode=_strQRCode;
@property(retain, nonatomic) NSMutableArray *strBarcodeArray; // @synthesize strBarcodeArray=_strBarcodeArray;
@property(retain, nonatomic) UIButton *btnPhoto; // @synthesize btnPhoto=_btnPhoto;
@property(retain, nonatomic) UIButton *btnSwitchInBarcodeView; // @synthesize btnSwitchInBarcodeView=_btnSwitchInBarcodeView;
@property(retain, nonatomic) UIButton *btnSwitchInScanView; // @synthesize btnSwitchInScanView=_btnSwitchInScanView;
@property(retain, nonatomic) UIButton *btnRight; // @synthesize btnRight=_btnRight;
@property(retain, nonatomic) AVCaptureMetadataOutput *captureMetadataOutput; // @synthesize captureMetadataOutput=_captureMetadataOutput;
@property(retain, nonatomic) AVCaptureVideoPreviewLayer *captureLayer; // @synthesize captureLayer=_captureLayer;
@property(retain, nonatomic) AVCaptureSession *captureSession; // @synthesize captureSession=_captureSession;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
@property(retain, nonatomic) EWalletUtils *ewallet; // @synthesize ewallet=_ewallet;
- (void)pressDoneDelegate;
- (void)revealDescription:(id)arg1;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)switchIsChanged:(id)arg1;
- (void)system_maintenance:(id)arg1;
- (void)test;
- (void)didIsPointRedeemFailed:(id)arg1;
- (void)didIsPointRedeemSuccess:(id)arg1;
- (void)didIsFirstLoginFailed:(id)arg1;
- (void)didIsFirstLoginSuccess:(id)arg1;
- (void)GET_TRANSACTIONDETAIL_SUCCESS:(id)arg1;
- (void)qrcodeNotification_FAILD:(id)arg1;
- (void)qrcodeNotification_SUCCESS:(id)arg1;
- (void)qrcodeNotification_Processing:(id)arg1;
- (void)t60:(id)arg1;
- (void)posturl;
- (void)btnRight:(id)arg1;
- (void)CREATE_QRCODE_FAILED:(id)arg1;
- (void)CREATE_QRCODE_SUCCESS:(id)arg1;
- (void)GET_MEMBER_SET_PWDATA_FAILED:(id)arg1;
- (void)VERIFY_PW_FAILED:(id)arg1;
- (void)VERIFY_PW_SUCCESS:(id)arg1;
- (void)GET_MEMBER_SET_PWDATA_SUCCESS:(id)arg1;
- (void)changeScan:(id)arg1 res:(id)arg2;
- (id)recognizeQRCodeFromImage:(id)arg1;
- (void)imagePickerController:(id)arg1 didFinishPickingMediaWithInfo:(id)arg2;
- (void)btnPhoto:(id)arg1;
- (void)btnSwitch:(id)arg1;
- (void)back:(id)arg1;
- (void)lookBarCode:(id)arg1;
- (void)completeCheckQRCodeCallBackWithReturnMsg:(id)arg1;
- (void)captureOutput:(id)arg1 didOutputMetadataObjects:(id)arg2 fromConnection:(id)arg3;
- (void)setupScanningSession;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (id)barCodeImageWithInfo:(id)arg1;
- (void)createBarcodeView;
- (void)createScanView;
- (void)lightingbtn:(id)arg1;
- (void)turnTorchOn:(_Bool)arg1;
- (void)apiError:(id)arg1;
- (void)didQRCodeBuyerScanFailed:(id)arg1;
- (void)p2p:(id)arg1;
- (void)sysCodeFailed:(id)arg1;
- (void)didQRCodeBuyerScanSuccess:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)someMethod:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

