//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MajorViewController.h"

#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegate.h"
#import "UICollectionViewDelegateFlowLayout.h"

@class APIDataManager, LAContext, NSMutableArray, NSNumber, NSString, NSTimer, UICollectionView;

@interface SelectCardVC : MajorViewController <UICollectionViewDelegate, UICollectionViewDataSource, UICollectionViewDelegateFlowLayout>
{
    _Bool _quickPay;
    int _viewType;
    UICollectionView *_collV;
    APIDataManager *_dataManager;
    NSMutableArray *_creditCardArray;
    NSMutableArray *_bankAccountArray;
    NSMutableArray *_cardArray;
    NSString *_payType;
    NSNumber *_payId;
    NSString *_token;
    LAContext *_touchId;
    long long _qrCodeCreateTime;
    NSTimer *_timer;
}

- (void).cxx_destruct;
@property(nonatomic) _Bool quickPay; // @synthesize quickPay=_quickPay;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(nonatomic) long long qrCodeCreateTime; // @synthesize qrCodeCreateTime=_qrCodeCreateTime;
@property(retain, nonatomic) LAContext *touchId; // @synthesize touchId=_touchId;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;
@property(nonatomic) int viewType; // @synthesize viewType=_viewType;
@property(retain, nonatomic) NSNumber *payId; // @synthesize payId=_payId;
@property(retain, nonatomic) NSString *payType; // @synthesize payType=_payType;
@property(retain, nonatomic) NSMutableArray *cardArray; // @synthesize cardArray=_cardArray;
@property(retain, nonatomic) NSMutableArray *bankAccountArray; // @synthesize bankAccountArray=_bankAccountArray;
@property(retain, nonatomic) NSMutableArray *creditCardArray; // @synthesize creditCardArray=_creditCardArray;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
@property(retain, nonatomic) UICollectionView *collV; // @synthesize collV=_collV;
- (void)system_maintenance:(id)arg1;
- (void)CREATE_QRCODE_FAILED:(id)arg1;
- (void)CREATE_QRCODE_SUCCESS:(id)arg1;
- (void)createCollectionView;
- (void)selectBtnTag:(id)arg1;
- (void)btnFinsh;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)countTimer;
- (void)removeNavVC;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

