//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCTableViewController.h"

#import "NSURLConnectionDataDelegate.h"
#import "NSURLConnectionDelegate.h"

@class NSLayoutConstraint, NSMutableArray, NSMutableData, NSString, UITextField;

@interface ServiceAudioViewController : HNCTableViewController <NSURLConnectionDataDelegate, NSURLConnectionDelegate>
{
    NSLayoutConstraint *_serviceAudioListHeightConstraint;
    NSString *_audioDialVOIPNum;
    UITextField *_questionTypesTextField;
    NSString *_questionTypesAudioDialVOIPNum;
    NSMutableData *_responseQuestionTypesData;
    NSMutableArray *_questionTypesArray;
}

@property(retain, nonatomic) NSMutableArray *questionTypesArray; // @synthesize questionTypesArray=_questionTypesArray;
@property(retain, nonatomic) NSMutableData *responseQuestionTypesData; // @synthesize responseQuestionTypesData=_responseQuestionTypesData;
@property(retain, nonatomic) NSString *questionTypesAudioDialVOIPNum; // @synthesize questionTypesAudioDialVOIPNum=_questionTypesAudioDialVOIPNum;
@property(retain, nonatomic) UITextField *questionTypesTextField; // @synthesize questionTypesTextField=_questionTypesTextField;
@property(retain, nonatomic) NSString *audioDialVOIPNum; // @synthesize audioDialVOIPNum=_audioDialVOIPNum;
@property(retain, nonatomic) NSLayoutConstraint *serviceAudioListHeightConstraint; // @synthesize serviceAudioListHeightConstraint=_serviceAudioListHeightConstraint;
- (void)sendNodeLogWithMediaType:(id)arg1;
- (void)connection:(id)arg1 didFailWithError:(id)arg2;
- (void)connectionDidFinishLoading:(id)arg1;
- (void)connection:(id)arg1 didReceiveData:(id)arg2;
- (void)sendQuestionTypesTelegram;
- (id)getAudioDialVOIPNum:(id)arg1;
- (id)getSubsysSettingJson;
- (void)tableFootViewButtonClickEvent:(id)arg1;
- (void)mmbPickerViewBtnDoneClickEvent:(id)arg1;
- (id)pickerView:(id)arg1 titleForRow:(long long)arg2 forComponent:(long long)arg3;
- (long long)pickerView:(id)arg1 numberOfRowsInComponent:(long long)arg2;
- (long long)numberOfComponentsInPickerView:(id)arg1;
- (_Bool)textFieldShouldBeginEditing:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)prepareForSegue:(id)arg1 sender:(id)arg2;
- (void)dealloc;
- (void)updateViewConstraints;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

