//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCViewController.h"

@class NSString, NSTimer, UILabel;

@interface ServiceAudioDialVOIPViewController : HNCViewController
{
    _Bool _callState;
    _Bool _callTimerFlag;
    NSString *_userName;
    NSString *_userGender;
    NSString *_userQuestion;
    NSString *_audioDialVOIPNum;
    NSString *_paramter;
    UILabel *_timeLabel;
    UILabel *_dialStatusLabel;
    NSString *_regStateMsg;
    NSTimer *_registerStateTimer;
    NSTimer *_checkStateTimer;
    NSTimer *_callStateTimer;
    NSTimer *_timer;
    long long _sec;
    long long _min;
}

@property(nonatomic) long long min; // @synthesize min=_min;
@property(nonatomic) long long sec; // @synthesize sec=_sec;
@property(nonatomic) _Bool callTimerFlag; // @synthesize callTimerFlag=_callTimerFlag;
@property(nonatomic) _Bool callState; // @synthesize callState=_callState;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) NSTimer *callStateTimer; // @synthesize callStateTimer=_callStateTimer;
@property(retain, nonatomic) NSTimer *checkStateTimer; // @synthesize checkStateTimer=_checkStateTimer;
@property(retain, nonatomic) NSTimer *registerStateTimer; // @synthesize registerStateTimer=_registerStateTimer;
@property(retain, nonatomic) NSString *regStateMsg; // @synthesize regStateMsg=_regStateMsg;
@property(retain, nonatomic) UILabel *dialStatusLabel; // @synthesize dialStatusLabel=_dialStatusLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) NSString *paramter; // @synthesize paramter=_paramter;
@property(retain, nonatomic) NSString *audioDialVOIPNum; // @synthesize audioDialVOIPNum=_audioDialVOIPNum;
@property(retain, nonatomic) NSString *userQuestion; // @synthesize userQuestion=_userQuestion;
@property(retain, nonatomic) NSString *userGender; // @synthesize userGender=_userGender;
@property(retain, nonatomic) NSString *userName; // @synthesize userName=_userName;
- (void)onHandUpClick:(id)arg1;
- (void)timerUpdate;
- (void)callStateUpdate;
- (void)checkStateUpdate;
- (void)registerStateUpdate;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

