//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class UIButton, UILabel;

@interface SettingDefaultHomeCell : UICollectionViewCell
{
    UIButton *_radioBtn;
    UILabel *_titleName;
    UILabel *_subName;
    UILabel *_defultLabel;
}

@property(retain, nonatomic) UILabel *defultLabel; // @synthesize defultLabel=_defultLabel;
@property(retain, nonatomic) UILabel *subName; // @synthesize subName=_subName;
@property(retain, nonatomic) UILabel *titleName; // @synthesize titleName=_titleName;
@property(retain, nonatomic) UIButton *radioBtn; // @synthesize radioBtn=_radioBtn;
- (id)initWithFrame:(struct CGRect)arg1;

@end

