//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class UIImageView;

@interface ShadowImageView : UIView
{
    UIImageView *imgView;
    struct CGSize sizeShadow;
}

@property(nonatomic) struct CGSize sizeShadow; // @synthesize sizeShadow;
@property(retain, nonatomic) UIImageView *imgView; // @synthesize imgView;
- (void)dealloc;
- (void)drawRect:(struct CGRect)arg1;
- (void)layoutSubviews;
- (id)initWithImage:(id)arg1;

@end

