//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCWebKitViewController.h"

@class NSString;

@interface SmartFinancialViewController : HNCWebKitViewController
{
    NSString *_guideWFID;
    NSString *_funcTXID;
    NSString *_smartFinancialUrl;
    NSString *_alertViewEventName;
}

@property(retain, nonatomic) NSString *alertViewEventName; // @synthesize alertViewEventName=_alertViewEventName;
@property(retain, nonatomic) NSString *smartFinancialUrl; // @synthesize smartFinancialUrl=_smartFinancialUrl;
@property(retain, nonatomic) NSString *funcTXID; // @synthesize funcTXID=_funcTXID;
@property(retain, nonatomic) NSString *guideWFID; // @synthesize guideWFID=_guideWFID;
- (void)WebServiceObject:(id)arg1 didCompleteCallHNCBAPIWithHeader:(id)arg2 withCallHNCBAPIResponseBody:(id)arg3;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)webView:(id)arg1 decidePolicyForNavigationAction:(id)arg2 decisionHandler:(CDUnknownBlockType)arg3;
- (void)webView:(id)arg1 didReceiveAuthenticationChallenge:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)dealloc;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;

@end

