//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MajorViewController.h"

#import "UITextFieldDelegate.h"

@class APIDataManager, EWalletData, EWalletUtils, NSMutableAttributedString, NSString, NSTimer, NSUserDefaults, UIButton, UILabel, UIProgressView, UITextField, UIView;

@interface SMSAuthenticationViewController : MajorViewController <UITextFieldDelegate>
{
    _Bool _checking;
    float _addPrgressValue;
    float _version;
    APIDataManager *_dataManager;
    UIButton *_btnRight;
    UIButton *_btnResendAuthCode;
    UILabel *_lbTime;
    UILabel *_lbResendTime;
    UITextField *_txtAuthCode;
    UIProgressView *_progressView;
    NSTimer *_timer;
    NSTimer *_resendTimer;
    long long _time;
    long long _resendTime;
    NSMutableAttributedString *_strMin;
    NSMutableAttributedString *_strSecond;
    NSString *_strAccNo;
    NSString *_strNickname;
    NSUserDefaults *_userDefault;
    long long _codeTimeLimit;
    long long _resendTimeLimit;
    long long _actionType;
    NSString *_nMypwordType;
    NSString *_nMypword;
    UILabel *_lbMobile;
    EWalletUtils *_ewallet;
    EWalletData *_eWalletData;
    NSString *_defult;
    NSString *_qrcode;
    UIView *_top;
    NSString *_bindId;
    NSString *_cvc;
    NSString *_cardExpireDate;
    NSString *_creditCardPhoneNum;
    NSString *_staff;
    NSString *_bankBranch;
    NSString *_areaCode;
    NSString *_maId;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *maId; // @synthesize maId=_maId;
@property(retain, nonatomic) NSString *areaCode; // @synthesize areaCode=_areaCode;
@property(retain, nonatomic) NSString *bankBranch; // @synthesize bankBranch=_bankBranch;
@property(retain, nonatomic) NSString *staff; // @synthesize staff=_staff;
@property(retain, nonatomic) NSString *creditCardPhoneNum; // @synthesize creditCardPhoneNum=_creditCardPhoneNum;
@property(retain, nonatomic) NSString *cardExpireDate; // @synthesize cardExpireDate=_cardExpireDate;
@property(retain, nonatomic) NSString *cvc; // @synthesize cvc=_cvc;
@property(retain, nonatomic) NSString *bindId; // @synthesize bindId=_bindId;
@property(retain, nonatomic) UIView *top; // @synthesize top=_top;
@property(nonatomic) float version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *qrcode; // @synthesize qrcode=_qrcode;
@property(retain, nonatomic) NSString *defult; // @synthesize defult=_defult;
@property(retain, nonatomic) EWalletData *eWalletData; // @synthesize eWalletData=_eWalletData;
@property(retain, nonatomic) EWalletUtils *ewallet; // @synthesize ewallet=_ewallet;
@property(nonatomic) _Bool checking; // @synthesize checking=_checking;
@property(retain, nonatomic) UILabel *lbMobile; // @synthesize lbMobile=_lbMobile;
@property(retain, nonatomic) NSString *nMypword; // @synthesize nMypword=_nMypword;
@property(retain, nonatomic) NSString *nMypwordType; // @synthesize nMypwordType=_nMypwordType;
@property(nonatomic) long long actionType; // @synthesize actionType=_actionType;
@property(nonatomic) long long resendTimeLimit; // @synthesize resendTimeLimit=_resendTimeLimit;
@property(nonatomic) long long codeTimeLimit; // @synthesize codeTimeLimit=_codeTimeLimit;
@property(retain, nonatomic) NSUserDefaults *userDefault; // @synthesize userDefault=_userDefault;
@property(retain, nonatomic) NSString *strNickname; // @synthesize strNickname=_strNickname;
@property(retain, nonatomic) NSString *strAccNo; // @synthesize strAccNo=_strAccNo;
@property(retain, nonatomic) NSMutableAttributedString *strSecond; // @synthesize strSecond=_strSecond;
@property(retain, nonatomic) NSMutableAttributedString *strMin; // @synthesize strMin=_strMin;
@property(nonatomic) float addPrgressValue; // @synthesize addPrgressValue=_addPrgressValue;
@property(nonatomic) long long resendTime; // @synthesize resendTime=_resendTime;
@property(nonatomic) long long time; // @synthesize time=_time;
@property(retain, nonatomic) NSTimer *resendTimer; // @synthesize resendTimer=_resendTimer;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) UIProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) UITextField *txtAuthCode; // @synthesize txtAuthCode=_txtAuthCode;
@property(retain, nonatomic) UILabel *lbResendTime; // @synthesize lbResendTime=_lbResendTime;
@property(retain, nonatomic) UILabel *lbTime; // @synthesize lbTime=_lbTime;
@property(retain, nonatomic) UIButton *btnResendAuthCode; // @synthesize btnResendAuthCode=_btnResendAuthCode;
@property(retain, nonatomic) UIButton *btnRight; // @synthesize btnRight=_btnRight;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
- (void)system_maintenance:(id)arg1;
- (void)verifyCreditCardOTPSuccessFailed:(id)arg1;
- (void)verifyCreditCardOTPSuccess:(id)arg1;
- (void)verifyCreditCardInfoSuccessFailed:(id)arg1;
- (void)verifyCreditCardInfoSuccess:(id)arg1;
- (void)bindMMDeviceOTPFailed:(id)arg1;
- (void)bindMMDeviceOTPSuccess:(id)arg1;
- (void)verifyOTPFailed:(id)arg1;
- (void)verifyOTPSuccess:(id)arg1;
- (void)sendOTPFailed:(id)arg1;
- (void)sendOTPSuccess:(id)arg1;
- (void)didIsFirstLoginFailed:(id)arg1;
- (void)didIsFirstLoginSuccess:(id)arg1;
- (void)registerWalletFailed:(id)arg1;
- (void)registerWalletSuccess:(id)arg1;
- (void)resendOTPFailed:(id)arg1;
- (void)resendOTPSuccess:(id)arg1;
- (void)verifyAccFailed:(id)arg1;
- (void)verifyAccSuccess:(id)arg1;
- (void)addAccTmpFailed:(id)arg1;
- (void)addAccTmpSuccess:(id)arg1;
- (void)resendTimerAction;
- (void)countDown;
- (void)txtAuthCodeChanged:(id)arg1;
- (_Bool)textField:(id)arg1 shouldChangeCharactersInRange:(struct _NSRange)arg2 replacementString:(id)arg3;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (_Bool)textFieldShouldReturn:(id)arg1;
- (void)textFieldDidEndEditing:(id)arg1;
- (void)getAuthCode:(id)arg1;
- (void)btnRight:(id)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)becomeActive:(id)arg1;
- (void)didUpdatePwFailed:(id)arg1;
- (void)didUpdatePwSuccess:(id)arg1;
- (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)viewWillAppear:(_Bool)arg1;
- (void)createContentView;
- (void)setOTPTimer:(long long)arg1;
- (void)startResendTimer:(long long)arg1;
- (void)dealloc;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)back:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

