//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FMDatabaseQueue;

@interface SystemDBService : NSObject
{
    FMDatabaseQueue *_systemInstance_FMDatabaseQueue;
}

+ (id)getInstance;
@property(retain, nonatomic) FMDatabaseQueue *systemInstance_FMDatabaseQueue; // @synthesize systemInstance_FMDatabaseQueue=_systemInstance_FMDatabaseQueue;
- (_Bool)saveCPUStatus:(id)arg1 identifier:(id)arg2 status:(id)arg3;
- (_Bool)saveCallParams:(id)arg1 identifier:(id)arg2 codec:(id)arg3 audioUploadBand:(id)arg4 audioDownloadBand:(id)arg5 videoUploadBand:(id)arg6 videoDownloadBand:(id)arg7;
- (_Bool)saveCallQualityStatus:(id)arg1 identifier:(id)arg2 status:(id)arg3;
- (_Bool)saveCallStatus:(id)arg1 identifier:(id)arg2 status:(id)arg3;
- (_Bool)saveRegisterStatus:(id)arg1 identifier:(id)arg2 status:(id)arg3;
- (_Bool)saveMessage:(id)arg1 identifier:(id)arg2 contentType:(id)arg3 action:(id)arg4 content:(id)arg5;
- (void)saveDeviceInfo:(id)arg1;
- (void)clearData;
- (id)init;

@end

