//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MajorViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class APIDataManager, NSMutableArray, NSString, UIButton, UILabel, UITableView;

@interface TaipowerPaymentViewController : MajorViewController <UITableViewDelegate, UITableViewDataSource>
{
    APIDataManager *_dataManager;
    NSMutableArray *_tpArray;
    NSMutableArray *_sumArray;
    NSMutableArray *_dicArray;
    NSMutableArray *_Comparison;
    UIButton *_checkbox;
    UITableView *_tableView;
    NSMutableArray *_selectIndexs;
    UILabel *_amt;
    NSString *_tmId;
    NSString *_payId;
    NSString *_payType;
    NSString *_defaultMemberCode;
    NSString *_mmSwName;
    NSString *_mmPhoneCode;
}

- (void).cxx_destruct;
@property(retain, nonatomic) NSString *mmPhoneCode; // @synthesize mmPhoneCode=_mmPhoneCode;
@property(retain, nonatomic) NSString *mmSwName; // @synthesize mmSwName=_mmSwName;
@property(retain, nonatomic) NSString *defaultMemberCode; // @synthesize defaultMemberCode=_defaultMemberCode;
@property(retain, nonatomic) NSString *payType; // @synthesize payType=_payType;
@property(retain, nonatomic) NSString *payId; // @synthesize payId=_payId;
@property(retain, nonatomic) NSString *tmId; // @synthesize tmId=_tmId;
@property(retain, nonatomic) UILabel *amt; // @synthesize amt=_amt;
@property(retain, nonatomic) NSMutableArray *selectIndexs; // @synthesize selectIndexs=_selectIndexs;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) UIButton *checkbox; // @synthesize checkbox=_checkbox;
@property(retain, nonatomic) NSMutableArray *Comparison; // @synthesize Comparison=_Comparison;
@property(retain, nonatomic) NSMutableArray *dicArray; // @synthesize dicArray=_dicArray;
@property(retain, nonatomic) NSMutableArray *sumArray; // @synthesize sumArray=_sumArray;
@property(retain, nonatomic) NSMutableArray *tpArray; // @synthesize tpArray=_tpArray;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
- (void)BuyerScanTradingFailed:(id)arg1;
- (void)BuyerScanTradingSuccess:(id)arg1;
- (void)btnRight:(id)arg1;
- (void)selectAll:(id)arg1;
- (id)dayFormat:(id)arg1;
- (id)amtFormat:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)checkAmt:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)tpView;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

