//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "MajorViewController.h"

#import "RevealDescriptionViewDeleaget.h"
#import "UINavigationBarDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class APIDataManager, BonusView, BonusdetailsData, NSMutableArray, NSMutableDictionary, NSNumber, NSString, RevealDescriptionView, UIButton, UIScrollView, UITableView, UIView;

@interface TransactionRecordDetailViewController : MajorViewController <RevealDescriptionViewDeleaget, UITableViewDelegate, UITableViewDataSource, UINavigationBarDelegate>
{
    _Bool _isFirst;
    int _actionType;
    APIDataManager *_dataManager;
    UITableView *_detailTableView;
    NSMutableDictionary *_dictDetail;
    NSMutableDictionary *_dictTitle;
    NSNumber *_tmId;
    NSMutableDictionary *_dic;
    NSMutableArray *_arraykey;
    NSString *_back;
    NSString *_txtTransactionNo;
    NSString *_type;
    NSNumber *_page;
    NSString *_startDate;
    NSString *_endDate;
    UIScrollView *_detailScrollView;
    UIView *_lastBottomLine;
    CDUnknownBlockType _isBackBlock;
    UIButton *_btnRight;
    UIView *_blankView;
    UIView *_bonusBackView;
    BonusView *_bonusView;
    NSMutableArray *_headerNames;
    NSMutableArray *_totals;
    BonusdetailsData *_bonusdetailsData;
    UIButton *_imgBonucicon;
    UIView *_bonusBlockView;
    RevealDescriptionView *_descriptionView;
}

- (void).cxx_destruct;
@property(retain, nonatomic) RevealDescriptionView *descriptionView; // @synthesize descriptionView=_descriptionView;
@property(retain, nonatomic) UIView *bonusBlockView; // @synthesize bonusBlockView=_bonusBlockView;
@property(retain, nonatomic) UIButton *imgBonucicon; // @synthesize imgBonucicon=_imgBonucicon;
@property(nonatomic) __weak BonusdetailsData *bonusdetailsData; // @synthesize bonusdetailsData=_bonusdetailsData;
@property(retain, nonatomic) NSMutableArray *totals; // @synthesize totals=_totals;
@property(retain, nonatomic) NSMutableArray *headerNames; // @synthesize headerNames=_headerNames;
@property(retain, nonatomic) BonusView *bonusView; // @synthesize bonusView=_bonusView;
@property(retain, nonatomic) UIView *bonusBackView; // @synthesize bonusBackView=_bonusBackView;
@property(retain, nonatomic) UIView *blankView; // @synthesize blankView=_blankView;
@property(nonatomic) _Bool isFirst; // @synthesize isFirst=_isFirst;
@property(retain, nonatomic) UIButton *btnRight; // @synthesize btnRight=_btnRight;
@property(nonatomic) int actionType; // @synthesize actionType=_actionType;
@property(copy, nonatomic) CDUnknownBlockType isBackBlock; // @synthesize isBackBlock=_isBackBlock;
@property(retain, nonatomic) UIView *lastBottomLine; // @synthesize lastBottomLine=_lastBottomLine;
@property(retain, nonatomic) UIScrollView *detailScrollView; // @synthesize detailScrollView=_detailScrollView;
@property(retain, nonatomic) NSString *endDate; // @synthesize endDate=_endDate;
@property(retain, nonatomic) NSString *startDate; // @synthesize startDate=_startDate;
@property(retain, nonatomic) NSNumber *page; // @synthesize page=_page;
@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *txtTransactionNo; // @synthesize txtTransactionNo=_txtTransactionNo;
@property(retain, nonatomic) NSString *back; // @synthesize back=_back;
@property(retain, nonatomic) NSMutableArray *arraykey; // @synthesize arraykey=_arraykey;
@property(retain, nonatomic) NSMutableDictionary *dic; // @synthesize dic=_dic;
@property(retain, nonatomic) NSNumber *tmId; // @synthesize tmId=_tmId;
@property(retain, nonatomic) NSMutableDictionary *dictTitle; // @synthesize dictTitle=_dictTitle;
@property(retain, nonatomic) NSMutableDictionary *dictDetail; // @synthesize dictDetail=_dictDetail;
@property(retain, nonatomic) UITableView *detailTableView; // @synthesize detailTableView=_detailTableView;
@property(retain, nonatomic) APIDataManager *dataManager; // @synthesize dataManager=_dataManager;
- (void)pressDoneDelegate;
- (void)revealDescription:(id)arg1;
- (void)system_maintenance:(id)arg1;
- (_Bool)IsSpecialSymbol:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)createContentView;
- (void)closeDetailPage:(id)arg1;
- (void)btnRight:(id)arg1;
- (void)showRefundQRCode;
- (void)didGetTransactionDetailFailed:(id)arg1;
- (void)didGetTransactionDetailSuccess:(id)arg1;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didReceiveMemoryWarning;
- (void)backRecord;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

