//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIIconButton.h"

@class UITextField;

@interface UIDigitButton : UIIconButton
{
    _Bool dtmf;
    BOOL digit;
    UITextField *addressField;
}

@property(retain, nonatomic) UITextField *addressField; // @synthesize addressField;
@property BOOL digit; // @synthesize digit;
@property _Bool dtmf; // @synthesize dtmf;
- (void)touchUp:(id)arg1;
- (void)touchDown:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;
- (void)initUIDigitButton;

@end

