//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class NSString;

@interface UINumberButton : UIButton
{
    NSString *_number;
    NSString *_audio;
    NSString *_video;
    NSString *_chat;
    NSString *_latitude;
    NSString *_longitude;
    NSString *_tel;
    NSString *_email;
    NSString *_type;
}

@property(retain, nonatomic) NSString *type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *email; // @synthesize email=_email;
@property(retain, nonatomic) NSString *tel; // @synthesize tel=_tel;
@property(retain, nonatomic) NSString *longitude; // @synthesize longitude=_longitude;
@property(retain, nonatomic) NSString *latitude; // @synthesize latitude=_latitude;
@property(retain, nonatomic) NSString *chat; // @synthesize chat=_chat;
@property(retain, nonatomic) NSString *video; // @synthesize video=_video;
@property(retain, nonatomic) NSString *audio; // @synthesize audio=_audio;
@property(retain, nonatomic) NSString *number; // @synthesize number=_number;

@end

