//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIToggleButton.h"

#import "UIToggleButtonDelegate.h"

@interface UIPauseButton : UIToggleButton <UIToggleButtonDelegate>
{
    int type;
    struct _LinphoneCall *call;
}

+ (struct _LinphoneCall *)getCall;
+ (_Bool)isInConference:(struct _LinphoneCall *)arg1;
- (_Bool)onUpdate;
- (void)onOff;
- (void)onOn;
- (void)setType:(int)arg1 call:(struct _LinphoneCall *)arg2;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)initUIPauseButton;

@end

