//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

@interface UIScrollView (SDAutoContentSize)
- (void)setupAutoContentSizeWithRightView:(id)arg1 rightMargin:(double)arg2;
- (void)setupAutoContentSizeWithBottomView:(id)arg1 bottomMargin:(double)arg2;
@end

