//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIToggleButton.h"

#import "UIToggleButtonDelegate.h"

@interface UISpeakerButton : UIToggleButton <UIToggleButtonDelegate>
{
}

- (_Bool)onUpdate;
- (void)onOff;
- (void)onOn;
- (void)audioRouteChangeListenerCallback:(id)arg1;
- (void)dealloc;

@end

