//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIIconButton.h"

#import "UIToggleButtonDelegate.h"

@interface UIToggleButton : UIIconButton <UIToggleButtonDelegate>
{
}

- (_Bool)onUpdate;
- (void)onOff;
- (void)onOn;
- (_Bool)update;
- (void)setOff;
- (void)setOn;
- (_Bool)toggle;
- (void)touchUp:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)init;
- (void)initUIToggleButton;

@end

