//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSNumber;

@interface UIView (SDLayoutExtention)
- (void)sd_addSubviews:(id)arg1;
@property(retain, nonatomic) NSArray *sd_equalWidthSubviews;
@property(retain, nonatomic) NSNumber *sd_cornerRadiusFromHeightRatio;
@property(retain, nonatomic) NSNumber *sd_cornerRadiusFromWidthRatio;
@property(retain, nonatomic) NSNumber *sd_cornerRadius;
@property(copy, nonatomic) CDUnknownBlockType didFinishAutoLayoutBlock;
@end

