//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class NSArray, NSMutableArray, SDUIViewCategoryManager;

@interface UIView (SDAutoHeightWidth)
@property(nonatomic) double sd_rightViewRightMargin;
@property(nonatomic) double sd_bottomViewBottomMargin;
@property(retain, nonatomic) NSArray *sd_rightViewsArray;
@property(readonly, nonatomic) NSMutableArray *sd_bottomViewsArray;
@property(nonatomic) double autoHeight;
- (void)updateLayoutWithCellContentView:(id)arg1;
- (void)updateLayout;
- (void)clearAutoWidthSettings;
- (void)clearAutoHeigtSettings;
- (void)setupAutoHeightWithBottomViewsArray:(id)arg1 bottomMargin:(double)arg2;
- (void)setupAutoWidthWithRightView:(id)arg1 rightMargin:(double)arg2;
- (void)setupAutoHeightWithBottomView:(id)arg1 bottomMargin:(double)arg2;
@property(readonly, nonatomic) SDUIViewCategoryManager *sd_categoryManager;
@end

