//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "HNCTableViewController.h"

@class NSLayoutConstraint, NSTimer;

@interface VersionInfoViewController : HNCTableViewController
{
    NSLayoutConstraint *_versionInfoListHeightConstraint;
    NSTimer *_countdownCalculateClickVersionDataCellTimesTimer;
    long long _clickVersionDataCellTimes;
}

@property(nonatomic) long long clickVersionDataCellTimes; // @synthesize clickVersionDataCellTimes=_clickVersionDataCellTimes;
@property(retain, nonatomic) NSTimer *countdownCalculateClickVersionDataCellTimesTimer; // @synthesize countdownCalculateClickVersionDataCellTimesTimer=_countdownCalculateClickVersionDataCellTimesTimer;
@property(retain, nonatomic) NSLayoutConstraint *versionInfoListHeightConstraint; // @synthesize versionInfoListHeightConstraint=_versionInfoListHeightConstraint;
- (void)timeoutCountdownCalculateEvent;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didReceiveMemoryWarning;
- (void)dealloc;
- (void)updateViewConstraints;
- (void)viewDidLoad;

@end

