//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class HNCResponseHeader, NSData, NSMutableDictionary, WebServiceObject;

@protocol WebServiceObjectDelegate

@optional
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompletePH00EWithHeader:(HNCResponseHeader *)arg2 withPH00EResponseBody:(NSData *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompletePH00DWithHeader:(HNCResponseHeader *)arg2 withPH00DResponseBody:(NSData *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompletePH00CWithHeader:(HNCResponseHeader *)arg2 withPH00CResponseBody:(NSData *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompletePH00AWithHeader:(HNCResponseHeader *)arg2 withPH00AResponseBody:(NSData *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompletePH009WithHeader:(HNCResponseHeader *)arg2 withPH009ResponseBody:(NSData *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompletePH008WithHeader:(HNCResponseHeader *)arg2 withPH008ResponseBody:(NSData *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompletePH007WithHeader:(HNCResponseHeader *)arg2 withPH007ResponseBody:(NSData *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompletePH004WithHeader:(HNCResponseHeader *)arg2 withPH004ResponseBody:(NSData *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompletePH003WithHeader:(HNCResponseHeader *)arg2 withPH003ResponseBody:(NSData *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompletePH002WithHeader:(HNCResponseHeader *)arg2 withPH002ResponseBody:(NSData *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompletePH001WithHeader:(HNCResponseHeader *)arg2 withPH001ResponseBody:(NSData *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompletePH000WithHeader:(HNCResponseHeader *)arg2 withPH000ResponseBody:(NSData *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteGenAuthenticateParamWithHeader:(HNCResponseHeader *)arg2 withGenAuthenticateParamResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteCallHNCBAPIWithHeader:(HNCResponseHeader *)arg2 withCallHNCBAPIResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteCustServiceWithHeader:(HNCResponseHeader *)arg2 withCustServiceResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteArxanExceptionHandlerWithHeader:(HNCResponseHeader *)arg2 withArxanExceptionHandlerResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteCheckQRCodeP2PWithHeader:(HNCResponseHeader *)arg2 withCheckQRCodeP2PResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteGetUserAccountWithHeader:(HNCResponseHeader *)arg2 withGetUserAccountResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteSignEndWithHeader:(HNCResponseHeader *)arg2 withSignEndResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteSignBeginWithHeader:(HNCResponseHeader *)arg2 withSignBeginResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteAuthenticateWithHeader:(HNCResponseHeader *)arg2 withAuthenticateResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteListDevicesWithHeader:(HNCResponseHeader *)arg2 withListDevicesResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteQuickLoginWithHeader:(HNCResponseHeader *)arg2 withQuickLoginResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteQuickLoginSettingWithHeader:(HNCResponseHeader *)arg2 withQuickLoginSettingResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteGOB0001WithHeader:(HNCResponseHeader *)arg2 withGOB0001ResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteAT0003WithHeader:(HNCResponseHeader *)arg2 withAT0003ResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteAT0002WithHeader:(HNCResponseHeader *)arg2 withAT0002ResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteAT0001WithHeader:(HNCResponseHeader *)arg2 withAT0001ResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteAP0021WithHeader:(HNCResponseHeader *)arg2 withAP0021ResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteAP0013WithHeader:(HNCResponseHeader *)arg2 withAP0013ResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteAP0011WithHeader:(HNCResponseHeader *)arg2 withAP0011ResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteAP0010WithHeader:(HNCResponseHeader *)arg2 withAP0010ResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteAP0008WithHeader:(HNCResponseHeader *)arg2 withAP0008ResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteAP0006WithHeader:(HNCResponseHeader *)arg2 withAP0006ResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteAP0004WithHeader:(HNCResponseHeader *)arg2 withAP0004ResponseBody:(NSMutableDictionary *)arg3;
- (void)WebServiceObject:(WebServiceObject *)arg1 didCompleteAP0001WithHeader:(HNCResponseHeader *)arg2 withAP0001ResponseBody:(NSMutableDictionary *)arg3;
@end

